openshift/cluster-version-operator

pkg/apis/clusterversion.openshift.io/v1/types.go
pkg/apis/clusterversion.openshift.io/v1/zz_generated.deepcopy.go
pkg/cincinnati/cincinnati.go
pkg/cvo/update.go

Rather than just showing the payload, the status will now show the
version number. This is needed if payloads don't use human-readable tags
or if they use digests instead.

cvo: report entire update in status

---

Gopkg.lock
Gopkg.toml
pkg/apis/clusterversion.openshift.io/v1/types.go
pkg/apis/clusterversion.openshift.io/v1/zz_generated.deepcopy.go
pkg/cvo/cvo.go
pkg/cvo/update.go
vendor/k8s.io/utils/LICENSE
vendor/k8s.io/utils/pointer/pointer.go

When an operator wants to trigger an update, they can write the update
payload and version into the CVOConfig. This will cause the CVO to
update its deployment to use that image instead, rolling the CVO to the
specified version.

cvo: add ability to apply updates

---

Gopkg.lock
cmd/start.go
lib/manifest.go
lib/manifest_test.go
lib/resourceapply/batch.go
lib/resourceapply/core.go
lib/resourceapply/rbac.go
lib/resourcebuilder/apiext.go
lib/resourcebuilder/apps.go
lib/resourcebuilder/batch.go
lib/resourcebuilder/core.go
lib/resourcebuilder/interface.go
lib/resourcebuilder/rbac.go
lib/resourcemerge/batch.go
lib/resourcemerge/core.go
lib/resourcemerge/cv.go
lib/resourcemerge/rbac.go
lib/resourceread/apiext.go
lib/resourceread/apps.go
lib/resourceread/batch.go
lib/resourceread/core.go
lib/resourceread/rbac.go
pkg/cvo/cvo.go
pkg/cvo/sync.go
vendor/k8s.io/apimachinery/pkg/util/rand/rand.go

* adds funcs to load manifests from disk
* add resource builder that allows Do on any **lib.Manifest**
* adds syncUpdatePayloadContents that ensures <prefix>/<version>
contains the <version> update payload
* adds syncUpdatePayload that uses lib.resourcebuilder to generically
apply the update payload in order.
/assign @crawford @yifan-gu

Add CVO sync from payload

---

cmd/start.go
pkg/autoupdate/autoupdate.go
pkg/autoupdate/autoupdate_test.go

autoupdate controller sets the DesiredUpdate for CVOConfig to the greatest available version from OperatorStatus AvailabeUpdates.
Requires #10 
/cc @crawford @smarterclayton 
/assign @crawford @smarterclayton

Add: autoupdate controller

---

cmd/main.go
cmd/render.go
cmd/start.go
install/00_clusterversionoperator_04_deployment.yaml
lib/resourcebuilder/interface.go
pkg/cvo/cvo.go
pkg/cvo/image.go
pkg/cvo/render.go
pkg/cvo/updatepayload.go

Add render subcommand for CVO

---

Dockerfile
pkg/cvo/render.go
pkg/cvo/updatepayload.go

CVO loads `manifests` dir for manifests that define CVO.
CVO loads `release-manifests` dir for manifests that release-image contains.
CVO still keeps the order `cvo manifests` > `release-image` manifests
/cc @smarterclayton

Drop CVO from release manifests

---

docs/dev/operators.md

New document/guide in the form of a detailed FAQ for operator authors wanting to integrate their operators with the cluster payload generated by CVO.
Excerpted from internal documentation.

docs/dev: Second level operator FAQ

---

pkg/cvo/internal/generic.go

genric_handler: error when object has no name

---

install/0000_00_cluster-version-operator_03_daemonset.yaml

This change switches the CVO to be installed as a daemonset instead of a deployment so that it can temporarily bypass the scheduling problem it faces as a deployment.  This allows us to 
1. avoid having the static pod which cannot be managed via `kubectl` 
2. ensures that a CVO rollout to a new image doesn't get backleveled by a static pod
3. ensures that the CVO is automatically balanced on new masters so that should one kube-apiserver go down, you don't lose all three CVO pods (deployments don't do this)
If we later want to switch back to deployments we can, but this change eliminates an unnecessary static pod and places the CVO at the right logical point in the installation flow.
/assign @abhinavdahiya 
@ironcladlou @smarterclayton @mfojtik

switch workload resource to daemonset

---

install/0000_00_cluster-version-operator_01_clusterversion.crd.yaml

Create the new API definition for CRD so installer can start creating
the new object. Extracted from PR #45, no changes.

api: Add stub ClusterVersion CRD so that installer can reference it

---

Gopkg.lock
docs/dev/metrics.md
lib/resourceapply/cv.go
lib/resourcemerge/os.go
pkg/autoupdate/autoupdate.go
pkg/cvo/cvo.go
pkg/cvo/cvo_test.go
pkg/cvo/internal/dynamicclient/client.go
pkg/cvo/metrics.go
pkg/cvo/metrics_test.go
pkg/cvo/status.go
pkg/cvo/sync.go
pkg/cvo/updatepayload.go
vendor/github.com/pkg/errors/LICENSE
vendor/github.com/pkg/errors/errors.go
vendor/github.com/pkg/errors/stack.go

Reporting sync errors to the user via the ClusterVersion status is important for usability - this will be the first place user interfaces check when errors occur. Improve the exit paths from the core payload sync path to capture errors.
```
$ oc get clusterversion
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE     STATUS
version   4.0.2     False       True          56m       Unable to apply 4.0.3: a required extension is not available to update
```
```
Status:
Available Updates:  <nil>
Conditions:
Last Transition Time:  2018-11-05T02:01:24Z
Status:                False
Type:                  Available
Last Transition Time:  2018-11-05T02:01:24Z
Message:               Unable to apply 4.0.3: a required extension is not available to update
Reason: …
```

cvo: Report errors to conditions more consistently

---

install/0001_00_cluster-version-operator_03_service.yaml

A service is required for the cluster monitoring operator to scrape a target
with prometheus. Create the service and define a metrics port.

manifests: Add a service for CVO so that a ServiceMonitor can scrape it

---

install/0000_00_cluster-version-operator_03_deployment.yaml

Reverts openshift/cluster-version-operator#35
In the 4.0 release, we want a deployment.  There is a suspect scheduling bug that must be resolved to switch back: https://bugzilla.redhat.com/show_bug.cgi?id=1638132 .
We made the change so we could remove a static pod that we don't want long term and ensure that bootstrapping sequence doesn't end up with accidental dependencies because of that.  
/hold
hold until the bug is fixed.
/assign @sjenning 
@sjenning I'm not sure who will be driving this change back in, but it's a thing we'll need to fix in 4.0 to avoid management issues related to a daemonset operator.
@abhinavdahiya fyi

Revert "switch workload resource to daemonset"

---

cmd/start.go
install/0001_00_cluster-version-operator_03_service.yaml

OpenShift opens 9000-9999 for internal host network use for services that
must be scraped like node-exporter but must also be on host network, and
which may be on the master. Move CVO to listen on 9101 so that prometheus
can scrape it to get cluster version metrics.

metrics: Move default metrics port to 9101 in the open internal range

---

cmd/start.go
install/0001_00_cluster-version-operator_03_service.yaml

Change to 9099, I will create a document in openshift/origin to track
claimed ports.

metrics: Default metrics port conflicts with node-exporter

---

install/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml

Knowing if the operator is failing is critical for determining health of the cluster
so we should show it by default
/assign @abhinavdahiya

manifest: show the Failing condition in a column

---

lib/resourcebuilder/errors.go
pkg/cvo/internal/operatorstatus.go
pkg/cvo/sync.go
pkg/cvo/sync_test.go

* Add RetryLaterError to reasons for sync task requeue
* clusteroperator is not present on installation and requeuing when not found allows progress on installation with sync only finishing when all clusteroperators are available.

Requeue clusteroperator on NotFound

---

docs/dev/clusterversion.md

To help devs to test one-off object changes.
Builds on #59; review that first.
CC @abhinavdahiya, @runcom

docs/dev/operators: Document ComponentOverride injection

---

install/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml

This removes the old operator status object as it is no longer set
and the cluster scoped ClusterOperator is being leveraged for 4.0.

api: Remove operatorstatus object before 4.0

---

docs/dev/operators.md

The checkpointer is gone and the cluster-config-operator needs an early runlevel
/assign @smarterclayton @abhinavdahiya

docs: cluster-config-operator needs runlevel

---

docs/dev/metrics.md
pkg/cvo/cvo.go

The production Cincinnati stack is going to run at the given URL. Once
it has been turned up, CVO will be able to automatically check for
updates.
cc @smarterclayton @steveej @jhernand
Hold while we wait for confirmation about that URL...
/hold

*: update default upstream URL

---

pkg/cincinnati/cincinnati.go

This aligns client-accepted media type to cincinnati spec.
Ref: https://github.com/openshift/cincinnati/blob/06c9ce64367b55f453295b2765a9aab61791dc76/docs/design/cincinnati.md#request

pkg/cincinnati: fix media-type

---

Gopkg.lock
README.md
cmd/start.go
hack/test-integration.sh
hack/test-prerequisites.go
pkg/cvo/cvo.go
pkg/cvo/cvo_integration_test.go
pkg/cvo/cvo_scenarios_test.go
pkg/cvo/cvo_test.go
pkg/cvo/internal/generic.go
pkg/cvo/status.go
pkg/cvo/sync.go
pkg/cvo/sync_test.go
pkg/cvo/sync_worker.go
pkg/cvo/sync_worker_test.go
pkg/cvo/updatepayload.go
vendor/k8s.io/client-go/dynamic/fake/simple.go

Implement #77
* Refactor payload syncing into its own loop, and the main loop tells it what to do and gathers status on where it is
* Take subtle behavior of syncing and put it into the worker, not the sync loop (retries, timeouts, remembering status)
* Writing CV status is much simpler and is based only on inputs (what the sync loop is doing + available updates + validation errors)
* Add integration and more extensive core testing

sync: Do config syncing in the background

---

cmd/main.go
cmd/render.go
cmd/start.go
pkg/autoupdate/autoupdate.go
pkg/cvo/cvo.go
pkg/cvo/cvo_test.go
pkg/cvo/sync.go
pkg/cvo/sync_test.go
pkg/start/start.go
pkg/start/start_integration_test.go

On an upgrade the CVO is always restarted but we don't release our
lease, which causes the new CVO pod to have to wait. We should
release our lease on exit.
Kube 1.14 (pr 71490) contains a new flag on leader lease that allows
the caller to step down gracefully. Because backporting that change
to client-go is complicated, we instead emulate the logic. When that
code is available we can simplify down.
This also makes install about 90s faster

cvo: Release our leader lease when we are gracefully terminated

---

lib/resourcebuilder/apiext.go
lib/resourcebuilder/apps.go
lib/resourcebuilder/batch.go
lib/resourcebuilder/core.go
lib/resourcebuilder/helper.go
lib/resourcebuilder/rbac.go
lib/resourcebuilder/security.go
pkg/cvo/cvo.go
pkg/start/start.go

For the kube apis, protobuf is more efficient on both client and server
side which reduces the base load of the cluster. We can't set protobuf for
custom resource clients or unstructured at the current time.
We are getting a fair amount of throttling during deployment and updates.
Increase QPS and Burst to be 4x the default. Refactor the start client
slightly to allow modifying the client in case we need to do this in the
future.

Increase the QPS limits on clients slightly and use protobuf for sync

---

pkg/cvo/cvo.go

We don't actually react to cluster operator objects today. We can
safely ignore this edge since we already wait inside sync loop.

cvo: Don't wake the CVO on a cluster operator change

---

docs/dev/clusteroperator.md

This wasn't quite clear enough in the docs. I had to have a discussion with @abhinavdahiya to understand whose responsibility it was to create the object.

docs: Add obligation to create ClusterOperator

---

docs/dev/clusteroperator.md

Everyone needs a clusteroperator so cluster-admins know the state of their cluster and so that the CVO can be sure that upgrades are successful before trying to apply the next payload.
/assign @smarterclayton @eparis

make it clear that everyone needs a clusteroperator

---

install/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml

This seems like a natural shortname for a resource that I type very often.
/assign @smarterclayton @abhinavdahiya

add 'co' as shortname for clusteroperators

---

docs/dev/metrics.md
pkg/cvo/cvo.go
pkg/cvo/metrics.go
pkg/cvo/metrics_test.go

One attack vector for clusters is to deny access to new updates or
to deliberately send an older update with vulnerabilities. This commit ensures the date the
payload was created is reported back through metrics and up via
telemetry. It also adds a new `completed` type for the cluster_version
metric that reports the last successfully applied cluster version and
the date it was successfully applied the first time (from the new
status history field). Finally, we correct the naming for the update
type to match the name of the status field to `desired`.

metrics: Report the age of the current payload for alerting

---

docs/dev/metrics.md
pkg/cvo/metrics.go
pkg/cvo/metrics_test.go

Building on feedback from the first round, report `cluster_version`
for each type as seconds since the epoch. The value allows relevant
data to be extracted such as the age of the cluster, the age of the
current payload, when the most recent successful update was applied,
and when the most recent failure started occurring.
Example queries:
sort(cluster_version{type="cluster"})
sort_desc(cluster_version{type="completed"})
topk(20, cluster_version{type="failure"})
sort(cluster_version{type="current"})

metrics: Report cluster_version as seconds since the epoch per type

---

pkg/autoupdate/autoupdate.go
pkg/cvo/cvo.go
pkg/cvo/cvo_test.go
pkg/cvo/metrics.go
pkg/cvo/metrics_test.go

Cluster operators may "flap" - have conditions that periodically
move from true to false (or appear and disappear). The CVO can record
all transitions as they occur and report it to prometheus, allowing
us to get fine grained reports of transitions. Since most operators
should be stable, treat Unknown -> False and <missing> -> Unknown
as just as valid, on the assumption that transitions are important.
Will allow us to identify flapping operators and fix them.

metrics: Report a gauge for when cluster operator conditions change

---

pkg/cvo/cvo_test.go
pkg/cvo/status.go

During both initial cluster init and upgrade it is valuable to show
the user how far we have gotten. Use the fraction reported by status
to show an approximate percentage of our progress through the payload.
During reconcilation, we show nothing.

status: Report a percentage when performing the initial sync

---

pkg/cvo/availableupdates.go
pkg/cvo/cvo.go
pkg/cvo/cvo_test.go
pkg/cvo/status.go
pkg/start/start_integration_test.go

When a payload is retrieved the version may be empty, and if the
status is updated it'll have an empty version. This caused an
integration flake.
Since retrieving the payload can take a certain amount of time,
reflect that in the progressing message and give a unique reason.
The test should then verify the state.

test: Fix flake when retrieving payloads

---

pkg/cvo/cvo.go
pkg/cvo/cvo_scenarios_test.go
pkg/cvo/cvo_test.go
pkg/cvo/sync_test.go
pkg/cvo/sync_worker.go
pkg/payload/task_graph.go
pkg/payload/task_graph_test.go
pkg/start/start.go

Parallelize payload execution using two simple rules:
1. a Job in the payload acts as a serialization barrier (all previous work must complete)
2. two manifests can be run in parallel if:
a. The name of the manifest matches `0000_<NUMBER>_<COMPONENT>_*`
b. The number matches
c. The component does not match
We'd build a graph, then greedily execute sync tasks, starting a node when all prerequisites are satisfied.  We never run manifests in parallel under the same `0000_<NUMBER>_<COMPONENT>` prefix.
The first few rules cut us to about ~120 sequential tasks, instead of 227.

Parallelize the payload execution

---

pkg/cvo/cvo_scenarios_test.go
pkg/cvo/internal/operatorstatus.go
pkg/cvo/status.go
pkg/payload/task.go
pkg/start/start_integration_test.go

Cluster operators block most of upgrade, so we should report the information the cluster operator has available back to the CV status object via an UpdateError.
Reduce the amount of debug info printed by cluster operator status waiting to simplify the logs.
While reviewing CV logs from startup, we run the resync loop more frequently waiting for the CO to be created because we exit the poll loop on any error. When we see "CO not found", continue the loop to avoid triggering the top level sync worker backoff loop.  Shaves a few tens of seconds of startup time.
Finally, remove the apiVersion info from the status log message, it didn't make much sense and the end user is going to have to look at the payload anyway if we get into a wierd error case where it matters (the apiVersion was put in …

sync: Report a specific cluster operator error when not available

---

pkg/cincinnati/cincinnati.go
pkg/cincinnati/cincinnati_test.go
pkg/cvo/cvo_test.go

currently if the current version does not exist in the reponse returned from cincinnati, we use the `0`th node as our version
and return the available updates for that version.
example,
If the response from cincinnati is following:
```console
$ curl --silent --header 'Accept:application/json' https://api.openshift.com/api/upgrades_info/v1/graph | jq .
{
"nodes": [
{
"version": "4.0.0-5",
"payload": "quay.io/openshift-release-dev/ocp-release:4.0.0-5",
"metadata": {}
},
{
"version": "4.0.0-4",
"payload": "quay.io/openshift-release-dev/ocp-release:4.0.0-4",
"metadata": {}
},
{
"version": "4.0.0-6",
"payload": "quay.io/openshift-release-dev/ocp-release:4.0.0-6",
"metadata": {}
},
{
"version": "4.0.0-7",
"payload": "quay.io/openshift-release-dev/ocp-release:4.0.0-7",
"metadata": {}
},
{ …
```

cininnati: fix unknown version fetch

---

lib/resourcemerge/os.go

The relatedObjects reported in status is used by must-gather tool to help get diagnostic information about an operator.  Missing from the existing library that handles cluster operator status.

lib: ensureClusterOperatorStatus tracks RelatedObjects

---

docs/dev/operators.md

Also document that ordering depends on proper ClusterOperator implementation
and components should transition to utilizing direct dependencies.

docs: Update CVO doc for run level and parallelization

---

docs/dev/operators.md

Catching up with openshift/cluster-openshift-apiserver-operator#121, openshift/machine-config-operator#331, and operator-framework/operator-lifecycle-manager#678.  I'm not personally clear on the reasoning; I'd have expected the OLM entries to belong at the end of the queue, since they seem less central than the OpenShift core operators.
The Machine API and autoapprover entries had been added to the end of the queue in dcab5e4c (#64), but I don't see any discussion of that placement there.
I'd also understood the `0000_` prefix to be a special case for where ordering is critical, with most operators landing without specific ordering after the key components had been addressed.  I dunno how that squares with:
```console
$ oc adm release extract …
```

docs/dev/operators: Reorder assigned runlevels (machine API to 30, etc.)

---

pkg/cincinnati/cincinnati.go
pkg/cincinnati/cincinnati_test.go
pkg/cvo/cvo_test.go

Based on [cincinnati graph api Response][1] the fields for a node must be `version`, `image` and `metadata`. But response from current api:
```console
$ curl --silent --header 'Accept:application/json' https://api.openshift.com/api/upgrades_info/v1/graph | jq .
{
"nodes": [
{
"version": "4.0.0-5",
"payload": "quay.io/openshift-release-dev/ocp-release:4.0.0-5",
"metadata": {}
},
{
"version": "4.0.0-4",
"payload": "quay.io/openshift-release-dev/ocp-release:4.0.0-4",
"metadata": {}
},
{
"version": "4.0.0-6",
"payload": "quay.io/openshift-release-dev/ocp-release:4.0.0-6",
"metadata": {}
},
{
"version": "4.0.0-7",
"payload": "quay.io/openshift-release-dev/ocp-release:4.0.0-7",
"metadata": {}
},
{
"version": "4.0.0-8",
"payload": "quay.io/openshift-release-dev/ocp-release:4.0.0-8",
"metadata": …
```

pkg/cincinnati: update unamrshal to node to match the result from cincinnati

---

hack/build-go.sh
hack/build-image.sh
hack/push-image.sh

Similar to https://github.com/openshift/machine-config-operator/pull/191.
Turns out `registry.svc.ci.openshift.org/openshift/release:golang-1.10` has `VERSION` env set to golang's version.
So switching to `VERSION_OVERRIDE` prevents conflicts.
/cc @crawford

hack: change override env for version

---

pkg/cvo/internal/operatorstatus.go

As operators begin waiting for versions, we no longer need to wait for progressing status before continuing to the payload as long as we aren't failing or available. For operators not yet setting versions, continue to wait for progressing.
Allowing this will allow the core operators to complete faster even if they are restarting to process config changes.  This may cause other operators to be flaky, but that's ok because they need to tolerate those anyway, or the kube-apiserver needs to be better at mitigating, or likely, both.
@derekwaynecarr @abhinavdahiya @bparees as per discussion today as we were switching image-registry operator over.  There's no reason to hold for progressing once an operator has told us it's available at the version we requested.  Will allow kube-apiserver to …

clusteroperator: Skip waiting for progressing when versions expected

---

install/0000_00_cluster-version-operator_03_deployment.yaml

specifies system-cluster-critical priority for operator.
blocks passing smoke tests for ensuring control plane pods always schedule.
see: https://github.com/openshift/origin/pull/22217

manifests: operator should have cluster-critical-priority

---

install/0000_00_cluster-version-operator_03_deployment.yaml

If the registry goes down, we want to continue to be able to run new replicas
of this image over time.
This matches other operators and our general guidance
/assign @abhinavdahiya

manifest: switch pull policy to ifnotpresent

---

lib/resourcebuilder/apiext.go
lib/resourcebuilder/apireg.go
lib/resourcebuilder/apps.go
lib/resourcebuilder/batch.go
lib/resourcebuilder/core.go
lib/resourcebuilder/interface.go
lib/resourcebuilder/rbac.go
lib/resourcebuilder/security.go
pkg/cvo/cvo.go
pkg/cvo/cvo_scenarios_test.go
pkg/cvo/internal/generic.go
pkg/cvo/internal/operatorstatus.go
pkg/cvo/internal/operatorstatus_test.go
pkg/cvo/sync_test.go
pkg/cvo/sync_worker.go
pkg/payload/task.go

all resourcebuilders must respect the context when doing work. This allows slow resource builders to
cancel their task mid-way.
/cc @smarterclayton

lib/resourcebuilder: update interface to include context when doing work

---

pkg/cvo/cvo.go

The 0000_70 run level has ~13 operators. It appears we can afford
to go a bit broader (although the ideal solution is to pause a task
group when we hit a CO, flush out the others, then wait).
A subsequent change will alter how the rate limiter works so that we
can be a little slower during reconcile but faster during initial install.
Extracted from #134

sync: Double max parallelism of sync worker

---

pkg/cvo/cvo.go
pkg/cvo/internal/operatorstatus.go
pkg/cvo/internal/operatorstatus_test.go
pkg/cvo/sync_test.go
pkg/start/start_integration_test.go

Reduces the amount of API calls we make significantly when polling,
which reduces load on API server and also doesn't consume as much of
our client rate limit.
This does not impact correctness because we're level driven for
continuity and a subsequent sync loop will already handle this.
Extracted from #131

sync: Serve cluster operator gets from the cache lister

---

lib/resourcebuilder/apiext.go
lib/resourcebuilder/apireg.go
lib/resourcebuilder/apps.go
lib/resourcebuilder/batch.go
lib/resourcebuilder/core.go
lib/resourcebuilder/interface.go
lib/resourcebuilder/rbac.go
lib/resourcebuilder/security.go
pkg/cvo/cvo.go
pkg/cvo/cvo_scenarios_test.go
pkg/cvo/internal/generic.go
pkg/cvo/internal/operatorstatus.go
pkg/cvo/internal/operatorstatus_test.go
pkg/cvo/status.go
pkg/cvo/status_test.go
pkg/cvo/sync_test.go
pkg/cvo/sync_worker.go
pkg/payload/payload.go
pkg/payload/task.go

Identify what sort of change we are making to the cluster in order
to better handle the different states. Does not change status reporting
or the internal sync which will be in a follow up commit.
The three states are:
* Initializing - we haven't yet completed a payload
* Updating - we're moving between two payloads of different versions
* Reconciling - we're level on a completed payload
The states will allow us to more efficiently reconcile, start faster,
and be safer during upgrades.
Extracted from #131

sync: Distinguish between reconcile, initial, and sync states

---

install/0000_00_cluster-version-operator_03_deployment.yaml

Address [rhbz#1670727][1]:
```
F0129 08:54:04.971868       1 start.go:144] Unable to start metrics server: listen tcp 0.0.0.0:9099: bind: address already in use
```
when the new CVO pod is scheduled on the same node as the old one.  From [the Kubernetes docs][2] the default strategy (which we override with this commit) was `RollingUpdate`.  The `Recreate` strategy avoids the port conflict [because][3]:
> All existing Pods are killed before new ones are created when `.spec.strategy.type==Recreate`.
That leaves a (hopefully brief) window when there is no CVO pod, but since our only API is serving those metrics, that's probably not a big deal.  The new pod should be able to pick up reconciling ClusterVersion changes when it comes up, even if changes were made during the no-CVO-pod gap.
CC …

Bug 1670727: install/0000_00_cluster-version-operator_03_deployment: Set 'strategy: Recreate'

---

pkg/start/start_integration_test.go

While testing in tight loops I was able to trigger collisions and
timeout errors.
https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/141/pull-ci-openshift-cluster-version-operator-master-integration/198
```
start_integration_test.go:549: timed out waiting for the condition
start_integration_test.go:476: failed to delete cluster version e2e-cvo-fqgh: clusterversions.config.openshift.io "e2e-cvo-fqgh" not found
```

test: Avoid collisions on namespace and lengthen shutdown timeout

---

Makefile
lib/resourcebuilder/apiext.go
lib/resourcebuilder/apps.go
lib/resourcebuilder/batch.go
lib/resourcebuilder/interface.go
pkg/cvo/cvo.go
pkg/cvo/cvo_scenarios_test.go
pkg/cvo/internal/operatorstatus.go
pkg/cvo/sync_test.go
pkg/cvo/sync_worker.go
pkg/cvo/updatepayload.go
pkg/payload/task.go
pkg/start/start.go
pkg/start/start_integration_test.go

The sync loop currently mixes a combination of:
1. Try forever (top level sync loop) 
2. Cancel sync when a timeout is reached 
3. Retry individual Apply actions in the sync workers up to a max
retry 
4. Retry within Apply actions
This led to bugs in initialization where transient errors cause a prereq
step to fail and never complete, leading to other operators never going
live.
This commit simplifies the structure of our retry logic to be:
1. Try to sync forever 
2. Cancel sync after a certain period of failure and go into backoff 
3. Retry individual Applies forever with capped backoff 
4. Retry applies as long as context is not cancelled
This implies all top level sync has a context with a deadline which is the
case today - some test cases are changed for it.
This should also reduce …

Bug 1691513: CVO should retry initialization until cancelled to avoid wedging because of failing dependencies

---

pkg/cvo/cvo_test.go
pkg/cvo/status.go
pkg/cvo/status_test.go

When we refactored to the newer status style syncFailingStatus was
left updating the cached map, which can cause corruption of the
in memory state.
Also, we shouldn't add an entry to the history when images are equal but the new version is empty because we can get into that state if the CVO is rescheduled onto another node during an upgrade - while it's loading the payload the version will be empty.  We only add an entry if the version is set and has changed (indicating possibly that the tagged image changed).

status: Correctly increment history and don't overwrite controller cache objects

---

Dockerfile.rhel7

Remove hardcoded 'amd64' from Dockerfile to support multi-arch builds.

Remove hardcoded 'amd64' from Dockerfile to support multi-arch builds.

---

pkg/cvo/sync_worker.go

from https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade-4.0/735/artifacts/e2e-aws-upgrade/pods/openshift-cluster-version_cluster-version-operator-6d45bb77db-sv7h9_cluster-version-operator.log.gz
```
...
I0329 12:54:45.471460       1 task_graph.go:538] Canceled worker 222
I0329 12:54:45.471444       1 task_graph.go:538] Canceled worker 265
I0329 12:54:45.471468       1 task_graph.go:538] Canceled worker 221
I0329 12:54:45.471476       1 task_graph.go:538] Canceled worker 220
I0329 12:54:45.471475       1 task_graph.go:538] Canceled worker 218
I0329 12:54:45.471483       1 task_graph.go:538] Canceled worker 202
...
I0329 12:54:45.471551       1 task_graph.go:538] Canceled worker 238
I0329 12:54:45.471552       1 task_graph.go:538] Canceled …
```

cvo: fix max_workers to number of nodes in graph

---

install/0000_00_cluster-version-operator_03_deployment.yaml

I'd added this in 078686d73b (#140), but apparently [got the wrong place][1]:
```console
$ curl -s https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-4.0/6412/artifacts/e2e-aws/deployments.json.gz | gunzip | jq '.items[] | select(.metadata.name == "cluster-version-operator").spec.strategy'
{
"rollingUpdate": {
"maxSurge": "25%",
"maxUnavailable": "25%"
},
"type": "RollingUpdate"
}
```
I'm not actually sure how I arrived at the previous position.  Anyway, hopefully this commit puts the setting in the right place.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1670727#c14

Bug 1670727: install/0000_00_cluster-version-operator_03_deployment: Fix Recreate strategy

---

docs/dev/metrics.md
pkg/cvo/metrics.go
pkg/cvo/metrics_test.go

The current metric for 'desired' cluster_version reports the user's
input. However this metric doesn't discriminate between an invalid
update (where nothing will be happening) and when the operator is
attempting to converge, nor does it report the version number we
read from the release image.
Add a new 'updating' cluster_version type that is returned if and
only if the most recent history entry is in the Partial update state
(i.e., not reconciling), which covers both upgrade and rollback. The
image and version are reported from the history and should be
accurate to the payload's internal version. The value is the start
time in unix seconds of this current version and is a good proxy for
"how long have we been trying to upgrade".
Identified by the analysis team because 'desired' is …

metrics: Report when the CVO is transitioning a payload

---

lib/resourcemerge/os.go

This commit ensures whenever there are differences between
existing and new status, we update the transition time with
current time.

SetOperatorStatusCondition update transition time for existing

---

docs/dev/clusteroperator.md

We want the possessive her, not the "it is" contraction.

docs/dev/clusteroperator: Fix "it's" -> "its" typo

---

lib/resourceapply/apiext.go
lib/resourceapply/apireg.go
lib/resourceapply/apps.go
lib/resourceapply/batch.go
lib/resourceapply/core.go
lib/resourceapply/cv.go
lib/resourceapply/interface.go
lib/resourceapply/rbac.go
lib/resourceapply/security.go
pkg/cvo/internal/generic.go
pkg/cvo/internal/generic_test.go

If a resource to apply specifies this annotation it is created if missing,
but it is never updated.  We want to use this for empty config.openshift.io
and operator.openshift.io resources, but support is uniform.
@smarterclayton I think the name matches our discussion.
/assign @abhinavdahiya

resource-apply: add release.openshift.io/create-only annotation

---

pkg/cvo/cvo_scenarios_test.go
pkg/cvo/status.go
pkg/cvo/sync_worker.go
pkg/cvo/sync_worker_test.go
pkg/cvo/testdata/paralleltest/release-manifests/0000_10_a_file.yaml
pkg/cvo/testdata/paralleltest/release-manifests/0000_20_a_file.yaml
pkg/cvo/testdata/paralleltest/release-manifests/0000_20_b_file.yaml
pkg/cvo/testdata/paralleltest/release-manifests/image-references
pkg/payload/task.go
pkg/payload/task_graph.go
pkg/payload/task_graph_test.go

The current single error return strategy from the CVO sync loop predates
parallel payload execution and limited retries. Instead, collect all
errors from the task execution graph and attempt to synthesize better
messages that describe what is actually happening.
1. Filter out cancellation error messages - they aren't useful and are
a normal part of execution
2. When multiple errors are reported, display a reasonable multi-line
error that summarizes any blockers
3. Treat ClusterOperatorNotAvailable as a special case - if all errors
reported are of that type convert it to ClusterOperatorsNotAvailable
and synthesize a better message
4. In the sync loop, if we are still making progress towards the update
goal and we haven't waited too long for an update, and if the error
is the specific …

status: Report the operators that have not yet deployed

---

pkg/cvo/sync_worker.go
pkg/payload/task_graph.go

The worst outcome of reconcile would be that a break occurs in a late component and the CVO gets hung trying to reach it to correct the issue (i.e. 0000_30 is broken due to a change in 0000_70).  Because we process in order we never get to 70 and fix it.  The other issue is that a medium to long term break in 30 can prevent entropy repair at 70, so 70 degrades until 30 recovers.
Instead of running the reconcile graph in order, run it in random blocks at a lower parallelization factor to ensure that we will eventually try all blocks, even if something fundamental is broken. The permutation of the graph ordering is stable for a given payload and sync time (so that when we test locally we are testing the same order a customer we would see).
The only gap still left would be a component breaks …

sync: During reconcile, try different parts of the payload and don't hang

---

pkg/cvo/availableupdates.go
pkg/cvo/cvo_test.go

Checking for an empty channel locally prevents unnecessary calls to the
upstream update server.
Partially fixes https://bugzilla.redhat.com/show_bug.cgi?id=1679901.

Ensure channel isn't empty on update check

---

install/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml

[Fix][1]:
```console
$ oc get clusteroperators kube-apiserver
NAME             VERSION                             AVAILABLE   PROGRESSING   FAILING   SINCE
kube-apiserver   4.1.0-0.nightly-2019-04-22-005054   True        False                   20m
```
when the ClusterOperator only sets `Degraded`.  This should have happened in 94c4e576d1 (#165).
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1702087

Bug 1702087: install/0000_00_cluster-version-operator_01_clusteroperator.crd: Failing -> Degraded

---

pkg/cvo/cvo.go
pkg/start/start.go
pkg/start/start_integration_test.go

Avoid the possibility of a bad release image being created that can't
correctly read the payload by failing hard on startup if the payload is
invalid.

start: Initialize the payload and fail if it can't be read at startup

---

pkg/cincinnati/cincinnati.go
pkg/cincinnati/cincinnati_test.go

Maybe having the current version not in the desired channel's graph is a problem, but maybe you know what you're doing.  And Cincinnati might *know* about your version, and just consider it to be outside your
channel, in which case the solution may be "switch channels" and not "switch versions".  This change hopefully makes it a bit easier for an admin in this condition to figure out the appropriate next step for their cluster.
CC @smarterclayton, @steveeJ

pkg/cincinnati: Soften unknown-version message

---

pkg/payload/task_graph_test.go

This caused flakes because we weren't checking against the deterministic
list like we should have been.

test: Fix flake in RunGraph, comparing the wrong list (errs vs messages)

---

pkg/cvo/status.go

A future change will perform selective pruning and preserve the initial
version of the code.
@wking to get us out the door, as discussed.

Preserve up to 50 version history entries

---

install/0000_00_cluster-version-operator_00_namespace.yaml

**Why this change?**
When https://github.com/openshift/cluster-kube-apiserver-operator/pull/394 merges, all the pods running openshift cluster will have a [defaultNodeSelector](https://docs.openshift.com/container-platform/3.11/admin_guide/managing_projects.html#setting-the-cluster-wide-default-node-selector) if it has been set by cluster-admin including pods running in `openshift-*` namespace. The main advantage of having that feature is in a multi-tenant environment, any new project created can be steered towards compute nodes(non-master nodes).
**What should I do?**
If you think, the pods in your namespace shouldn't have defaultNodeSelector set, please review this PR. If not feel free to close this. The annotation added as part of this PR lets all the pods created within your project …

Add node-selector annotation to namespace

---

pkg/cvo/cvo.go
pkg/start/start.go
pkg/start/start_integration_test.go

When we upgrade the CVO causes itself to reboot by updating the
deployment. The CVO gets signalled with SIGTERM and then releases
the leader lease. However, there is no guarantee the latest status
of the CVO has been flushed to the cluster version object which
can mean the "verified: true" flag that the sync worker calculates
when it retrieves the payload doesn't get written. The new CVO pod
loads from the payload and so doesn't have the verified flag.
While in the future we may want to completely decouple verification
from payload retrieval (background worker that verifies available
updates as well as checks historical records), for now we need to
ensure the loaded state is persisted to the CV. Since there may be
useful human information available about the payload that a failed
new CVO …

cvo: Verified true boolean not written to cv.status.history during update

---

lib/resourcebuilder/apiext.go
lib/resourcebuilder/apps.go
lib/resourcebuilder/batch.go
pkg/autoupdate/autoupdate.go
pkg/cincinnati/cincinnati_test.go
pkg/cvo/availableupdates.go
pkg/cvo/cvo.go
pkg/cvo/cvo_test.go
pkg/cvo/status.go
pkg/cvo/sync_worker.go
pkg/cvo/updatepayload.go
pkg/payload/payload.go
pkg/payload/task_graph.go
pkg/start/start.go
pkg/verify/verify.go

The glog wrapper of klog has a fatal flaw - it doesn't print the
correct line number of a message. This makes debugging almost impossible
in high level debug.
Fix this by using the method directly.

Bug 1706202: Use klog directly or no line info is printed

---

install/0000_00_cluster-version-operator_03_deployment.yaml

In 4.1, we have taint-based evictions enabled. This changes logic in the node lifecycle controller in the kube-controller-manager significantly.
Historically, the node lifecycle controller would directly evict pods from node that had a Ready condition of False or Unknown after a pod eviction timeout set by the --pod-eviction-timeout flag on the kube-controller-manager. This setting applied to all pods cluster-wide. The default was 5m.
With taint-based evictions, all the node lifecycle controller does is taint the node with node.kubernetes.io/unreachable and/or node.kubernetes.io/not-ready taint with NoExecute effect. This would normally result in the immediate eviction of all pods that don't tolerate those taints, breaking the old behavior with pod eviction timeouts. Enter …

Fix tolerations

---

docs/dev/clusterversion.md

Now that we have no default overrides, the version-patch has to add the
overrides field.  According to patch docs (that I found http://jsonpatch.com/#add) the Add Op
1) If the path includes an array index, the new value is added to the entity at the specified index
2) If the path doesn't exist, a new member is created
3) If the path does exist, the value is replaced
~This worked for me~ Nope a second add squashed my first... 
Now that I've opened, I'm holding until I fix that ^^

Update version-patch.yaml in clusterversion.md

---

install/0000_00_cluster-version-operator_01_clusterversion.crd.yaml

Use history instead of desired version in the custom columns, since desired state can be set to empty when a user provides invalid input.  The first "Completed" entry in history is our "current" version - if
one doesn't exist, we have "no version".
Reproducer:
1. `oc adm upgrade --to-image=X` (triggering signature verification error)
2. `oc get clusterversion` has an empty VERSION column

ClusterVersion version column should be last completed

---

pkg/cvo/internal/operatorstatus.go
pkg/cvo/internal/operatorstatus_test.go

In practice, the output of displaying version operands is redundant and our current use doesn't require it. Since the core output is
"we are going to X, these are the things not there yet"
also showing
"we are going to X, these are the things not there yet A-X,B-X,C-X"
makes it harder to understand what is going on.
Strip all sub version reporting from cluster operators, and in the future we can improve this if we have a use case.
---
Encountered while debugging failure output in upgrades - the key messages are always the actual Degraded conditition, and the extra versions are always variants of the operator version.
https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/1724/
```
Multiple errors are preventing progress:
* …
```

status: Simplify operator not available status

---

docs/dev/metrics.md
pkg/cvo/cvo_scenarios_test.go
pkg/cvo/cvo_test.go
pkg/cvo/metrics.go
pkg/cvo/metrics_test.go
pkg/cvo/status.go
pkg/cvo/status_test.go
pkg/start/start_integration_test.go

This needs to be moved back into openshift/api since it is now part
of our public API, but for now ensure it is consistently used.

conditions: Use a consistent constant for the Failing condition

---

pkg/cvo/sync_worker.go

When upgrading and a sync loop exits, we often see:
* Operator A not upgraded yet
* Operator B not upgraded yet
* Operator C not upgraded yet
* Some more specific error
* Operator D not upgraded yet
Since the not available messages carry little value and are expected
when we are processing parallel output, if we have one or more errors
during sync that are not the generic error, only report those. This
focuses the user's attention on the actual problem, rather than
distracting them with noise. In the ideal case, the user immediately
sees "router is totally broken" vs "a, b, c, d, e, router is broken, f".
E.g. https://openshift-gce-devel.appspot.com/build/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/1724/
```
Multiple errors are preventing progress:
* Cluster …
```

status: Hide generic operator status in favor of more specific errors

---

docs/dev/metrics.md
pkg/cvo/metrics.go
pkg/cvo/metrics_test.go

Conditions are read by telemetry and the reason incentivizes teams
to have good reasons on their operators. Should not increase
cardinality significantly, but instead provide better insight.
/cherry-pick release-4.1

Bug 1717619: metrics: Report reason as a label on the conditions metric

---

lib/resourcemerge/core.go
lib/resourcemerge/core_test.go

Don't set `modified` if both `*existing` and `required` are `nil`.  Also add unit tests which cover this indirectly.

lib/resourcemerge/core: Fix setInt32Ptr for "both nil" case

---

docs/dev/metrics.md
pkg/cvo/metrics.go
pkg/cvo/metrics_test.go

The cluster_version completed type was inconsistent with other types in that it was always included but the version label was unset when no completed update had been applied. Instead, only include the series when a completed update has been applied.
Discovered while building dashboards for metrics - the `completed` and `updating` metrics are similar in usage (tell me when updating, tell me when completed) and so this makes them consistent.

metrics: Omit `cluster_version{type="completed"}` when not available

---

docs/dev/metrics.md
pkg/cvo/metrics.go
pkg/cvo/metrics_test.go

The `updating` type is hard to join in PromQL. Instead, report a label for
each type that is the previous completed version. Also change the `cluster`
type to return the original version of the cluster (first history entry).
This answers the following questions:
"what stable version is this cluster updating from"
"what was the first version recorded for this cluster"
Intended to fix bug 1720308 in 4.1

metrics: Give all cluster_version types a `from_version` label

---

pkg/cvo/sync_worker.go

Make it easier to grep for a problem-asset in the logs.  Currently:
```console
$ curl -s --compressed https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/178/pull-ci-openshift-cluster-version-operator-master-e2e-aws-upgrade/134/artifacts/e2e-aws-upgrade/must-gather/namespaces/openshift-cluster-version/pods/cluster-version-operator-7cb5846b6b-ljbd5/cluster-version-operator/cluster-version-operator/logs/current.log | grep kube-apiserver | grep '48.*381' | head -n6
2019-06-13T14:35:28.248884894Z I0613 14:35:28.248875       1 sync_worker.go:574] Running sync for namespace "openshift-kube-apiserver-operator" (40 of 381)
2019-06-13T14:35:28.448511089Z I0613 14:35:28.448453       1 sync_worker.go:587] Done syncing for service …
```

pkg/cvo: Standardize "%d/%d" -> "%d of %d"

---

lib/resourcemerge/core.go
lib/resourcemerge/core_test.go

lib does not remove containers from existing based on `Required` while merging. 
Not sure, if this is by design or it is a bug. This PR is more for a discussion/clarification.

Bug 1710172: lib/resourcemerge: Remove containers from existing based on required

---

docs/dev/metrics.md
pkg/cvo/metrics.go
pkg/cvo/metrics_test.go

An important query is "how old are the clusters of a specific version"
and the current "cluster" query does not make this possible. In addition,
we can't get initial + current version in a single query. Split the
use case for "cluster" into "initial" and "cluster", where "initial"
is the same as "cluster" today, and "cluster" now points to the same
image and version as "current", has from_version populated, and has
the same value.

Bug 1723945: Add a metric that combines the current age of the cluster with the current version

---

lib/resourcemerge/core.go
lib/resourcemerge/core_test.go

Existing logic does fails to reset the pointer to `nil`. Fixed this by declaring pointer variable at appropriate location.
Plus modified unit tests to cover this scenario.

Fix remove containers logic

---

install/0000_90_cluster-version-operator_00_servicemonitor.yaml

Since each team should own their monitoring configuration we are removing ServiceMonitor manifests from cluster-monitoring-operator.
Related to https://github.com/openshift/cluster-monitoring-operator/pull/390
/cc @brancz @smarterclayton

install: add service monitor manifest

---

pkg/payload/render.go

the `manifests` directory on the bootstrap is used by the cluster-bootstrap to push to the cluster.
`servicemonitor` for cvo was added by https://github.com/openshift/cluster-version-operator/pull/214
`servicemonitor` api is created by the cluster-monitoring-operator and therefore this causes the bootstrapping to get stuck until we get the monitoring operator running.
This skips the `servicemonitor` in the bootstrap render as it is not required for the bootstrap cvo pod.
/cc @smarterclayton @brancz

payload/render: update the bootstrap render to skip servicemonitor

---

pkg/cincinnati/cincinnati.go
pkg/cincinnati/cincinnati_test.go
pkg/cvo/availableupdates.go
pkg/cvo/cvo.go
pkg/cvo/cvo_test.go
pkg/start/start.go

- Modified Cincinnati client to accept the http transport struct
so that a https proxy can be set
- Created new function getHTTPTransportProxy that
retrieves the proxy config, creates the transport and returns the
transport ptr.

Add http transport for cincinnati to enable proxy

---

install/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
install/0000_00_cluster-version-operator_01_clusterversion.crd.yaml

This refreshes our CRD schema with the latest copies from the 4.2
streams. Docs are regenerated from tooling in cluster-config-operator
and merged with the current definition.
1. Go to openshift/cluster-config-operator
2. Build crd-schema-gen, invoke it like `crd-schema-gen --apis-dir vendor/github.com/openshift/api/config/v1/ -output-dir manifests`
3. Copy the generated clusterversion/operator manifests over the CRDS in repo
4. Merge the schema portion only in (dropping other changes)

manifests: Update the CRD definitions with more accurate docs

---

lib/resourcebuilder/apps.go
lib/resourcebuilder/podspec.go
lib/resourcebuilder/podspec_test.go

set .metadata.annotations["config.openshift.io/inject-proxy"]="container1,initcontainer2"
to inject into specified container names

inject proxy env vars into requesting workload resources

---

pkg/cvo/availableupdates.go
pkg/cvo/cvo.go
pkg/internal/constants.go
pkg/start/start.go

follow up from https://github.com/openshift/api/pull/400
/cc @jcpowermac

pkg: switch to openshift-config for proxy CA

---

pkg/cincinnati/cincinnati.go
pkg/cincinnati/cincinnati_test.go
pkg/cvo/availableupdates.go
pkg/start/start_integration_test.go

OpenShift is going to be gaining support for architectures other than
AMD64 soon. In order to make sure that the updates provided to a cluster
are compatible with the underlying architecture(s), we are adding an
"arch" parameter to the Cincinnati upstream queries. This new parameter
will contain a set of architectures, separated by commas, that need to
be supported by a release image in order for it to be applied to the
cluster. In a homogeneous deployment, the set of architectures will only
contain a single architecture (this is what this patch implements).
Eventually, once heterogeneous deployments are supported, the set may
contain multiple architectures. The details of heterogeneous deployments
and their constraints haven't been fully fleshed out, so this scheme may
change over time.

cincinnati: add arch parameter to requests

---

install/0000_00_cluster-version-operator_00_namespace.yaml

Follow-up to #234 
Without this label prometheus-operator doesn't watch `openshift-cluster-version` namespace in search for ServiceMonitor.
/assign @abhinavdahiya 
/cc @s-urbaniak

Bug 1738527: install: enable prometheus-operator to watch over namespace in search for ServiceMonitor

---

pkg/cvo/metrics.go
pkg/cvo/metrics_test.go

This will allow us to discover upgrade and other failure reasons without having to resort to a must-gather or similar.
Stick this in `cluster_operator_conditions`, since we already have a `reason` slot there.  I don't see a reason to add a new metric to separate cluster-version operator failures from second-level operator failures; the name should be sufficient for that.

Bug 1741645: pkg/cvo/metrics: Report cluster-version conditions with reasons

---

docs/dev/metrics.md
pkg/cvo/metrics.go
pkg/cvo/metrics_test.go

We currently report failure twice. Now that we have from_version,
we can report the previous completed version.

Bug 1739988: Stop double reporting "failure" cluster_version

---

bootstrap/bootstrap-pod.yaml
cmd/start.go
install/0000_00_cluster-version-operator_03_deployment.yaml
pkg/cvo/cvo.go
pkg/cvo/cvo_scenarios_test.go
pkg/cvo/cvo_test.go
pkg/start/start.go
pkg/start/start_integration_test.go

This avoids a race between:
* The cluster-version operator pushing its internally-generated default and
* The cluster-bootstrap process pushing the installer-generated ClusterVersion into the cluster ([rhbz#1741786][1])
Because cluster-bootstrap does not override already-existing objects, when the CVO's default won that race, the cluster would come up with a bogus `channel` (`fast`, instead of the installer's default `stable-4.2`, etc.) and `clusterID` (causing the reported Telemetry to come in under a different UUID than the one the installer [provided in its `metadata.json` output][2]).
By removing the default, the CVO will continue applying the current version and reporting some metrics like `cluster_version{type="current"}`.  But it will not report metrics that depend on the state …

Bug 1741786: pkg/cvo: Drop ClusterVersion defaulting during bootstrap

---

lib/resourcemerge/core.go
lib/resourcemerge/core_test.go

- Add ensureResourceRequirements function
If existing and required are not equal will DeepCopy required
into existing.
- Update core_test to include testing container resources limits addition
and removal.

Bug 1726455: Reconcile container ResourceRequirements in resource merge

---

install/0000_90_cluster-version-operator_02_servicemonitor.yaml
pkg/cvo/metrics.go
pkg/cvo/metrics_test.go

Adds alerts for cluster-version-operator and cluster operators
* `ClusterVersionOperatorDown`
This alert is fired when cluster-version-operator is not providing any metrics. Serverity is critical as upgrades will not work and the clusters can drift from expected state.
* `ClusterOperatorDegraded`
This alert is fired when the cluster operator is degraded. This is important as the cluster might be in an unacceptable state for produciton cluster, for example, using emptyDir for storage backend for registry. Severity is critical as
degraded operator implies the operands are in a state that is not correct for the cluster.
* `ClusterOperatorDown`
This alert fires when a cluster operator is not up ie cluster_operator_up is 0. This means that the operator might not be reconcile the operands.
* …

Bug 1717632: install: add alerts for cluster-version-operator

---

pkg/cvo/cvo_scenarios_test.go
pkg/cvo/sync_worker.go

Currently the `!equalUpdate` is always true when the upgrade was force. This causes all the syncs to retrieve the payload and then sync.. when the payload only needs to be retrieved once. Also added a test to ensure the behavior.

pkg/cvo: ensure payload is retirved once when forced upgrade

---

pkg/cvo/sync_worker.go
pkg/payload/task_graph.go
pkg/payload/task_graph_test.go

When a large chunk of the objects in the payload are deleted, the
current algorithm for reconcile could in theory take an unlimited
number of attempts to try the entire payload. Instead, for each
permutation of order, try 8 successive attempts starting at
different positions within the step order. I.e.:
```
attempt 1: permute CGEABHDF, start at C
attempt 2: permute CGEABHDF, start at G
...
attempt 8: permute CGEABHDF, start at F
attempt 9: permute AHFECBGD, start at A
...
```
This significantly caps the number of attempts required to cover
the full payload.
Grew irritated at this when testing how the cluster recovers from
a mass deletion event (it takes upwards of 12-16 sync intervals to
restore all objects, just due to the wait on creating objects).

Bug 1749890: Iterate through the payload in chunks during reconciliation

---

pkg/cvo/status.go

Fix a bug where `history[n-1].completionTime == history[n].startedTime`.  @smarterclayton [pointed out this fix][2].
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=1756461#c3

Bug 1756461: pkg/cvo/status: Don't clobber last.CompletionTime when adding new entries

---

docs/dev/clusterversion.md

I'm not sure when we started enforcing this, but against a recent 4.2 nightly:
```console
$ cat version-patch.yaml
- op: add
path: /spec/overrides
value:
- kind: ImageStream
name: must-gather
namespace: openshift
unmanaged: true
$ oc patch clusterversion version --type json -p "$(cat version-patch.yaml)"
The ClusterVersion "version" is invalid: ... "image":"registry.svc.ci.openshift.org/wking/openshift4@sha256:9b5d0863abafcb98d1be5a4cf153e919530ba79ea4b18c390d602f9284cf916b", "startedTime":"2019-09-16T18:44:55Z", "state":"Completed", "verified":false, "version":"4.2.0-0.nightly-2019-09-11-114314"}}, "observedGeneration":1, "versionHash":"ukrOqloEb10="}}: validation failure list:
spec.overrides.group in body is required
```

docs/dev/clusterversion: Set 'group' in patch manifests

---

cmd/main.go

Bug 1665828: cmd/main.go: fix cli use to cluster-version-operator instead of version

---

lib/resourcemerge/apps.go
lib/resourcemerge/apps_test.go

The CVO wrongly makes an update API call and returns `modified=true` when ensuring deployments with same number of replicas

bug 1764017: Fix replicas comparison

---

pkg/payload/task_graph.go
pkg/payload/task_graph_test.go

Avoid situations [like][1]:
```
2019-10-21T10:34:30.63940461Z I1021 10:34:30.639073       1 start.go:19] ClusterVersionOperator v1.0.0-106-g0725bd53-dirty
...
2019-10-21T10:34:31.132673574Z I1021 10:34:31.132635       1 sync_worker.go:453] Running sync quay.io/runcom/origin-release:v4.2-1196 (force=true) on generation 2 in state Updating at attempt 0
...
2019-10-21T10:40:16.168632703Z I1021 10:40:16.168604       1 sync_worker.go:579] Running sync for customresourcedefinition "baremetalhosts.metal3.io" (101 of 432)
2019-10-21T10:40:16.18425522Z I1021 10:40:16.184220       1 task_graph.go:583] Canceled worker 0
2019-10-21T10:40:16.184381244Z I1021 10:40:16.184360       1 task_graph.go:583] Canceled worker 3
...
2019-10-21T10:40:16.21772875Z I1021 10:40:16.217715       1 task_graph.go:603] …
```

Bug 1763821: pkg/payload/task_graph: Canceling the task graph partway though is an error even if no tasks fail

---

lib/resourcebuilder/apiext.go

This is softening 4ee7b07 (#259) to use the older v1beta1 API version for waiting for CRDs to be established. This fixes the creation of v1beta1 CRDs before kube-apiserver is updated during a 4.2->4.3 update.
Note: this will not fix the creation of v1 CRDs before kube-apiserver is upgraded. Hence, we are still restricted in the use of v1 CRDs for early manifests.

apiext: wait for CRD using v1beta1 for compatibility on upgrades

---

pkg/cvo/cvo.go
pkg/cvo/cvo_scenarios_test.go
pkg/cvo/cvo_test.go
pkg/cvo/status.go
pkg/cvo/sync_test.go
pkg/cvo/sync_worker.go
pkg/cvo/upgradeable.go
pkg/payload/precondition/clusterversion/upgradeable.go
pkg/payload/precondition/precondition.go
pkg/payload/precondition/precondition_test.go
pkg/payload/task.go
pkg/start/start_integration_test.go

Bug 1730401: prevent automatic upgrades for clusters with cluster operators reporting Upgradeable false

---

Dockerfile

This modifies the Dockerfile to add the build support for archs other than amd64, based on the commit: https://github.com/openshift/cluster-version-operator/commit/bd1c181d38016f5f840353cbd7ce45fdce1f546a

Adding support for other archs than amd64

---

pkg/cincinnati/cincinnati.go
pkg/cincinnati/cincinnati_test.go
pkg/cvo/availableupdates.go
pkg/cvo/cvo_test.go

We [want][1] to be able to distinguish these conditions, which can be due to internal misconfiguration or external Cincinnati/network errors.  The former can be fixed by cluster admins.  The latter could go either way.
I dropped the `len(upstream)` guard from `checkForUpdate` because there's already an earlier guard in `syncAvailableUpdates`.  The guard I'm removing is from db150e6db4 (#45).  The covering guard is from the later 286641de68 (#55).
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1685338

Bug 1685338: pkg/cvo: Reason granularity for RemoteFailed

---

pkg/cvo/cvo.go
pkg/cvo/cvo_scenarios_test.go
pkg/cvo/sync_worker.go
pkg/start/start.go
pkg/start/start_integration_test.go

Allows specifying an identifier with the `EXCLUDE_MANIFESTS` environment variable that will be used to skip manifests that contain an annotation like `exclude.release.openshift.io/<identifier>=true`

Allow excluding manifests from CVO payload

---

install/0000_00_cluster-version-operator_03_deployment.yaml
install/0000_90_cluster-version-operator_01_prometheusrolebinding.yaml
install/0000_90_cluster-version-operator_02_servicemonitor.yaml
install/0001_00_cluster-version-operator_03_service.yaml

Enables the CVO to exclude manifests in an externally hosted control plane deployment
See https://github.com/openshift/cluster-version-operator/pull/252

Add annotations to manifests to exclude in hosted deployment

---

install/0000_90_cluster-version-operator_02_servicemonitor.yaml
pkg/cvo/metrics.go
pkg/cvo/metrics_test.go
pkg/payload/render.go

Backports #232 to release-4.1. Also pulls in the precursor commits from #221, and #214.
This one is smaller cherry-pick of https://github.com/openshift/cluster-version-operator/pull/253 because that one needs changes in the CMO to move the servicemonitor to the CVO management.
This only moves the alerts using `PrometheusRule` skipping the `ServiceMonitor`
This is not a clean cherry-pick and definitely needs review.
/cc @wking @smarterclayton

Bug 1762920: install: add alerts for cluster-version-operator

---

README.md
pkg/cvo/availableupdates.go
pkg/cvo/cvo.go
pkg/verify/verify.go
pkg/verify/verify_test.go

This PR adds proxy support to the CVO for verifying signatures. It centralizes some of the proxy logic used in Cincinnati to be shared. More significantly, it restructures the releaseVerifier struct to be able to use an up-to-date proxy. The releaseVerifier is created before a watch has been established on the cluster proxy. This PR ensures that the releaseVerifier gets the proxy after it is available to the operator and that the proxy settings are updated if there are any changes to the configuration.
Fixes BZ-1766907.

Bug 1766907: Add proxy support for CVO.

---

pkg/cvo/updatepayload.go

We want to be in burstable QoS, and we want to avoid causing warnings
if e2e runs detect that we happen to be running when they see we
aren't in burstable.

Bug 1781283: Set resource requests on the extract job

---

pkg/cvo/updatepayload.go

We want to be in burstable QoS, and we want to avoid causing warnings
if e2e runs detect that we happen to be running when they see we
aren't in burstable.

Bug 1781284: Set resource requests on the extract job

---

pkg/cvo/availableupdates.go
pkg/cvo/cvo.go
pkg/verify/verify.go
pkg/verify/verify_test.go

cherry-picks 00abef67c28a2069d7a1138a34043d8252197be3 34ab90db4cb0554eb1d90f1364365fc03dafc83a from https://github.com/openshift/cluster-version-operator/pull/267
This PR adds proxy support to the CVO for verifying signatures. It centralizes some of the proxy logic used in Cincinnati to be shared. More significantly, it restructures the releaseVerifier struct to be able to use an up-to-date proxy. The releaseVerifier is created before a watch has been established on the cluster proxy. This PR ensures that the releaseVerifier gets the proxy after it is available to the operator and that the proxy settings are updated if there are any changes to the configuration.
NOTE: This required a manual cherry-pick and conflict resolution, So please re-review.
/cc @patrickdillon

Bug 1775836: Add proxy support for CVO

---

pkg/cvo/updatepayload.go

Reopening #289 on release-4.3, since Prow seemed to not notice [my changing #289's base branch][1].
[1]: https://github.com/openshift/cluster-version-operator/pull/289#event-2918526191

Bug 1787334: pkg/cvo/updatepayload: Drop ephemeral-storage request

---

pkg/cvo/updatepayload.go

I dunno why there is no capacity reporting in 4.2, but ephemeral-storage capacity reporting is not working there, leading to version pods dying [with][1]:
> Node didn't have enough resource: ephemeral-storage, requested: 2097152, used: 0, capacity: 0
For an example of a 4.2 cluster without ephemeral-storage capacity reporting, see [this 4.2.10 -> 4.2.12 update test][2]:
```console
$ curl -s https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/12620/artifacts/e2e-aws-upgrade/must-gather/quay-io-openshift-release-dev-ocp-v4-0-art-dev-sha256-a0dbe73b7831a8ddb9a2c58a560461d7c2c23a92231289a2104b93e7723c0eff/cluster-scoped-resources/core/nodes/ip-10-0-129-58.ec2.internal.yaml | yaml2json | jq .status.capacity | json2yaml …
```

Bug 1786315: pkg/cvo/updatepayload: Drop ephemeral-storage request

---

lib/resourcemerge/core.go

We've [claimed][0]:
> if we have no required, then we don't care what someone else has set
since this code landed in d9f6718de0 (#7).  But we do care in situations like [rhbz#1791863][1], where a 4.3 -> 4.2 downgrade leaves 4.3 readiness probes in place for a 4.2 operator which has no `/readyz`.
With this pull-request we still have a few other types where we claim to not care:
```console
$ git grep -hB1 'someone else has set' | grep func
func ensureSecurityContextPtr(modified *bool, existing **corev1.SecurityContext, required *corev1.SecurityContext) {
func ensureCapabilitiesPtr(modified *bool, existing **corev1.Capabilities, required *corev1.Capabilities) {
func ensureAffinityPtr(modified *bool, existing **corev1.Affinity, required *corev1.Affinity) {
func …
```

Bug 1791863: lib/resourcemerge/core: Clear livenessProbe and readinessProbe if nil in required

---

pkg/verify/verifyconfigmap/store.go

`NewStore` creates a limiter, but doesn't pass it to `Store`. Later Store 
attempts to use it in `DigestSignatures` - and explodes

Bug 1793051: cvo: pass limiter when creating a store

---

pkg/payload/task.go
pkg/payload/task_test.go

This is helpful when one of the manifests doesn't have a name (like `kind: List` in [image-registry PR](https://github.com/openshift/cluster-image-registry-operator/commit/d197841e7944138ee2dc0815f2749c4f67657889#diff-88bbb853bcd5a5fbc188c46767630fadR1))
This list still cannot be applied (`apply` requires a name to find existing resource) but it would be helpful to debug these kind of issues.
TODO:

Bug 1790629: use st.Manifest.OriginalFilename if object doesn't have a name

---

lib/resourcemerge/core.go
lib/resourcemerge/core_test.go

Avoid:
```console
$ go test ./lib/resourcemerge/
panic: runtime error: index out of range [recovered]
panic: runtime error: index out of range
goroutine 38 [running]:
testing.tRunner.func1(0xc0001ab000)
/home/trking/sdk/go1.12.9/src/testing/testing.go:830 +0x392
panic(0xccb520, 0x163f880)
/home/trking/sdk/go1.12.9/src/runtime/panic.go:522 +0x1b5
github.com/openshift/cluster-version-operator/lib/resourcemerge.ensureContainers(0xc0000bbd57, 0xc0001d4040, 0xc0001cd760, 0x1, 0x1)
/home/trking/.local/lib/go/src/github.com/openshift/cluster-version-operator/lib/resourcemerge/core.go:69 +0x840
github.com/openshift/cluster-version-operator/lib/resourcemerge.ensurePodSpec(0xc0001c5d57, 0xc0001d4010, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0001cd760, 0x1, ...) …
```

Bug 1783221: lib/resourcemerge/core: Fix panic on container/port removal

---

lib/resourceapply/apiext.go

This will help to see hotloops due to missing defaults in manifests, leading invisibly to https://bugzilla.redhat.com/show_bug.cgi?id=1795412.

Bug 1795412: Print whether CRDs are updated

---

pkg/cvo/sync_test.go
pkg/cvo/sync_worker.go
pkg/payload/precondition/clusterversion/upgradable_test.go
pkg/payload/precondition/clusterversion/upgradeable.go
pkg/payload/precondition/precondition.go

If current and desired have the same 4.y, then the upgrade is allowed even
if upgradeable==false.  If the 4.y is different, then upgrades are not allowed.
This permits CVE updates and fixes the current service-catalog upgrade problem.
Alternative to https://github.com/openshift/cluster-version-operator/pull/285

Bug 1797624: loosen upgradeable condition to allow z-level upgrades

---

pkg/cvo/metrics.go
pkg/cvo/metrics_test.go
pkg/internal/constants.go

This is a follow-on to c1477328, which added the cluster_installer
series originally. Recently, the installer started injecting a new
ConfigMap (openshift-install-manifests), which includes information
about the manifest generation stage of the install. Because this phase
always happens, this ConfigMap is included in every cluster created by
this newer installer. We can now look at the presence of this new
ConfigMap and the absence of the openshift-install ConfigMap to
determine that the cluster was installed using UPI. We can additionally
look at its contents to determine information about the installer.

Bug 1797806: metrics: include upi installs in cluster_installer

---

OWNERS

The repo-scoped `OWNERS` file here isn't large, and the CVO is nobody's main focus.  Add group-lead @sdodson to broaden the set of folk who can be talked into approving changes during a maintainer shortage ;).

OWNERS: Add Scott Dodson as an approver

---

lib/resourcemerge/core.go
lib/resourcemerge/core_test.go

This ensures container ports which are no longer specified are
being removed

Bug 1801300: lib/resourcemerge: remove ports which are no longer required

---

lib/resourcemerge/core.go
lib/resourcemerge/core_test.go

This ensures container ports which are no longer specified are
being removed

Bug 1802710: lib/resourcemerge: remove ports which are no longer required

---

lib/resourcebuilder/batch.go

When the cluster version operator is in Initialization mode, don't wait for jobs to complete to allow for maximum traversal of the requirement..

bug 1794817: lib/resourcebuilder/batch.go: skip waiting for job to complete when in Init mode

---

pkg/verify/verifyconfigmap/store.go

Instead of using the `{algo}:{hash}` digest directly, because [colons are not allowed in ConfigMap keys][1]:
```go
const configMapKeyFmt = `[-._a-zA-Z0-9]+`
```
The keys also have a [maximum length][1] of [253 characters][2], but sha256 digests are only a 6 char algorithm, 1 char delimiter, and 64 char hex hash, so there's plenty of space for user-defined suffixes in the ConfigMap keys.
I'm using a hyphen (`-`) as the delimiter, because neither the canonical `:` nor the `=` used for signature URIs are [allowed in ConfigMap keys][1].  Hyphens are not valid in algorithm-component, although they [are valid in algorithm-separator][3]:
```
digest              ::= algorithm ":" encoded
algorithm           ::= algorithm-component (algorithm-separator algorithm-component)*
algorithm-component ::= …
```

Bug 1782982: pkg/verify/verifyconfigmap: Use {algo}-{hash} prefixes

---

lib/resourcemerge/core.go
lib/resourcemerge/core_test.go

This ensures container ports which are no longer specified are
being removed
Cherrypick of https://github.com/openshift/cluster-version-operator/pull/323 on release-4.2

Bug 1802248: lib/resourcemerge: remove ports which are no longer required

---

lib/resourcebuilder/apps.go
pkg/payload/task.go

waitFor{Deployment,Daemonset} now return UpdateError's so that the sync cycle can include detailed errors.
deployment:
- when replicafailure condition is true, returns WorkloadNotProgressing update error.
- when available condition is false or progressing is true, returns WorkloadNotAvailable update error.
daemonset:
It returns WorkloadNotAvailbale update error whenever the daemonset has not rolled out.

Bug 1768260: lib,pkg: provide detailed errors for workload failures

---

pkg/verify/verifyconfigmap/store.go

To make it easier to understand where things are breaking down when they [don't work as expected][1].
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1782982#c16

Bug 1805172: pkg/verify/verifyconfigmap: Add klog logging

---

lib/resourcemerge/core.go
lib/resourcemerge/core_test.go

This pull-request cherry-picks e8e80c2c8f (#282) back to the 4.2 branch.  But since f268b6d478 (#272) and its `EnsureServicePorts` was never backported to the 4.2 branch, I've only kept the container portion of e8e80c2c8f in this PR.

Bug 1800346: lib/resourcemerge/core: Fix panic on container removal

---

docs/user/status.md

The messages included in the condition are intended to be fairly clear, but add some additional docs here where we can talk about the impact of the failure and suggest possible mitigations.

docs/user/status: Document RetrievedUpdates reasons

---

README.md

As logically the install section should come first and
then the use section. 
Also made the section `Using CVO to render the release-image locally` reference more explicit. 

Rearranging the sections in README

---

OWNERS

OWNERS: Add component Cluster Version Operator

---

OWNERS

Example of OpenShift components:
```console
$ curl -sH Accept:application/json -H Content-Type:application/json --data '{"jsonrpc":"2.0","method":"SelectizeJS.list_components","id":1,"params":[{"term":"..","descrs":1,"disabled":0,"product":"v314_product"}]}' https://bugzilla.redhat.com/jsonrpc.cgi | jq -r '[.result[].value] | sort[]'
Build
Cincinnati
Cloud Compute
Cloud Credential Operator
Cluster Loader
Cluster Version Operator
Compliance Operator
...
```
Based on @sdodson's [comment][1]:
> It's used downstream to facilitate mapping to BZ Components.
[1]: https://github.com/openshift/cluster-version-operator/pull/344#issuecomment-610902992

OWNERS: Document 'component' property

---

lib/resourcebuilder/interface.go
pkg/cvo/cvo.go
pkg/cvo/internal/operatorstatus.go
pkg/cvo/sync_worker.go
pkg/payload/payload.go

The must-gather and insights operator depend on cluster operators
and related objects in order to identify resources to create. Because
cluster operators are delegated to the operator install and upgrade
failures of new operators can fail to gather the requisite info if
the cluster degrades before those steps.
Add a new selective Precreating install mode and do a single pass
over all cluster operators in the payload without retries at the beginning
of an initializing or upgrading sync pass to attempt to create the
ClusterOperators if they don't exist.

cvo: When installing or upgrading, fast-fill cluster-operators

---

docs/dev/clusteroperator.md

Failing was deprecated in favour of Degraded, this updates the docs to reflect that to avoid confusion.

docs/dev/clusteroperator.md: Change Failing to Degraded

---

pkg/payload/task.go

Because this makes it easier to grow the `SummaryForReason` logic.  The previous, generic error message is not very useful (e.g. as seen [here][1]).
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1710012#c0

Bug 1825003: pkg/payload/task: Include name/reason in "unknown error" message

---

pkg/cvo/cvo.go

Upstream pull request https://github.com/kubernetes/kubernetes/pull/77170. It is available in upstream v1.15

Using optr.queue.ShutDown directly as upstream K8s is fixed now

---

lib/resourceread/apiext.go
lib/resourceread/apiext_test.go

The v1 scheme was not being passed to the decoder.

Bug 1825512: Support v1 crds in manifests

---

docs/dev/clusteroperator.md

This https://github.com/openshift/cluster-version-operator/pull/318 introduced a PrecreatingMode which actually let the CVO to push the clusterOperator in manifests.
This changes previous behaviour and enables a new pattern for individual operators to set related objects into the clusterOperator defined in manifests/ https://github.com/openshift/cluster-kube-apiserver-operator/pull/833
https://github.com/openshift/cluster-etcd-operator/pull/312
https://github.com/openshift/cluster-kube-controller-manager-operator/pull/398

Update readme to include fast fill logic

---

install/0001_00_cluster-version-operator_03_service.yaml

Fix for https://bugzilla.redhat.com/show_bug.cgi?id=1809195 is to add
https metrics target. The PR to fix that bug is failing CI upgrade
test since the 0001_00_cluster-version-operator_03_service with the
service.beta.openshift.io/serving-cert-secret-name annotation is
coming too late. So the monitoring tools aren't creating the secret
causing the CVO container to fail to start.
This PR adds the annotation to the service so that change can be
fielded ahead of remaining changes necessary to support https
target.

Bug 1834568: Add cert to service to support https

---

hack/cluster-version-util/task_graph.go
pkg/cvo/cvo.go
pkg/cvo/cvo_scenarios_test.go
pkg/cvo/sync_worker.go
pkg/cvo/testdata/payloadtest/release-manifests/0000_20_a_exclude.yml
pkg/payload/payload.go
pkg/payload/payload_test.go
pkg/payload/task_graph_test.go

In 4.5 we added code to precreate cluster-operator resources. However, in the precreate loop we're not checking whether resources should be excluded based on annotation. This adds a check to the loop so we can preserve pre-4.5 behavior.

Bug 1838872: Avoid pre-creating clusteroperators that should be excluded

---

pkg/payload/task_graph.go

The old format is from cb4e0375e6 (#88), but @abhinavdahiya [points out][1] that `on %d` could use a bit more context.
[1]: https://github.com/openshift/cluster-version-operator/pull/264#discussion_r433554377

pkg/payload/task_graph: "on" -> "on worker" logging

---

pkg/cvo/sync_worker.go

To match the existing v4 logs for:
Running sync %s (force=%t) on generation %d in state %s at attempt %d
To avoid excessive noise, also restrict it to edge transitions between states (the `Running sync ...` line exposes the level) and include the source state in the logged message.  Because the * -> `Reconciling` transition is important, and deserves at least as much weight in the logs as "we're about to start a new sync cycle" and a log entry that comes before the next `Until` sleep.

pkg/cvo/sync_worker: Promote "Sync succeeded" to v4

---

pkg/cvo/sync_worker.go

One less level of nesting makes for slightly easier reading.  The nested `if changed` landed when `sync_worker.go` was born in 961873d66a (#82).

pkg/cvo/sync_worker: Flatten a nested 'if changed'

---

pkg/cvo/availableupdates.go
pkg/cvo/cvo_test.go

The previous `At` had been tracking the most recent attempt, regardless of success.  With this PR, we rename it to the more explicit `LastAttempt` and add godocs explaining the intended semantics.
Also grow a `LastSyncOrConfigChange` sibling, tracking the time since the last success (or since the configured upstream had been changed).  This will make it more convenient to alert when the slice of available updates is stale, although that alert itself and the metric that feeds it will come from #357.

pkg/cvo/availableupdates: Split 'At' into LastAttempt and LastSyncOrConfigChange

---

pkg/cvo/sync_worker.go

The property landed with SyncWorker in 961873d66a (#82), but has never been used.

pkg/cvo/sync_worker: Drop unused 'reconciling' from SyncWorker

---

pkg/cvo/sync_worker.go

With this commit, I drop `contextIsCancelled` in favor of `Context.Err()`. From [the docs][1]:
> If Done is not yet closed, Err returns nil.  If Done is closed, Err returns a non-nil error explaining why: Canceled if the context was canceled or DeadlineExceeded if the context's deadline passed.  After Err returns a non-nil error, successive calls to Err return the same error.
I dunno why we'd been checking `Done()` instead, but `contextIsCancelled` dates back to 961873d66a (#82).
I've also generalized a number of `*Cancel*` helpers to be `*Context*` to remind folks that `Context.Err()` can be `DeadlineExceeded` as well as `Canceled`, and the CVO uses both `WithCancel` and `WithTimeout`.  The new error messages will be either:
update context deadline exceeded at 1 of 2
or:
update context …

Bug 1838497: pkg/cvo/sync_worker: Do not treat "All errors were context errors..." as success

---

pkg/cvo/sync_worker.go

Cherry-picked from #378 and edited to resolve context conflicts because release-4.4 lacks #318.

Bug 1843732: pkg/cvo/sync_worker: Do not treat "All errors were context errors..." as success

---

pkg/payload/task_graph.go
pkg/payload/task_graph_test.go

We want to give #255 time to cook in master before backporting it, so:
/hold
while that happens.  Once it does, I think we want this larger refactor in the master branch, even if we don't end up backporting it to earlier z streams.
The old code launched a goroutine for the pushing/reaping, which was an unecessary, and made error reporting on any outstanding tasks more complicated.  Dropping this goroutine let me get rid of `errCh` which used to be used to pass errors back to the main goroutine.  I also dropped the `wg.Wait()` goroutine, which used to be part of supporting the `range errCh` used in the main goroutine to collect failed jobs. But because `errCh` was filled directly from the worker goroutines, nothing used to be collecting the completeness of graph coverage from the …

pkg/payload/task_graph: Handle node pushing and result collection without a goroutine

---

docs/user/reconciliation.md
docs/user/status.md
pkg/cvo/cvo.go
pkg/cvo/cvo_scenarios_test.go

Because every `Failing=True` condition should have a reason.
Also wordsmith the user-facing docs to replace "synchronize" with "reconcile", because our merge logic is more nuanced than the complete match "synchronize" implies for me.

pkg/cvo: Set NoDesiredImage reason when desired.Image is empty

---

CONTRIBUTING.md
README.md
lib/resourceread/apiext_test.go
pkg/autoupdate/autoupdate.go
pkg/cvo/cvo_test.go

Based on [the installer's][1], but with a few local changes like:
* No section about mock tests, because we don't have any.
* No section about the Developer Certificate of Origin, because we don't use `Signed-off-by`, and I'm skeptical about how binding a `CONTRIBUTING.md` -> `DCO` link is vs. a contributor claiming "I just wrote a commit; I didn't read all the docs in the repo first".  If we decide that a `CONTRIBUTING.md` -> `DCO` link is binding, we can always add it later.
* Trimmed down section about linting, because we don't do as much of that as the installer.
* One sentence per line, so we don't have to worry about rewrapping (and complicating diff/blame) as we edit this content going forward.
* Whatever else seemed reasonable when I went through ;).
Also wash the repository …

CONTRIBUTING: Add a contributing file

---

lib/resourcemerge/core.go
lib/resourcemerge/core_test.go

Before this change, only the initialDelaySeconds field of probes could be
updated. This patch expands the set of supported fields to include all the
other int32 fields of probes so that CVO will roll out such changes.

Bug 1847672: Expand supported set of probe field mutations

---

install/0000_90_cluster-version-operator_02_servicemonitor.yaml

During modifications for
https://github.com/openshift/cluster-version-operator/pull/358/ a new first
line of spec was added and therefore next line should not contain '-'.

Bug 1809195: Remove '-' from servicemonitor spec

---

hack/build-go.sh

This would update the build script, so that OCP could be built using
a custom semver string from OS_GIT_VERSION instead of `git describe` output

Bug 1826349: hack/build-go: Use OS_GIT_VERSION if available

---

pkg/cvo/cvo.go
pkg/verify/configmap.go
pkg/verify/store/configmap/configmap.go
pkg/verify/store/memory/memory.go
pkg/verify/store/parallel/parallel.go
pkg/verify/store/parallel/parallel_test.go
pkg/verify/store/serial/serial.go
pkg/verify/store/serial/serial_test.go
pkg/verify/store/store.go
pkg/verify/verify.go
pkg/verify/verify_test.go

Builds on top of #294.  You can review that one first if you like, or review both commits in this PR (and GitHub will mark #294 merged if this one lands first, because it will pull #294's tip into the target `master` branch).  With #294, the change we need to make to parallelize HTTP(S) retrieval is pretty small.  I'm just adding a parallel store implementation and using that instead of the serial wrapper for HTTP(S) retrieval.

Bug 1840343: pkg/verify: Parallelize HTTP(S) signature retrieval

---

pkg/cvo/cvo.go
pkg/verify/configmap.go
pkg/verify/store/configmap/configmap.go
pkg/verify/store/memory/memory.go
pkg/verify/store/serial/serial.go
pkg/verify/store/serial/serial_test.go
pkg/verify/store/store.go
pkg/verify/verify.go
pkg/verify/verify_test.go

This abstracts signature retrieval, setting the stage for future pivots such as fetching signatures from config maps in the local cluster.
Spun off from [these suggestions][1] for #279.  I've left the file implementation in place to minimize the diff (in 0cc3e41c1d04 I'd replaced it with an in-memory sig store).  I've also left both the file and HTTP stores in the `verify.go` file to minimize the diff (in 0cc3e41c1d04 I'd moved the HTTP store into a subpackage to simplify `verify.go`).
[1]: https://github.com/openshift/cluster-version-operator/pull/279#discussion_r359239295

pkg/verify: Refactor signature fetching to only use a Store interface

---

install/0000_90_cluster-version-operator_02_servicemonitor.yaml

Added alert ClusterNotUpgradeable that fires when metric
cluster_operator_conditions{name="version"} reports condition Upgradeable as
false for > 1 hour. Alert reports the reason cluster is not upgradeable and
console URL to get more information.

Add an alert to CVO that fires when cluster is not upgradeable

---

pkg/cvo/availableupdates.go
pkg/cvo/cvo.go
pkg/cvo/egress.go
pkg/cvo/metrics.go
pkg/start/start.go
pkg/start/start_integration_test.go

Somewhat like [this example][1].  This pushes the server management down into a new `RunMetrics` method, which we then run in its own goroutine.  This is initial groundwork; I expect we will port more of our child goroutines to this framework in follow-up work, e.g. by launching a set of long-running manifest-recociliation goroutines for [rbhz#1822752][2].
[1]: https://golang.org/pkg/net/http/#Server.Shutdown
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=1822752

pkg/cvo/metrics: Graceful server shutdown

---

pkg/cvo/cvo.go
pkg/cvo/cvo_test.go
pkg/verify/configmap.go
pkg/verify/configmap_test.go
pkg/verify/store/sigstore/client.go
pkg/verify/store/sigstore/sigstore.go
pkg/verify/store/sigstore/sigstore_test.go
pkg/verify/verify.go
pkg/verify/verify_test.go

Decluttering the root verify package and making it more store-agnostic.
I've also replaced the `ClientBuilder` interface with a single `HTTPClient` function type, which removes the need for `verifyClientBuilder` and other wrappers.  I'm also adding a rate-limiter around the client builder to avoid pounding away at that logic, even if it's mostly fed through informers (so should be no API-call reduction, but will save some local CPU cycles).
Spun off from my [earlier][1] 0cc3e41c1d04 as another nibbly bit (hopefully easy to review), now that the bulk of the earlier change has landed via #294.  Still to go after this change will be a similar sub-package for the file store, or deprecating the file store in favor of #294's memory store for unit testing.
[1]: …

pkg/verify/store/sigstore: Factor HTTP store into its own package

---

lib/resourcebuilder/apps.go

`deploymentBuilder` and `daemonsetBuilder` grow `mode` properties.  They had been using `actual.Generation > 1` as a proxy for "post-install" since 14fab0b2c8 (#26), but generation 1 is just "we haven't changed the object since it was created", not "we're installing a fresh cluster".  For example, a new Deployment or DaemonSet could be added as part of a cluster update, and we don't want special install-time "we don't care about specific manifest failures" then.
Spun out from #400 at @smarterclayton's [request](https://github.com/openshift/cluster-version-operator/pull/400/#issuecomment-655152378).

lib/resourcebuilder/apps: Explicit mode instead of 'Generation > 1'

---

docs/user/reconciliation.md

The image tags now contains arch information, hence the existing command was not
working.

Fixing a command in reconciliation document

---

install/0000_00_cluster-version-operator_03_deployment.yaml
lib/resourcebuilder/apps.go
lib/resourcebuilder/podspec.go
lib/resourcebuilder/podspec_test.go

During upgrades and kube-apiserver rollouts, the localhost connection can become
unavailable for multiple minutes. Using the internal loadbalancer prevents the
outage and lease loss.
/hold  
unit tests are owed, so I'm holding the PR, but I'd like to demonstrate the idea and see how CI reacts.

update CVO to inject internal loadbalancer for use by the CVO pod

---

lib/resourcebuilder/apiext.go

Error for unrecognized CRD version, because that will be easier to debug than trying to figure out why a CRD manifest is being silently ignored by the CVO (which is what we've done since the version switch landed in 4ee7b07e99, #259).  Split out from #400 at @smarterclayton's [request](https://github.com/openshift/cluster-version-operator/pull/400#issuecomment-655152378).

lib/resourcebuilder/apiext: Error on unrecognized CRD version

---

pkg/cvo/cvo.go
pkg/cvo/cvo_scenarios_test.go
pkg/cvo/sync_test.go
pkg/cvo/sync_worker.go
pkg/payload/precondition/clusterversion/upgradable_test.go
pkg/payload/precondition/clusterversion/upgradeable.go
pkg/payload/precondition/precondition.go

CVO Upgradeable=False should block all upgrades including z level.

Bug 1822844: Block z level upgrades when ClusterVersionOverridesSet is set

---

pkg/cvo/cvo.go
pkg/cvo/cvo_scenarios_test.go
pkg/cvo/cvo_test.go
pkg/cvo/metrics_test.go
pkg/cvo/status_test.go
pkg/cvo/sync_test.go
pkg/cvo/sync_worker.go
pkg/cvo/sync_worker_test.go
pkg/start/start_integration_test.go

Since the CVO updates itself every time it updates, we always lose our logs for what happens when the update starts.  Updates are infrequent enough that we can emit events for them without loading the kube-apiserver.

emit events for each new payload

---

pkg/cvo/cvo_scenarios_test.go

Typo is from d06f4be481 (#244).

pkg/cvo/cvo_scenarios_test: Fix "Retrive" -> "Retrieve" typo

---

pkg/cvo/cvo_test.go

The three cases landed with the same name in 04528144fe (#243).  The new names make the differences, which all involve the presence and state of `default-operator-2`, more obvious.

pkg/cvo/cvo_test: Distinguish names for the "single clusteroperator" cases

---

lib/resourcebuilder/apiext.go
lib/resourcebuilder/apps.go
lib/resourcebuilder/batch.go

We've had `if updated` guards around `waitFor*Completion` since the library landed in 2d334c2190 (#10).  But, only waiting when `updated` is true is a weak block, because if/when we fail to complete, [`Task.Run` will back-off and call `builder.Apply` again][0].  That new `Apply` will see the already-updated object, set `updated` false, and not wait.  So whether we block or not is orthogonal to `updated`; nobody cares about whether the most recent update happened in this `builder.Apply`, this sync cycle, or a previous cycle.
We don't even care all that much about whether the Deployment, DaemonSet, CustomResourceDefinition, or Job succeeded.  Most feedback is going to come from the ClusterOperator, so with this commit we continue past the resource wait-for unless the resource is really …

lib/resourcebuilder: Replace wait-for with single-shot "is it alive now?"

---

pkg/cincinnati/cincinnati.go
pkg/cincinnati/cincinnati_test.go
pkg/cvo/availableupdates.go
pkg/cvo/cvo.go
pkg/cvo/cvo_test.go
pkg/cvo/sync_worker.go
pkg/cvo/sync_worker_test.go

Change CVO wait.Until instances to wait.UntilWithContext making top-level context available to the lower levels of the code. Use the added context to add a timeout to the remote cincinnati HTTP call which has the potential to hang the caller at the mercy of the target server.
The timeout has been set to an hour which was determined to be long enough to allow all expected well-behaved requests to complete but short enough to not be catastrophic if the calling thread were to hang.

Use context to add timeout to cincinnati HTTP request

---

pkg/cvo/cvo.go
pkg/cvo/cvo_test.go
pkg/cvo/egress.go
pkg/internal/constants.go

[The API docs][1] recommend avoiding `trustedCA` (unless you happen to be the "proxy validator") and instead pulling the trust bundle from this managed namespace.  The docs also explain that the `trusted-ca-bundle` ConfigMap has already been merged with the system certificates, so we don't need to inject those locally.  If `trusted-ca-bundle` doesn't exist, we'll fall back to our local system store.
Our logic was touched most recently in 5968cdf933 (#231), which resolved the "looking in the wrong place" issue by looking at the `trustedCA` source (which feeds the proxy validator).  With this commit we switch that around and look at the proxy validator's output.
[1]: https://github.com/openshift/api/blob/f2a771e1a90ceb4e65f1ca2c8b11fc1ac6a66da8/config/v1/types_proxy.go#L44-L52

Bug 1797123: pkg/cvo: Fetch proxy CA certs from openshift-config-managed/trusted-ca-bundle

---

docs/user/status.md
pkg/cvo/status.go

Reduce false-positives when operators take a while to level (like the machine-config operator, which has to roll the control plane machines).  We may want to raise this further in the future, but baby steps ;).

Bug 1862524: pkg/cvo/status: Raise Operator leveling grace-period to 20 minutes

---

docs/user/status.md
pkg/cincinnati/cincinnati.go
pkg/cincinnati/cincinnati_test.go

When you initiate an update from A -> B, if B is not found in the current channel, the cluster would start reporting VersionNotFound after it's first attempt to retrieve recommended updates for B.  That usually happens before the update completes, and the old "currently installed version" wasn't a very accurate description of B mid-update.  The new wording relaxes our claim about the cluster state (maybe it has been reconciled, maybe not) and just talks about the version we're attempting to reconcile.

pkg/cincinnati/cincinnati: Change "installed" -> "reconciling" for VersionNotFound

---

pkg/start/start.go

This resolves a problem where status doesn't reflect the payload actually being applied.
wking is chasing an alternative using different graceful leader election rules.
It would also be resolved by synchronously writing the status out when we start applying a new payload.

Bug 1843505: Have the leader election use faster defaults

---

pkg/autoupdate/autoupdate.go
pkg/cvo/cvo.go

This seems to have been copy-pasted from the machine-config operator in 6c8f725f5d (#7) and then from there over to the auto-update package with ad4bd6c428 (#11).  Update to generic wording that is less likely to go stale.

pkg/cvo: Fix maxRetries comment (not about machineconfig pools)

---

install/0000_90_cluster-version-operator_02_servicemonitor.yaml

Fixing an off-by-one from ccf08821e4 (#415).  One available update is all we need for this to go off.

b/install/0000_90_cluster-version-operator_02_servicemonitor: > 0 for UpdateAvailable

---

lib/resourcemerge/core.go

Ensure ShareProcessNamespace, DNSConfig and TerminationGracePeriodSeconds are copied during resource merge.
Not sure if this needs a test case - looks pretty straightforward to me

Bug 1866554: lib/resourcemerge/core: set ShareProcessNamespace, DNSConfig and TerminationGracePeriodSeconds

---

lib/resourcebuilder/apps.go

`Available=True`, `Progressing=False` is the happy, steady state.
`Available=True`, `Progressing=True` is a happy update.
`Available=False`, `Progressing=True` is acceptable outage, e.g. [during an update][1] with the `Recreate` strategy:
```console
$ curl -s https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade-4.6/1291426211527921664/artifacts/e2e-gcp-upgrade/container-logs/test.log | grep MinimumReplicasUnavailable | head -n1
Aug  6 17:56:00.674: INFO: deployment status: v1.DeploymentStatus{ObservedGeneration:1, Replicas:1, UpdatedReplicas:1, ReadyReplicas:0, AvailableReplicas:0, UnavailableReplicas:1, Conditions:[]v1.DeploymentCondition{v1.DeploymentCondition{Type:"Available", Status:"False", …
```

lib/resourcebuilder/apps: Only error on Deployment Available=False *and* Progressing=False

---

pkg/cvo/cvo.go
pkg/cvo/cvo_test.go
pkg/verify/configmap.go
pkg/verify/configmap_test.go
pkg/verify/store/configmap/configmap.go
pkg/verify/store/sigstore/sigstore.go
pkg/verify/testdata/manifests/loads-valid.yaml
pkg/verify/testdata/manifests/only-first-used.yaml
pkg/verify/testdata/manifests/requires-data.yaml
pkg/verify/testdata/manifests/requires-stores.yaml
pkg/verify/testdata/manifests/requires-verifiers.yaml
pkg/verify/util/encode.go
pkg/verify/util/util.go
pkg/verify/verify.go

Changes to verify package in preparation for move to library-go
The CVO verify package will be moved to library-go for reuse by 'oc adm release mirror' and CVO. Changes are being made here in CVO before the move to provide a cleaner move to library-go.
Logic to create verifier was broken out into a new configmap method NewFromManifests. This method uses k8s encoding and as a result existing test cases had to be changed from creating manifests from from declarations within the test cases itself to creating them from config map files. In this manner the lib/Manifest object is properly created with its Raw bytes field populated.

Changes to verify package in preparation for move to library-go

---

docs/dev/operators.md

The regular expression that the cluster-version operator actually uses is unchanged since it landed in cb4e0375e6 (#88).  But the regular expression given in the docs was over-simplified (e.g. it allowed the component to begin with a dash, while the actual expression forbids component-leading dashes).  Instead of talking about the specifics of the regular expression, just explain the different portions in the docs.

docs/dev/operators: Replace stale manifest filename regexp with generic discussion

---

docs/user/reconciliation.md
docs/user/status.md
pkg/cvo/cvo.go
pkg/cvo/cvo_scenarios_test.go
pkg/cvo/status.go

Backporting #422 and, to avoid rebase conflicts, the doc-only #371 to 4.5.

Bug 1866480: pkg/cvo/status: Raise Operator leveling grace-period to 20 minutes

---

pkg/cvo/cvo.go
pkg/start/start.go

With c9fab435c1 (#311), I attempted to pivot to loading the TLS configration from the `openshift-config-managed` namespace.  But I hadn't realized that `cmConfigInformer` was scoped to the `openshift-config` namespace, so attempts to retrieve `trusted-ca-bundle` failed via the "not found" no-op path regardless of whether the ConfigMap actually existed.  With this commit, I create a new informer for the `openshift-config-managed` namespace, so we can successfully retrieve the ConfigMap when it exists.
An alternative approach would be to drop the `informers.WithNamespace` filter.  My impression is that having two namespace-filtered informers will be more efficient than a single unfiltered informer, but I'm not really sure.

Bug 1797123: pkg/cvo: Separate ConfigMap informer for openshift-config-managed

---

bootstrap/bootstrap-pod.yaml
cmd/start.go
install/0000_00_cluster-version-operator_03_deployment.yaml
pkg/autoupdate/autoupdate.go
pkg/cvo/cvo.go
pkg/start/start.go
pkg/start/start_integration_test.go

So the incoming cluster-version operator doesn't need to wait for the outgoing operator's lease to expire, which [can take a while][1]:
```
I0802 10:06:01.056591       1 leaderelection.go:243] attempting to acquire leader lease  openshift-cluster-version/version...
...
I0802 10:07:42.632719       1 leaderelection.go:253] successfully acquired lease openshift-cluster-version/version
```
and [time out the `Cluster did not acknowledge request to upgrade in a reasonable time` testcase][2].  Using `ReleaseOnCancel` has been the plan since 2b81f47626 (#87).  I'm not clear on why it (sometimes?) doesn't work today.
The discrepancy between the "exit after 2s no matter what" comment and the 5s `After` dates back to dbedb7accb (#179), which bumped the `After` from 2s to 5s, but forgot to bump the …

Bug 1843505: pkg/start: Release leader lease on graceful shutdown

---

Dockerfile.rhel
Dockerfile.rhel7

So we don't have a nominally-rhel7 Dockerfile building RHEL 8 images and also so we don't need to manually bump this filename when we bump RHEL versions.

Bug 1872080: Dockerfile.rhel: Use a RHEL-version-agnostic filename

---

bootstrap/bootstrap-pod.yaml
install/0000_00_cluster-version-operator_03_deployment.yaml

To pick up all the `.V(5)` logging in `pkg/cvo/sync_worker.go`.  I'm especially interested in the main select loop in `SyncWorker.Start`, because we have one recent cluster where the sync worker loop [apparently goes to sleep][1] for no clear reason.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1873900

Bug 1873900: install/0000_00_cluster-version-operator_03_deployment: Bump to --v=5

---

pkg/cvo/sync_worker.go

To make it easier to debug situations where the CVO's `Operator.sync` logs:
Desired version from spec is ...
but the sync worker itself doesn't seem to pick up the update (like [this][1] and [this][2]).
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1843505#c19
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=1873900

Bug 1873900: pkg/cvo/sync_worker: Grow logging in SyncWorker.Update

---

hack/cluster-version-util/task_graph.go
lib/resourcebuilder/interface.go
pkg/cvo/cvo.go
pkg/cvo/cvo_scenarios_test.go
pkg/cvo/internal/operatorstatus.go
pkg/cvo/sync_worker.go
pkg/cvo/testdata/payloadtest/release-manifests/0000_20_a_exclude.yml
pkg/payload/payload.go
pkg/payload/payload_test.go
pkg/payload/task_graph_test.go

Backport of https://github.com/openshift/cluster-version-operator/pull/370

Bug 1841239: Avoid pre-creating clusteroperators that should be excluded

---

Dockerfile.rhel

ART is [waffling][1] around the 1.14 <-> 1.15 transition, but we don't need to wait.  Let the future start today!
Replaces #456, but without the commit message `to mach` typo or the bogus link to an ocp-build-data branch where the CVO is currently reverted back to Go 1.14.
[1]: https://github.com/openshift/ocp-build-data/pull/665

Bug 1878163: Dockerfile.rhel: Bump to Go 1.15

---

pkg/payload/task_graph.go
pkg/payload/task_graph_test.go

Before 55ef3d3027 (#264, new in 4.6), `RunGraph` had a separate goroutine that managed the work queue, with results fed into `errCh` to be collected by the main `RunGraph` goroutine.  It didn't matter if that work queue goroutine hung; as long as all the worker goroutines exited, `RunGraph` would collect their errors from `errCh` and return.  In 55ef3d3027, I removed the queue goroutine and moved queue management into the main `RunGraph` goroutine.  With that change, we became exposed to the following race:
1. Main goroutine pushes work into `workCh`.
2. Context canceled.
3. Workers exit via the `Canceled worker...` case, so they don't pick the work out of `workCh`.
4. Main goroutine deadlocks because there is work in flight, but nothing in `resultCh`, and no longer any workers to feed …

Bug 1873900: pkg/payload/task_graph: Avoid deadlocking on cancel with workCh queue

---

Dockerfile

Bug 1884209: Moving the go version to 1.15 as the Dockerfile.rhel already on it

---

docs/user/status.md
pkg/cvo/status.go

Similar to #422, further tune things up so that we can ensure that
our 90th percentile of clusters do not trip over momentary cluster
upgrade failures whenever operators take longer than 20 minutes to
roll out.

Bug 1884334: pkv/cvo/status: Raise Operator leveling grace-period to 40 minutes

---

Dockerfile.rhel

Updating cluster-version-operator builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/cluster-version-operator.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.

Updating cluster-version-operator builder & base images to be consistent with ART

---

pkg/cvo/sync_worker.go

This line is descended from logging we grew way back in 847f71bcef (#14).  But we triggered it recently with 88c222c954 (#448).  Drop the line, because it's noisy spew in the log files, and we can get the manifest content via:
```console
$ oc adm release extract --to=manifests $PULLSPEC
```

Bug 1886900: pkg/cvo/sync_worker: Drop "Manifest: ..." logging

---

pkg/cvo/sync_worker.go

This line is descended from 961873d66a (#82).  But we triggered it recently with 88c222c954 (#448).  Drop the line, because it's noisy spew in the log files, with all of the small "fraction-completed" bumps:
```console
$ grep -c 'sync_worker.go:.*Status change' namespaces/openshift-cluster-version/pods/cluster-version-operator-*/cluster-version-operator/cluster-version-operator/logs/current.log6265
$ grep 'sync_worker.go:.*Status change' namespaces/openshift-cluster-version/pods/cluster-version-operator-*/cluster-version-operator/cluster-version-operator/logs/current.log | tail -n4
2020-10-09T18:21:53.523398340Z I1009 18:21:53.522733       1 sync_worker.go:458] Status change cvo.SyncWorkerStatus{Generation:1, Step:"ApplyResources", Failure:error(nil), Fraction:0.9936, Completed:0, …
```

Bug 1886900: pkg/cvo/sync_worker: Demote "Status change: ..." logging to v6

---

hack/log-explainer.py

Avoid crashing on undefined `sync` if someone pushes in logs from a pod that has been running for so long that we no longer have the lines that start the opening sync.  Instead, just throw that partially-logged sync out.

hack/log-explainer: Don't crash if run on truncated logs

---

pkg/cvo/metrics.go

Apparently there's something in the HTTPS server goroutine that can hang up even if we've called `Shutdown()` on the server.  Defend against that with a safety valve to abandon stuck goroutines if `shutdownContext` expires.
Also pivot to `resultChannel` and `asyncResult`, so we can get names for the collected channels (and more easily identify the stuck channels by elimination), following the pattern set by cc1921d186 (#424).
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1891143#c1

Bug 1891143: pkg/cvo/metrics: Abandon child goroutines after shutdownContext expires

---

docs/dev/clusteroperator.md

It looks like that a small portion of the documentation was not yet updated due the changes introduced in https://github.com/openshift/cluster-version-operator/pull/318. Thanks @sdodson for pointing it out

Doc fix for cluster operator creation step

---

docs/dev/clusteroperator.md

This snuck in with be09d1e4d3 (#478).
Re: "or recreate if deleted", the CVO (if it is running) will eventually get around to recreating the ClusterOperator, as described in the text added in be09d1e4d3.  But it's still the operator's job to recreate it if the ClusterOperator is missing, as part of the "properly update" responsibility.

docs/dev/clusteroperator: Fix "he" -> "the" typo

---

pkg/payload/payload.go
pkg/payload/render.go

This allows future CVO manifests to use {{ .ClusterProfile }}.
Example, futur CVO might look like:
```
apiVersion: v1
kind: Pod
metadata:
name: bootstrap-cluster-version-operator
namespace: openshift-cluster-version
...
env:
- name: CLUSTER_PROFILE
value: "{{.ClusterProfile}}"
```
This implements phase 1 of https://github.com/openshift/enhancements/pull/543.
Default value is the one decided in https://github.com/openshift/enhancements/pull/510

Add ClusterProfile template variable

---

pkg/cvo/sync_worker.go

Using the installer, if a cluster operator is in overrides list, it is
still created during the precreation step.
When both the cluster operator and the deployment of an operator are
overridden, the CVO (and the installer) waits for ever the end of the
end of the provisioning.
---
I faced this when I tried to disable monitoring for CRC
```
I1210 20:28:04.418715       1 sync_worker.go:687] Precreated resource clusteroperator "monitoring" (317 of 617)
I1210 20:28:32.633406       1 sync_worker.go:701] Running sync for clusteroperator "monitoring" (317 of 617)
I1210 20:28:32.633423       1 sync_worker.go:705] Skipping clusteroperator "monitoring" (317 of 617) as unmanaged
```
It means that we can't disable fully an operator with overrides. It has to be deployed once.

Bug 1907313: Don't create ClusterOperator during precreation step if it's present in overrides

---

pkg/cvo/availableupdates.go
pkg/cvo/cvo.go
pkg/cvo/sync_worker.go
pkg/cvo/sync_worker_test.go

Fixing [rbhz#1879976][1], where clusters installed with pullspecs like:
registry.svc.ci.openshift.org/ocp/release@sha256:c7e8f18e8116356701bd23ae3a23fb9892dd5ea66c8300662ef30563d7104f39
would not pick up channel metadata that Cincinnati was associating with canonical pullspecs like:
quay.io/openshift-release-dev/ocp-release@sha256:c7e8f18e8116356701bd23ae3a23fb9892dd5ea66c8300662ef30563d7104f39
I really wish source-repo "hints" were not part of pullspecs, and these images were purely content-addressable.  But wishing doesn't make it true ;).
I'm not using the new `equalDigest` for some of our "is this change an update?" logic, because [we want to go through "updates" on repository changes][2] to ensure that the release content is still available when accessed via the new pullspec …

Bug 1879976: pkg/cvo: Compare Cincinnati data by digest when merging metadata

---

pkg/cvo/updatepayload.go

When '--force' is specified for an update, create new context with reduced timeout for use in signature verification to allow time to perform update.
The currently used context's timeout is set by SyncWorker Start based on an initial interval of 2  to ~4 minutes modified based on work.State and can therefore range from 2 to ~8 minutes. My testing found that during verify payload it had a 5 to 6 minute deadline. I therefore created a child context with a timeout of half that value when `--force` is specified.

Bug 1906100: use child context to verify payload signature on forced update

---

Dockerfile
Dockerfile.rhel
README.md
docs/dev/clusterversion.md
docs/dev/operators.md
docs/user/reconciliation.md

The canonical registry URI has been updated, see openshift/release@f6ac0408e0 (openshift/release#14726) and similar.  Generated with:
```console
$ sed -i 's/registry.svc.ci.openshift.org/registry.ci.openshift.org/g' $(git grep -l registry.svc.ci.openshift.org)
```
Replacing #495.

*: Replace registry.svc.ci.openshift.org with registry.ci.openshift.org

---

pkg/cvo/cvo_scenarios_test.go
pkg/cvo/cvo_test.go
pkg/cvo/status.go
pkg/cvo/sync_worker.go
pkg/cvo/sync_worker_test.go

Make Done and Total available to syncStatus and calculate percent complete locally. Use `math.Trunc` to avoid rounding which occurs when only `%.0f` is used. This can also cause us to display 100% complete when `Done != Total`.
Also dropped pkg/cvo/cvo_scenarios_test.go's use of diff.ObjectReflectDiff.  Method was causing a panic and is also deprecated in favor of cmp.Diff. cmp.Diff does not print out difference so simply logged expected and actual values instead.

Bug 1768255: replace Fraction with Done and Total

---

pkg/payload/task_graph.go

Our graph has some nodes without tasks, e.g. nodes which create a choke point between two sets of parallel nodes.  Ideally we give all nodes descriptive names (#435), but until we have that, require at least one entry in `Tasks` before we store a node as `firstIncompleteNode`.
This avoids the chance of panicking during the subsequent:
```go
fmt.Errorf("%d incomplete task nodes, beginning with %s", incompleteCount, firstIncompleteNode.Tasks[0])
```

Bug 1903382: pkg/payload/task_graph: Require firstIncompleteNode to have tasks

---

pkg/cvo/cvo_scenarios_test.go
pkg/cvo/internal/operatorstatus.go
pkg/cvo/internal/operatorstatus_test.go
pkg/cvo/status.go
pkg/cvo/sync_worker.go
pkg/payload/task.go

Currently during an upgrade the cluster will be marked as failing when an operator is still updating but not necessarily failing. Add the ability to set whether a given cluster operator error should result in the cluster being set to failing.
The bool  `UpgradeSucceeding` was added to the `UpdateError` structure to indicate whether the error should result in `Failing=True`. The name was chosen such that `!UpgradeSucceeding== Failing`. In this way  the default for a given error is that it results in the cluster being marked as failing and explicit action must be taken by a developer, for example when a new `UpdateError` is added, to determine and set the error such that the cluster is not marked as failing. I chose to stick with a new field in `UpdateError` as opposed to an `UpdateError` …

Bug 1884334: UpdateError: enhance for ability to determine when upgrade failing

---

pkg/cvo/cvo.go
pkg/start/start.go

Address a bug introduced by cc1921d186 (#424), where canceling the `Operator.Run` context would leave the operator with [no time to attempt the final sync][1]:
E0119 22:24:15.924216       1 cvo.go:344] unable to perform final sync: context canceled
With this commit, I'm piping through `shutdownContext`, which gets a two-minute grace period beyond runContext, to give the operator time to push out that final status (which may include important information like the fact that the incoming release image has completed verification).
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1916384#c10

Bug 1916384: pkg/cvo: Use shutdownContext for final status synchronization

---

pkg/cvo/cvo.go

Builds on #501; possibly review that first.
In [rbhz#1921413][1], we had a CVO fail to gracefully release the leader lock, with:
```console
$ grep start.go: namespaces/openshift-cluster-version/pods/cluster-version-operator-968d9fd48-25zkz/cluster-version-operator/cluster-version-operator/logs/current.log
2021-01-26T19:02:48.678276895Z I0126 19:02:48.678120       1 start.go:21] ClusterVersionOperator 4.6.0-202012050130.p0-39a4256
2021-01-26T19:02:49.273117163Z I0126 19:02:49.273074       1 start.go:260] Waiting on 2 outstanding goroutines.
2021-01-26T19:02:49.273512006Z E0126 19:02:49.273474       1 start.go:271] Collected metrics server goroutine: listen tcp 0.0.0.0:9099: bind: address already in use
2021-01-26T19:02:49.273587622Z I0126 19:02:49.273551       1 start.go:260] Waiting on 1 …
```

Bug 1921413: pkg/cvo/cvo: Guard Operator.Run goroutine handling from early cancels

---

install/0000_90_cluster-version-operator_02_servicemonitor.yaml

SRE-P has commited to feed findings and changes in regards to alerts back to upstream, this change is a follow up to https://issues.redhat.com/browse/OSD-6327
We are obeying the following standards for alert levels and recommend every component team to do so to:
```
Critical: An issue, that needs to page a person to take instant action
Warning: An issue, that needs to be worked on but in the regular work queue or for during office hours rather than paging the oncall
Info: Is meant to support a trouble shooting process by informing about a non-normal situation for one or more systems but not worth a page or ticket on its own.
```
[reference](https://github.com/kubernetes-monitoring/kubernetes-mixin#alert-severities)
This therefore is a `warning` level alert. No one should be paged for it …

Bug 1926310: install/0000_90_cluster-version-operator_02_servicemonitor.yaml: adjust "CannotRetrieveUpdates" to "warning"

---

pkg/cvo/cvo_scenarios_test.go
pkg/cvo/sync_worker.go

If, for example, the configured ClusterVersion `spec.upstream` advertised a given image as 4.0.1, but the version baked into the release's own metadata was 1.0.0-abc, report VerifyPayloadVersionFailed and continue to apply the previous release image, instead of optimistically moving on to apply the new release image.  This protects users from compromised or man-in-the-middled upstreams who attempt downgrade and similar attacks by misrepresenting a recommended update.
Addressing a FIXME from 58356deee6 (#419).

pkg/cvo/sync_worker: Make expected/actual version mismatch fatal

---

pkg/cvo/metrics.go

Following cc1921d186 (#424), which logs overall shutdown in `cmd/start.go`, this commit will make it extremely clear in the CVO logs when the metrics goroutine is wrapping up.

pkg/cvo/metrics: Log metrics-server shutdown

---

pkg/cvo/upgradeable.go

Fixing a typo from 04528144fe (#243).
Generated with:
```console
$ sed -i 's/Upgradebale/Upgradeable/g' $(git grep -l Upgradebale)
```
No rush; we can land this after 4.6 forks off and master reopens.

pkg/cvo/upgradeable: Fix "Upgradebale" -> "Upgradeable"

---

pkg/start/start.go

a9e075a79d (#508) made us more robust to situations where we are canceled after acquiring the leader lock but before we got into `Operator.Run`'s `UntilWithContext`.  However, there was [still a bug][1] from cc1921d186 (#424) where we had not acquired the leader lock.  `postMainContext` is used for metrics, informers, and the leader election loop.  We used to only call `postMainCancel` after reaping the main goroutine, and obviously that will only work if we've launched the main goroutine.  This commit adds a new `launchedMain` to track that.  If `launchedMain` is true, we get the old handling.  If `launchedMain` is still false when `runContext.Done`, we now call `postMainCancel` without waiting to reap a non-existent main goroutine.
There's also a new `postMainCancel` when the shutdown …

Bug 1927944: pkg/start: Fix shutdown deadlock when die before getting a leader lock

---

pkg/cvo/cvo.go
pkg/cvo/status.go

This is temporary logging to help debug an issue during CI testing. Most if not all will be removed once the issue has been identified.

pkg/cvo: Add logging to track ClusterVersion

---

pkg/start/start.go

Backporting #519, which we need in 4.7 in addition to #508, which landed in master before 4.7 forked off.

Bug 1921413: pkg/start: Fix shutdown deadlock when die before getting a leader lock

---

pkg/cvo/cvo.go
pkg/start/start.go

This commit picks c4ddf03bec (#517) back to 4.5.  It's not a clean pick, because we're missing changes like:
* b72e843974 (Bug 1822844: Block z level upgrades if ClusterVersionOverridesSet set, 2020-04-30, #364).
* 1d1de3ba1a (Use context to add timeout to cincinnati HTTP request, 2019-01-15, #410).
which also touched these lines.  But we've gotten this far without backporting rhbz#1822844, and #410 was never associated with a bug in the first place, so instead of pulling back more of 4.6 to get a clean pick, I've just manually reconciled the pick conflicts.
/assign @jottofar

Bug 1931025: pkg/cvo: Use shutdownContext for final status synchronization

---

bootstrap/bootstrap-pod.yaml
cmd/render.go
install/0000_00_cluster-version-operator_03_deployment.yaml
pkg/payload/payload.go
pkg/payload/render.go

This also propagates the CLUSTER_PROFILE to the next generation of CVO
---
This is the final part of cluster profile. Now that 4.7 CVOs know about this new {{ .ClusterProfile }} template variable. We can use it. 
Tested with registry.svc.ci.openshift.org/ocp/release:4.8.0-0.ci-2021-02-17-015150 + single-node-developer profile, works great!

Use profile from the installer to render CVO manifests

---

pkg/cvo/internal/operatorstatus.go
pkg/cvo/internal/operatorstatus_test.go

to a different message for cluster operators that are available, not degraded, but not yet finished updating

pkg/cvo/internal/operatorstatus: Change nested message

---

pkg/cvo/sync_worker.go

This is a hack fix for [rhbz#1929917][1], where we have a delay on 4.6->4.7 updates, and on some 4.7 installs, between the very early ClusterOperator precreation and the operator eventually coming up to set its status conditions.  In the interim, there are no conditions, which causes `cluster_operator_up` to be 0, which causes the `critical` `ClusterOperatorDown` to fire.  We'll want a more general fix going forward, this commit is a temporary hack to avoid firing the critical `ClusterOperatorDown` while we build consensus around the general fix.
The downside to dropping precreates for this operator is that we lose the must-gather references when the operator fails to come up.  That was what precreation was designed to address in 2a469e37c1 (#318).  If we actually get a must-gather …

Bug 1929917: pkg/cvo/sync_worker: Skip precreation of baremetal ClusterOperator

---

pkg/cvo/metrics.go

We have been excluding `Unknown` since the metric landed in 8b9118992d (#45).  But operators could do crazy things like setting `status: Muahaha`, and we don't want to collapse them all into the `False`/`0` case.  We could enumerate the known statuses (e.g. using 2 for `Unknown`), but that would probably not play well with existing queries, and `Unknown` is hopefully not too popular.

pkg/cvo/metrics: Exclude unrecognized statuses from cluster_operator_conditions

---

pkg/cvo/metrics.go
pkg/start/start.go

We'll get a CI error if installer metric is generated with either `type` or `invoker` set to "". Fix possible race condition whereby informers are not yet sync'ed before metrics are served which results in an API IsNotFound error.

Bug 1871303: metrics: serve metrics after leader lock acquired

---

lib/resourceapply/core.go
lib/resourcemerge/core.go

Currently, if you were to change the value of the service account `automountServiceAccountToken` field between versions of openshift, CVO will not update it, it only updates metadata.
With this fix, it will now also set the `automountServiceAccountToken` to the value specified in the service account yaml in the manifests.

Bug 1938947: Ensure automountServiceAccountToken is synced on service account updates

---

bootstrap/bootstrap-pod.yaml
install/0000_00_cluster-version-operator_03_deployment.yaml

To pick up all the .V(5) logging in pkg/cvo/sync_worker.go.  I'm
especially interested in syncStatus logging that logs Generation
to help debug issue [1].
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1915559

Bug 1940652: Bump logging to --v=5

---

lib/resourcemerge/rbac.go
lib/resourcemerge/rbacv1beta1.go

This wasn't covered when ClusterRole reconciliation landed in 697cbf6370 (#10), but the property existed even back then:
```console
$ git grep -A20 'type ClusterRole struct' 697cbf6370 | grep '[-][[:space:]]Aggrega
tionRule'
697cbf6370:vendor/k8s.io/api/rbac/v1/types.go-  AggregationRule *AggregationRule `json:"aggregationRule,omitempty" protobuf:"bytes,3,opt,name=aggregationRule"`
697cbf6370:vendor/k8s.io/api/rbac/v1alpha1/types.go-    AggregationRule *AggregationRule `json:"aggregationRule,omitempty" protobuf:"bytes,3,opt,name=aggregationRule"`
697cbf6370:vendor/k8s.io/api/rbac/v1beta1/types.go-     AggregationRule *AggregationRule `json:"aggregationRule,omitempty" protobuf:"bytes,3,opt,name=aggregationRule"`
```
and now folks want to use `aggregationRule` for something: …

lib/resourcemerge/rbac: Reconcile ClusterRole.AggregationRule

---

docs/user/reconciliation.md
pkg/cvo/internal/operatorstatus.go
pkg/cvo/internal/operatorstatus_test.go
pkg/cvo/metrics.go
pkg/cvo/metrics_test.go

Also simplify the `undone` type from a map to a slice of strings.  The only consumers are length checks and `nestedMessage` formatting, so we don't need to preserve structured access to the current and expected values.
I've also dropped the old, early "Cluster operator %s is still updating" guard.  If the ClusterOperator is degraded or unavailable, those are much more serious than being behind in version, so we want those guards coming first.  The undone guard is now only the final fallback for available, non-degraded operators that aren't completely satisfactory (and I've pivoted to use `ClusterOperatorUpdating` for that reason).
I'm also now keeping any available condition data, and including that status, reason, and message in the nested message, because it seemed strange to do that …

pkg/cvo/internal/operatorstatus: Drop deprecated failing/progressing handling

---

pkg/cvo/sync_worker.go

Picking #534 back to release-4.6 manually, because 4.6 doesn't include #488.

Bug 1943973: pkg/cvo/sync_worker: Skip precreation of baremetal ClusterOperator

---

install/0000_00_cluster-version-operator_00_namespace.yaml
install/0000_00_cluster-version-operator_03_deployment.yaml

In support of the workload partitioning feature
(openshift/enhancements#703), we need to add
annotations to all management pods and namespaces so they can be
properly identified and assigned to segregated management cores on
clusters configured to do so.
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

Add management workload annotations

---

lib/resourcebuilder/apps.go
lib/resourcemerge/core.go

And also fail on Deployments that set [`ProgressDeadlineExceeded`][1].  More background in the commit messages, but these two changes should address both points from [rhbz#1951339][2].
[1]: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#failed-deployment
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=1951339

Bug 1951339: lib/resourcemerge/core: Clear env and envFrom if unset in manifest

---

install/0000_00_cluster-version-operator_03_deployment.yaml

As per openshift/enhancements#739, the workload annotations names are changing.
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>
/hold
Hold until after openshift/kubernetes#632 is merged

Rename workload annotations

---

install/0000_90_cluster-version-operator_02_servicemonitor.yaml
pkg/cvo/metrics.go
pkg/cvo/metrics_test.go

`ClusterOperatorDown` is based on `cluster_operator_up`, but we also have `ClusterOperatorDegraded` based on `cluster_operator_conditions{condition="Degraded"}`.  Firing `ClusterOperatorDown` for operators which are `Available=True` and `Degraded=True` [confuses users][1].  `ClusterOperatorDegraded` will also be firing.  With this commit, I'm adjusting `cluster_operator_up` to only care about `Available`, to decouple the two alerts and bring them in line with their existing "has not been available" and "has been degraded" descriptions.
However, `IsOperatorStatusConditionTrue` requires the condition to be present, and `cluster_operator_conditions` only creates entries when the conditions are present.  To guard against the Degraded-unset condition in `ClusterOperatorDegraded`, I'm covering …

Bug 1834551: pkg/cvo/metrics: Ignore Degraded for cluster_operator_up

---

install/0000_90_cluster-version-operator_02_servicemonitor.yaml

During install, the CVO has pushed manifests into the cluster as fast as possible without blocking on "has the in-cluster resource leveled?" since way back in b0b4902fce (#136).  That can lead to `ClusterOperatorDown` and `ClusterOperatorDegraded` firing during install, as we see [here][1], where:
* [ClusterOperatorDegraded started pending at 5:00:15Z][2] (`group by (alertstate) (ALERTS{alertname="ClusterOperatorDegraded"})`.
* [Install completed at 5:09:58Z][3].
* [ClusterOperatorDegraded started firing at 5:10:04Z][2].
* [ClusterOperatorDegraded stopped firing at 5:10:23Z][2].
* [The e2e suite][1] complained about:
alert ClusterOperatorDegraded fired for 15 seconds with labels: {... name="authentication"...} (open bug: https://bugzilla.redhat.com/show_bug.cgi?id=1939580) …

Bug 1957991: install/0000_90_cluster-version-operator_02_servicemonitor: Soften ClusterOperatorDegraded

---

pkg/cvo/sync_worker.go

ClusterOperator pre-creation landed in 2a469e37c1 (#318) to move us from:
1. CVO creates a namespace for an operator.
2. CVO creates ... for the operator.
3. CVO creates the operator Deployment.
4. Operator deployment never comes up, for whatever reason.
5. Admin must-gathers.
6. Must gather uses ClusterOperators for discovering important stuff, and because the ClusterOperator doesn't exist yet, we get no data about why the deployment didn't come up.
to:
1. CVO pre-creates ClusterOperator for an operator.
2. CVO creates the namespace for an operator.
3. CVO creates ... for the operator.
4. CVO creates the operator Deployment.
5. Operator deployment never comes up, for whatever reason.
6. Admin must-gathers.
7. Must gather uses ClusterOperators for discovering important stuff, and finds …

Bug 1957775: pkg/cvo/sync_worker: Shift ClusterOperator pre-creation into the manifest-task node

---

install/0000_90_cluster-version-operator_02_servicemonitor.yaml

Catching up with fb5257d4be (#554).

Bug 1957991: install/0000_90_cluster-version-operator_02_servicemonitor: Update ClusterOperatorDegraded message to 30m

---

lib/resourceapply/core.go
lib/resourcemerge/core.go
lib/resourcemerge/core_test.go

Previously ServiceType was simply checked for equality resulting in CVO hot looping trying to clear ServiceType field that server continuously defaults. Added EnsureServiceType that will only check field equality if the field has been set. If field has not been set  EnsureServiceType ensures the in-cluster object's ServiceType is set to the default "ClusterIP".

Bug 1881481: Only compare ServiceType when set in manifest

---

pkg/cvo/internal/operatorstatus.go
pkg/cvo/internal/operatorstatus_test.go

Like cc9292a061 (#400), but for ClusterOperator.  In that commit message, I'd explain that we'd continue on past imperfect (e.g. Progressing=True) but still happy-enough Deployments and such and later block on the ClusterOperator.  But there's really no need to poll the ClusterOperator while we're blocked on it; we can instead fail that sync loop, take the short cool-off break, and come in again with a new pass at the sync cycle.
This will help reduce delays like [rhbz#1927168][1] where a good chunk of the ~5.5 minute delay was waiting for the network ClusterOperator to become happy.  If instead we give up on that sync cycle and start in again with a fresh sync cycle, we would have been more likely to recreate the ServiceMonitors CRD more quickly.
The downside is that we will now complain …

Bug 1927168: pkg/cvo/internal/operatorstatus: Replace wait-for with single-shot "is it alive now?"

---

Dockerfile
Dockerfile.rhel

Catching up with openshift/ocp-build-data@e3b61ff1dde2b.  Generated with:
```console
$ sed -i 's/golang-1.15/golang-1.16/g' $(git grep -l golang-1.15)
```
Replaces #535.
[1]: https://github.com/openshift/ocp-build-data/commit/e3b61ff1dde2bfc2bc7f2b5efdd155d1d3299cd7

Dockerfile*: Bump to Go 1.16

---

lib/resourcemerge/rbac.go
lib/resourcemerge/rbac_test.go

`EnsureRoleBinding` and `EnsureClusterRoleBinding` expect `RoleRefs` to be identical. Some manifests are skipping `APIGroup`, so CVO keeps attempting to apply those on every sync.
This PR adds `CompareRoleRefsv1`/`CompareRoleRefsv1beta1` functions, which return true ("identical") if required APIGroup is empty and existing APIGroup is "rbac.authorization.k8s.io"
TODO:

Bug 1881520: avoid hotlooping on RoleBindings with empty APIGroup

---

lib/resourcemerge/core.go
lib/resourcemerge/core_test.go

`TargetPort` is not being set in some required manifests, but returned by API server

Bug 1881481: TargetPort should default to port in ServicePort if unset

---

pkg/cvo/sync_worker.go

Avoid situations [like][1]:
```console
$ grep 'Running sync.*in state\|Result of work' cvo.log | tail -n4
I0517 11:30:37.342895       1 sync_worker.go:549] Running sync 4.8.0-0.nightly-2021-05-15-141455 (force=false) on generation 1 in state Reconciling at attempt 0
I0517 11:36:19.258793       1 task_graph.go:555] Result of work: [Could not update servicemonitor "openshift-machine-api/cluster-autoscaler-operator" (255 of 676): the server does not recognize this resource, check extension API servers Could not update servicemonitor "openshift-kube-apiserver-operator/kube-apiserver-operator" (627 of 676): the server does not recognize this resource, check extension API servers update context deadline exceeded at 28 of 676 update context deadline exceeded at 28 of 676]
I0517 11:39:38.268693 …
```

Bug 1927168: pkg/cvo/sync_worker: Increment Attempt on failed reconciliation

---

pkg/cvo/updatepayload.go

Avoid [failing][1]:
[sig-arch] Managed cluster should ensure platform components have system-* priority class associated [Suite:openshift/conformance/parallel]
by setting the property.  From [our conventions][2], `openshift-user-critical` means it is fine for this workload to be preempted by user-workload and OOMKilled.  If we have such dire resource constraints that the version pod gets evicted, it's probably not a good time to be kicking off an update with all of its associated control-plane churn.
[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.8-e2e-aws-upgrade-rollback/1395138552144072704
[2]: https://github.com/openshift/enhancements/blob/fe578535d5e6a126a10bb26830b7755266d0f92e/CONVENTIONS.md#priority-classes

Bug 1962882: pkg/cvo/updatepayload: Set priorityClassName for the version Job

---

docs/dev/clusterversion.md

The example of how to make an operator unmanaged makes assumptions that probably haven't been true since 4.1. The _idea_ is still right, but the specifics of it are all wrong...

Update a doc example to match modern OCP

---

lib/resourcemerge/core.go
lib/resourcemerge/core_test.go

As described in [rhbz#1941901][1], the old logic matching on key could lead to later required entries clobbering earlier ones if the keys matched.  Personally, I'd rather just force an exact match here, but that's blocked on gathering sufficient data from the wild to know we wouldn't be clobbering some important admin-added toleration ([rhbz#1942271][2]).  This commit pivots us to at least requiring all manifest tolerations being present in-cluster, althought it does not remove additional admin-added tolerations.  The most important benefit is that previously-key-match-clobbered manifest tolerations will be restored.  A secondary benefit is that it will reduce one source of potential hotloop behavior ([rhbz#1881484][3], #559).
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1941901#c0 …

Bug 1941901: lib/resourcemerge/core: Fix toleration matching logic

---

lib/resourcemerge/apps_test.go
lib/resourcemerge/batch_test.go
lib/resourcemerge/core.go
lib/resourcemerge/core_test.go

Mostly followed kube defaulting logic however with some exceptions:
-  Currently only CVO deployment uses "KUBERNETES_SERVICE_HOST" env variable to inject internal LB host.This may result in an IP address being returned by API so always assuming returned value is okay.
-  Toleration keys can be duplicated and are so in CVO (see [Bug 1941901](https://bugzilla.redhat.com/show_bug.cgi?id=1941901)) so needed to change logic to not simply exit when first matched key found possibly incorrectly overwrite the wrong key's value.
Also added VolumeSource defaulting in its entirety even though some are not currently used to avoid future hot looping issues.

Bug 1881484: Set defaults in deployment

---

install/0000_00_cluster-version-operator_03_deployment.yaml

In an upgrade scenario:
1. a kube apiserver updates, any pod request that passes its admission
is injected with SA projected volume
2. OpenShift adds a configMap "openshift-service-ca.crt" among the
volume sources to the projected volume
3. Any pod that gets created now will be stuck until an updated
version of KCM gets started
4. If CVO pod gets deleted at this point, the whole upgrade might
get stuck
Prevent the deadlock by manually configuring the projected volume.
This can be removed in 4.9 when even the older KCM contains the code
creating the openshift-service-ca.crt CMs.

Bug 1946479: prevent pod deployment deadlock due to custom SA projected volume injection

---

lib/resourceapply/apiext.go
lib/resourceapply/apireg.go
lib/resourceapply/apps.go
lib/resourceapply/batch.go
lib/resourceapply/core.go
lib/resourceapply/cv.go
lib/resourceapply/rbac.go
lib/resourceapply/security.go
pkg/cvo/internal/generic.go

Show when object gets created or updated with diff

Bug 1879184: Log object updates and show existing/required diff

---

install/0000_90_cluster-version-operator_02_servicemonitor.yaml

This pull request brings back fb5257d4be (#554) and 92ed7f110c (#556).  There are some conflicts, because I am not bringing back 90539f9a17 (#550).  But that one [had its own conflicts in `metrics.go`][5], and the conflicts with this commit were orthogonal context issues, so moving this back to 4.7 first won't make it much harder to bring back #550 and such later on, if we decide to do that.
[5]: https://github.com/openshift/cluster-version-operator/pull/550#issuecomment-856815344

Bug 1969501: install/0000_90_cluster-version-operator_02_servicemonitor: Soften ClusterOperatorDegraded

---

lib/resourcebuilder/podspec.go
lib/resourcebuilder/podspec_test.go

The init containers where not be correctly initialized with the service host and port. Also fixed tests.

Correctly initialize service host and port when environment is missing

---

README.md

Update the README.md and update the hyperlink that points to the `Using CVO to render the release-image locally` header.

README: Update the link to the rendering release image locally header

---

pkg/cvo/sync_worker.go

Increase readability of comparison between `*SyncWork` references.

Simplify the comparison between SyncWork references

---

install/0000_00_cluster-version-operator_03_deployment.yaml

This reverts commit 9bde7bb89677fe166303c040d220b763c3291234, #585.
It was a temporary workaround in 4.8 to bridge a gap between Kube-API-server and Kube-controller-manager during 4.7 -> 4.8 updates. Once the cluster has reconciled 4.8, we will no longer need the crutch.  And 4.8 has now forked off master, so we can revert now, and that revert will go out in 4.9.

Revert "prevent pod deployment deadlock due to custom SA projected volume injection"

---

install/0000_90_cluster-version-operator_02_servicemonitor.yaml

Catching up with upstream's move from `message`, as documented [here][1].
[1]: https://github.com/monitoring-mixins/docs/pull/10/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R183

install/0000_90_cluster-version-operator_02_servicemonitor: Alert summary/descriptions

---

pkg/cvo/cvo_scenarios_test.go

The fake client for the CVO scenarios test uses a switch-case statement to compare the received `Action` pointer type to interfaces for update-action, create-action and get-action. However in go when two interfaces have the same definition(same functions) a concrete type can match against both of them. And because `clientgotesting.CreateAction` and `clientgotesting.UpdateAction` are basically the same interface the action always matched against the first interface. In this case the `CreateAction`. So the `ClusterVersion` object was always recreated and the `ResourceVersion` and `Generation` fields in the result object were reset all the time.
I have fixed the above issue by using the actual structs `CreateActionImpl`, `UpdateActionImpl` and `GetActionImpl` in the switch-case. This means …

Fixed fake client for CVO scenarios test

---

docs/dev/object-deletion.md
docs/dev/operators.md
lib/resourcebuilder/resourcebuilder.go
lib/resourcedelete/apiext.go
lib/resourcedelete/apireg.go
lib/resourcedelete/apps.go
lib/resourcedelete/batch.go
lib/resourcedelete/core.go
lib/resourcedelete/helper.go
lib/resourcedelete/helper_test.go
lib/resourcedelete/rbac.go
lib/resourcedelete/security.go
pkg/cvo/internal/generic.go
pkg/cvo/upgradeable.go

The new manifest annotation will trigger new CVO delete logic, added by this PR, to delete the in-cluster object instead of creating/updating it. This will provide a more straightforward way for engineering to remove content.
See [Enhancement for adding a manifest annotation for object removal
#419](https://github.com/openshift/enhancements/pull/419) for implementation details.
Per the enhancement whenever object deletions are pending, one or more deletions have been requested but object removal has not completed, the cluster is blocked from upgrading to the next minor release (`Upgradeable==false`).
if an object previously removed reappears a warning is logged which meets what is specified by the enhancement. This does not result in `Upgradeable==false` and no attempt is made to remove …

OTA-222: Add a manifest annotation to be used for object deletion

---

.golangci.yaml
pkg/cvo/sync_worker.go
pkg/cvo/sync_worker_test.go

Depends on #598 and #597 
This [linter](https://github.com/dominikh/go-tools/tree/master/simple) looks for common non-idiomatic patterns in code which can be simplified.
Result from linter:
```
pkg/cvo/sync_worker_test.go:88:5       gosimple  S1000: should use a simple channel send/receive instead of `select` with a single case
pkg/cvo/sync_worker_test.go:102:5      gosimple  S1000: should use a simple channel send/receive instead of `select` with a single case
pkg/cvo/sync_worker_test.go:141:4      gosimple  S1000: should use a simple channel send/receive instead of `select` with a single case
pkg/cvo/cvo_scenarios_test.go:418:12   gosimple  S1039: unnecessary use of fmt.Sprintf
pkg/cvo/cvo_scenarios_test.go:1081:12  gosimple  S1039: unnecessary use of fmt.Sprintf …
```

Enable gosimple

---

.golangci.yaml
cmd/main.go
cmd/render.go
pkg/cvo/sync_test.go
pkg/payload/precondition/clusterversion/upgradable_test.go
pkg/start/start_integration_test.go

Depends on #598 
The [errcheck](https://github.com/kisielk/errcheck) linter ensures that all functions which return errors have their return value checked

Enable errcheck linter

---

.golangci.yaml
pkg/autoupdate/autoupdate.go
pkg/cvo/cvo.go

Depends on #598
The [structcheck](https://gitlab.com/opennota/check) linter finds unused fields in structs.

Enable structcheck

---

.golangci.yaml
pkg/cvo/cvo_test.go
pkg/cvo/status_test.go
pkg/cvo/sync_test.go

Depends on #598 #599
The [unused](https://github.com/dominikh/go-tools/tree/master/unused) linter finds unused constants, variable, types and functions. It detects some of the same stuff as `deadcode` but finds more types than it.

Enable unused

---

.golangci.yaml
pkg/cvo/cvo_test.go
pkg/cvo/internal/operatorstatus_test.go
pkg/cvo/status_test.go
pkg/cvo/sync_test.go

Depends on #598 
According to the [documentation](https://golang.org/cmd/vet/):
> Vet examines Go source code and reports suspicious constructs
Results from the linter:
```
pkg/cvo/cvo_test.go:702:100                    govet  composites: `k8s.io/apimachinery/pkg/apis/meta/v1.Time` composite literal uses unkeyed fields
pkg/cvo/cvo_test.go:2172:25                    govet  composites: `k8s.io/apimachinery/pkg/apis/meta/v1.Time` composite literal uses unkeyed fields
pkg/cvo/sync_test.go:70:42                     govet  composites: `k8s.io/apimachinery/pkg/runtime/schema.GroupVersionKind` composite literal uses unkeyed fields
pkg/cvo/sync_test.go:73:42                     govet  composites: `k8s.io/apimachinery/pkg/runtime/schema.GroupVersionKind` composite literal uses unkeyed fields …
```

Enable govet

---

.golangci.yaml
lib/resourcemerge/core_test.go

Depends on #598
[gofmt](https://golang.org/cmd/gofmt/) was already being used so this linter has not detected many issue. The only one detected is for the redundant type declaration.

Enable gofmt

---

.golangci.yaml
lib/resourcemerge/core.go
lib/validation/validation.go
pkg/cvo/cvo_test.go
pkg/cvo/internal/generic.go
pkg/cvo/internal/operatorstatus.go
pkg/cvo/sync_worker.go
pkg/payload/task_graph.go

Depends on #598
The [deadcode](https://github.com/remyoudompheng/go-misc/tree/master/deadcode) linter finds unused code.

Enable deadcode linter

---

.golangci.yaml
cmd/image.go
pkg/cvo/egress.go

Depends on #598 and #602
[staticcheck](https://github.com/dominikh/go-tools/tree/master/cmd/staticcheck) is a code analysis tool which detects common mistakes in go.

Enable staticcheck

---

lib/resourcedelete/helper_test.go
pkg/payload/precondition/precondition_test.go

Fixed linting issues with redundant type declaration and the use of `fmt.Sprintf()` when there is no string formatting required.

Fix more golangci-lint issues

---

install/0000_00_cluster-version-operator_03_deployment.yaml

Currently, the CVO tolerates the taint
'node.kubernetes.io/unschedulable'.  This is undersireable as it will
result in the pod potentially being rescheduled onto a cordoned host.
This commit removes this particular toleration from the CVO deployment
so we do not conflict with administrative drains.

Remove toleration of unschedulable

---

pkg/cvo/cvo.go
pkg/cvo/cvo_scenarios_test.go
pkg/cvo/cvo_test.go
pkg/cvo/sync_test.go
pkg/start/start_integration_test.go

The operator object no has a metadata modifier which injects an owner reference if there is no existing owner references. Also updates the ownerReference if it has been changed due to recreation

Added ownerReference to all objects created and managed by CVO

---

.golangci.yaml
lib/resourcebuilder/interface.go
pkg/cvo/internal/generic.go
pkg/cvo/metrics.go
pkg/cvo/sync_test.go
pkg/cvo/updatepayload.go

Enabled the misspell linter to catch spelling errors in comments. Also fixed other spelling errors in code.

Enable misspell linter

---

pkg/cvo/egress.go

Since 4.2's ea5e3bc86e (#219), the CVO has been loading proxy config from the `spec` property.  We should be loading from `status` instead, so we benefit from the network operator's validation.  Risk is small, because unlike some other in-cluster components, the CVO is unlikely to break things if it is temporarily consuming a broken proxy configuration.
This is similar to c9fab435c1 (#311), where we moved our trusted CA source from the user-configured ConfigMap to the network-operator-validated ConfigMap.

Bug 1978774: pkg/cvo/egress: Load HTTPS proxy from Proxy status

---

pkg/autoupdate/autoupdate.go

The `wait.UntilWithContext` will repeatedly run the function passed to it
till the context also passed to it is done. At which point it will
return. Adding a wait group after the UntilWithContext ensures that
the top level goroutine does not return till all the spawned goroutines
terminate.

Added waitgroups for autoupdate workers to complete before stopping

---

lib/resourcebuilder/batch.go

When a job pod fails because kubelet is unable to pull the image, the pod is never considered *active* and subsequently after timing out it is never considered as `Failed` and the `Failed` count in the job status is never incremented.

Bug 1970421: Do not check if Job has Failed count set

---

lib/resourceapply/apiext.go
lib/resourceapply/apps.go
lib/resourceapply/batch.go
lib/resourceapply/core.go
lib/resourceapply/cv.go
lib/resourceapply/imagestream.go
lib/resourceapply/rbac.go
lib/resourceapply/security.go
lib/resourcebuilder/podspec_test.go
lib/resourcebuilder/resourcebuilder.go
pkg/cvo/internal/generic.go
pkg/cvo/internal/generic_test.go

Logging of resource diffs was introduced to detect [hotlooping in the CVO](https://github.com/openshift/cluster-version-operator/pull/561). But this increases the verbosity of logging during updates when the resources have changed which is not useful. The logging of the diffs is more useful in the reconcile mode. Also the diff is generated with [ObjectDiff](https://github.com/kubernetes/apimachinery/blob/235edae7dd90601011bbe3bcd6f84f7dc857b034/pkg/util/diff/diff.go#L57) which is deprecated. The `ObjectDiff` function now just uses [cmp.Diff](https://pkg.go.dev/github.com/google/go-cmp/cmp#Diff) internally and all instances of `ObjectDiff` have been replaced with `cmp.Diff`.

Bug 1984414: Log resource diffs on update only in reconcile mode

---

lib/resourcedelete/apiext.go
lib/resourcedelete/apireg.go
lib/resourcedelete/apps.go
lib/resourcedelete/batch.go
lib/resourcedelete/core.go
lib/resourcedelete/imagestream.go
lib/resourcedelete/rbac.go
lib/resourcedelete/security.go
pkg/cvo/internal/generic.go

Previously delete methods would simply return when not in UpdateMode. This meant that if a delete was started in UpdateMode but had not completed while in UpdateMode the delete would never be marked as completed and minor upgrades would remain blocked. With this change deletes are continuously checked which also means a deleted resource that is recreated is logged as such by CVO even when not in UpdateMode. Deletes are still only requested when in UpdateMode.

Bug 1982046: lib/resourcedelete: Always check delete progress

---

README.md

As part of #631 CVO docs has been removed as the docs are moved to
enhancements repository [1]
[1] https://github.com/openshift/enhancements/pull/695/

Update the doc links in Readme

---

pkg/start/start.go

As per [1]
[1] https://github.com/openshift/library-go/blob/4b9033d00d37b88393f837a88ff541a56fd13621/pkg/config/leaderelection/leaderelection.go#L84

Bug 1985802: Updating the lease, renew, retry duration

---

install/0000_90_cluster-version-operator_02_servicemonitor.yaml
pkg/cvo/metrics.go
pkg/cvo/metrics_test.go

Bringing #550 back to 4.7.  By hand, since there are neighbor-line conflicts with #587, which landed first in 4.7, but is backported from changes that landed later in master/4.8.

Bug 1991010: pkg/cvo/metrics: Ignore Degraded for cluster_operator_up

---

install/0000_00_cluster-version-operator_01_adminack_configmap.yaml
install/0000_00_cluster-version-operator_01_admingate_configmap.yaml
pkg/cvo/cvo.go
pkg/cvo/cvo_test.go
pkg/cvo/upgradeable.go
pkg/internal/constants.go
pkg/payload/precondition/clusterversion/upgradable_test.go
pkg/payload/precondition/clusterversion/upgradeable.go

This PR adds a generic upgrade blocking mechanism for blocking minor level upgrades. It is the general implementation of the [Add admin ack upgrade gate enhancement](https://github.com/openshift/enhancements/pull/828). Therefore since 4.9 does not contain any active admin ack gates the check `clusterAdminAcksCompletedUpgradeable` is not added to `defaultUpgradeableChecks`. It is added as part of unit test and tested.
This PR will be backported to 4.8.z and the 4.8 specific implementation details will be added, i.e. the `ack-4.8-kube-122-api-removals-in-4.9` gate will be added by adding check `clusterAdminAcksCompletedUpgradeable` to `defaultUpgradeableChecks`.
Once active the  `clusterAdminAcksCompletedUpgradeable` Upgradeable check implementation differs from other Upgradeable checks by …

Bug 1978376: Add admin ack Upgradeable condition gate

---

pkg/cvo/cvo_test.go
pkg/cvo/upgradeable.go

519b466793 (#633) had these commented out, because 4.9 has no built-in acks.  But with the code commented out, it's [hard to verify][1] that the logic works in 4.9 before backporting to 4.8.  Enabling these checks should be a no-op outside of verification, because admins are unlikely to inject additional keys in the `openshift-config-managed` namespace's `admin-gates` ConfigMap.  And it allows us to verify the logic in 4.9 and cook there with live code before approving the 4.8 backports.  It's also one less thing we might forget before enabling new admin acks in future versions, like 4.10 or later.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1978376#c19

Bug 1978376: pkg/cvo/upgradeable: Enable admin-ack logic

---

pkg/cvo/cvo.go

Hopefully we never actually have to stuff a CVO-generated ClusterVersion into the cluster; it's just for recovery after admins accidentally delete their existing ClusterVersion.  But if we ever do hit this code, we want to push it without `spec.upstream`, to allow later ClusterVersion-consuming code to say "ah, user doesn't care which upstream I use, so I'll use the best default I'm aware of". This effectively pushes default choice from the CVO that creates the ClusterVersion out to the CVO that consumes the ClusterVersion, and that later CVO is almost certainly more current on which default is best.
Similar to openshift/installer@c9095b3451 (openshift/installer#4112).

pkg/cvo: Drop the explicit 'upstream' from our replacement ClusterVersion

---

pkg/cvo/egress.go

Backport to release-4.8 of [PR 621](https://github.com/openshift/cluster-version-operator/pull/621)
Since 4.2's ea5e3bc (Add http transport for cincinnati to enable
proxy, 2019-07-16, #219), the CVO has been loading proxy config from
the spec property.  We should be loading from status instead, so we
benefit from the network operator's validation.  Risk is small,
because unlike some other in-cluster components, the CVO is unlikely
to break things if it is temporarily consuming a broken proxy
configuration.
This is similar to c9fab43 (pkg/cvo: Fetch proxy CA certs from
openshift-config-managed/trusted-ca-bundle, 2020-01-31, #311), where
we moved our trusted CA source from the user-configured ConfigMap to
the network-operator-validated ConfigMap.

Bug 1980411: [release-4.8] pkg/cvo/egress: Load HTTPS proxy from Proxy status

---

pkg/cvo/cvo.go
pkg/payload/precondition/clusterversion/upgradeable.go

Back-ported "Ensure recent etcd backup before allowing minor-version updates":
$ git cherry-pick ee2dcd1

Bug 1999777: Ensure recent etcd backup before allowing minor-version updates

---

lib/resourcemerge/core.go
lib/resourcemerge/core_test.go

Since this package was created in d9f6718de0 (#7), the volume(mount) merge logic has required manifest entries to exist, but has allowed in-cluster entries to persist without removal.  That hasn't been a problem [until][1]:
1. In 4.3, the autoscaler asked for a ca-cert volume mount, based on the cluster-autoscaler-operator-ca config map.
2. In 4.4, the autoscaler [dropped those manifest entries][2].
3. In 4.9, the autoscaler [asked the CVO to remove the config map][3].
That lead some born-in 4.3 clusters to have crashlooping autoscalers, because the mount attempts kept failing on the missing config map.
We couldn't think of a plausible reason why cluster admins would want to inject additional volume mounts in a CVO-managed pod configuration, so this commit removes that ability and begins …

Bug 2002834: lib/resourcemerge/core: Remove unrecognized volumes and mounts

---

install/0000_00_cluster-version-operator_03_deployment.yaml

[This content][2] is [injected by an admission webhook][1].  When we started removing not-in-manifest volumes in 83faa6e716 (#654), the cluster-version operator started removing the webhook-injected volume, leading to the cluster-version operator crash-looping on updates from 4.8 to 4.9 with messages [like][3]:
F0920 13:23:23.565439       1 start.go:24] error: error creating clients: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
With this commit, we follow the precedent of the Kubernetes API server's own manifest: openshift/cluster-kube-apiserver-operator#1142.
[1]: https://github.com/kubernetes/kubernetes/blob/2f68346fbb6246961ce0a3176418630950aea500/plugin/pkg/admission/serviceaccount/admission.go#L53-L54
[2]: …

Bug 2005581: install/0000_00_cluster-version-operator_03_deployment: Explicit kube-api-access

---

install/0000_00_cluster-version-operator_03_deployment.yaml

Bug 2006145: install/0000_00_cluster-version-operator_03_deployment: Explicit kube-api-access

---

.ci-operator.yaml

This is [ART's default for OpenShift 4.10][1], and we need [1.16's new `io/fs` package][2] to [avoid][3]:
INFO[2021-09-24T19:45:46Z] vendor/k8s.io/client-go/plugin/pkg/client/auth/exec/metrics.go:21:2: cannot find package "." in:
/go/src/github.com/openshift/cluster-version-operator/vendor/io/fs
for the 1.22 Kube bumps needed for targeted edge blocking (#663).
[1]: https://github.com/openshift/ocp-build-data/blob/f14ea97fcb9893c325f12bed9d9afb9cd2f10857/streams.yml#L31
[2]: https://golang.org/doc/go1.16#fs
[3]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/663/pull-ci-openshift-cluster-version-operator-master-unit/1441488679963987968#1:build-log.txt%3A13

.ci-operator: Bump to Go 1.16

---

docs/dev/run-cvo-locally.md

Reference: https://github.com/openshift/cluster-version-operator/issues/666
As I am a newbie and trying to learn the CVO's flow, let me know, in case unsetting the `listen` doesn't make sense. Will be glad to hear some inputs.

Unset listen option while running CVO locally [doc/dev]

---

install/0000_00_cluster-version-operator_01_adminack_configmap.yaml
install/0000_00_cluster-version-operator_01_admingate_configmap.yaml
pkg/cvo/cvo.go
pkg/cvo/cvo_test.go
pkg/cvo/upgradeable.go
pkg/internal/constants.go
pkg/payload/precondition/clusterversion/upgradable_test.go
pkg/payload/precondition/clusterversion/upgradeable.go

This PR backports "Bug 1978376: Add admin ack Upgradeable condition gate" and "pkg/cvo/upgradeable: Enable admin-ack logic". It also adds the 4.8 gate "ack-4.8-kube-122-api-removals-in-4.9" which blocks upgrades to 4.9 until an admin performs the required acknowledgement step.
The PR is composed of 3 commits the first 2 of which were created with cherry-pick:
$ git cherry-pick 519b466
$ git cherry-pick 5b5db7d

Bug 1999092: Add and enable admin ack Upgradeable condition gate 

---

cmd/start.go

Without different seed values in rand.Seed(), rand.Float64() does not return random values

Adding seed to make rand.Float64() return random values

---

pkg/cvo/updatepayload.go

The logic I'm removing is a convenience from 558ae021bd (#63).  But the current consensus is that:
* Rollbacks are risky enough that we don't want to make them that convenient.
* Rollbacks have never been supported, so removing the convenient pullspec lookup is a backwards-compatible-enough change.
This also brings the ClusterVersion operator's approach into line with how `oc adm upgrade --to ...` has always worked; openshift/oc#566.

Bug 1878925: pkg/cvo/updatepayload: Drop history from target pullspec lookup

---

install/0000_00_cluster-version-operator_01_adminack_configmap.yaml
install/0000_00_cluster-version-operator_01_admingate_configmap.yaml

There's [an enhancement proposal][1] for this profile, and the Code Ready Containers folks [took a run at using it][2] before [backing off][3].  I don't have any problems with having a specific CRC profile, but if we end up going that way, we'll need a lot more CVO manifests with the annotation than just these two admin-ack ConfigMaps (e.g. we'll probably also want the CVO's Namespace and Deployment, etc., or there won't be anything consuming the admin-ack ConfigMaps ;).  This commit drops these two annotations, which slipped in when the ConfigMaps landed in 519b466793 (#633).
[1]: https://github.com/openshift/enhancements/blob/2911c46bf7d2f22eb1ab81739b4f9c2603fd0c07/enhancements/single-node/developer-cluster-profile.md
[2]: https://github.com/code-ready/snc/pull/338
[3]: …

install: Drop single-node-developer profile

---

bootstrap/bootstrap-pod.yaml
install/0000_00_cluster-version-operator_03_deployment.yaml

From [upstream docs][1]:
> For Pods running with hostNetwork, you should explicitly set its DNS policy "ClusterFirstWithHostNet".
[The type definitions include][2]:
* `ClusterFirstWithHostNet`, using cluster DNS, and falling back to kubelet defaults.
* `Default`, using kubelet defaults alone.
* `ClusterFirst`, which acts like `Default` with `hostNetwork:true` (bizarrely not including cluster DNS at all, despite including `Cluster` in the name), but like `ClusterFirstWithHostNet` otherwise.
There's also some discussion in [rhbz#1880902][3].
[1]: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
[2]: https://github.com/kubernetes/kubernetes/blob/f0b7ad3ee06c5168fef5fa4f01fe445ece595f89/pkg/apis/core/types.go#L2396-L2408
[3]: …

install/0000_00_cluster-version-operator_03_deployment: Set dnsPolicy: ClusterFirstWithHostNet

---

lib/resourcemerge/imagestream.go

Cherry-pick of #674 + #677 on release-4.8 branch

[release-4.8] Bug 2015025: lib/resourcemerge/imagestream.go: Copy all data for new tag reference

---

pkg/cvo/sync_worker.go

Fixes https://github.com/openshift/cluster-version-operator/issues/688
`getOverrideForManifest` needs unit tests, but I can follow up separately since this is urgent for ARO.

Bug 2022509: cvo: Compare manifest group in getOverrideForManifest

---

install/0000_00_cluster-version-operator_00_namespace.yaml
install/0000_00_cluster-version-operator_01_adminack_configmap.yaml
install/0000_00_cluster-version-operator_01_admingate_configmap.yaml
install/0000_00_cluster-version-operator_02_roles.yaml
install/0000_00_cluster-version-operator_03_deployment.yaml
install/0000_90_cluster-version-operator_00_prometheusrole.yaml
install/0000_90_cluster-version-operator_01_prometheusrolebinding.yaml
install/0000_90_cluster-version-operator_02_servicemonitor.yaml
install/0001_00_cluster-version-operator_03_service.yaml

To make it easier to see what these resources are for, especially once they become in-cluster resources and `git blame ...` is further away.
See [this example][1] in the upstream docs of using the `kubernetes.io/description` annotation for this purpose, although the key is not listed [in this reference][2].
[1]: https://github.com/kubernetes/website/blob/082116588c191f52de2003deb71ce7a304cc357d/content/en/examples/access/endpoints-aggregated.yaml#L5
[2]: https://github.com/kubernetes/website/blob/082116588c191f52de2003deb71ce7a304cc357d/content/en/docs/reference/labels-annotations-taints.md

install: Add description annotations to manifests

---

pkg/cincinnati/cincinnati.go
pkg/cincinnati/cincinnati_test.go

[Avoid][1]:
```
6609 E1130 07:10:17.721916       1 runtime.go:78] Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error:      index out of range [0] with length 0)
6610 goroutine 177 [running]:
6611 k8s.io/apimachinery/pkg/util/runtime.logPanic({0x196f5a0, 0xc000eee2d0})
6612         /go/src/github.com/openshift/cluster-version-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x85
6613 k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000af1680})
6614         /go/src/github.com/openshift/cluster-version-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x75
6615 panic({0x196f5a0, 0xc000eee2d0})
6616         /usr/lib/golang/src/runtime/panic.go:1038 +0x215
6617 …
```

Bug 2027585: pkg/cincinnati: Fix panic for conditional edges with risks after an invalid risk

---

lib/resourcemerge/apps.go
lib/resourcemerge/apps_test.go

@tdosek and @vrutkovs noticed that, when a Deployment manifest leaves `replicas` unset, the CVO ignores the property.  This means that cluster admins can scale those Deployments up or, worse, down to 0, and the CVO will happily continue on without stomping them.  Auditing 4.9.10:
```console
$ oc adm release extract --to manifests quay.io/openshift-release-dev/ocp-release:4.9.10-x86_64
Extracted release payload from digest sha256:e1853d68d8ff093ec353ca7078b6b6df1533729688bb016b8208263ee7423f66 created at 2021-12-01T09:19:24Z
$ for F in $(grep -rl 'kind: Deployment' manifests); do yaml2json < "${F}" | jq -r '.[] | select(.kind == "Deployment" and .spec.replicas == null).metadata | .namespace + " " + .name'; done | sort | uniq
openshift-cluster-machine-approver machine-approver …
```

Bug 2028217: lib/resourcemerge/apps: Default Deployment replicas to one

---

install/0000_00_cluster-version-operator_00_namespace.yaml

Given the original commit for this was in 2018, it might be possible to remove the label now entirely. Given #24 is specifically setting it a dependency on the openshift-apiserver, I doubt it, 
Will use this PR for testing and further discussion.

Bug 2020107: Remove run-level label

---

lib/resourcemerge/core.go
lib/resourcemerge/core_test.go

We had been merging by name since `ensureVolumeMounts` landed in 83faa6e716 (#654).  But as pointed out in [rhbz#2026560][1], a single volume may be mounted at multiple paths.  With this commit, I'm pivoting to merge by `mountPath`, [which is the `patchMergeKey`][2] (and it makes sense that you wouldn't have multiple volumes mounted at the same path).
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=2026560
[2]: https://github.com/kubernetes/api/blob/1d6faf224f146dd002553f55cd9fcaaaa0dc00cb/core/v1/types.go#L2367

Bug 2026560: lib/resourcemerge/core: Merge volumeMounts by mountPath

---

hack/cluster-version-util/task_graph.go
pkg/cvo/cvo.go
pkg/cvo/cvo_scenarios_test.go
pkg/cvo/sync_worker.go
pkg/featurechangestopper/techpreviewchangestopper.go
pkg/featurechangestopper/techpreviewchangestopper_test.go
pkg/payload/payload.go
pkg/payload/payload_test.go
pkg/payload/task_graph_test.go
pkg/start/start.go
pkg/start/start_integration_test.go

rebase and push of https://github.com/openshift/cluster-version-operator/pull/546
It still needs an auto-shutdown and probably (haven't yet looked) a few tests.
Implements https://github.com/openshift/enhancements/pull/957

Exclude featuregate.release.openshift/tech-preview=true manifests

---

pkg/featurechangestopper/techpreviewchangestopper.go
pkg/start/start.go

To make it easier to differentiate between "cluster version operator is confused about the cluster's tech-preview-ness", "cluster-version operator has broken manifest exclusion logic", and "manifest is mis-setting an annotation".
WIP until we remove the `pkg/payload/payload.go` logging, which I'm using to help debug openshift/cluster-capi-operator#20.

pkg/start: Log and continue when we fail to retrieve the feature gate

---

pkg/cincinnati/cincinnati.go

Like fa40743276 (#679), but for [rhbz#2029785][1]:
```
3095 E1207 08:39:42.972092       1 runtime.go:78] Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error:      index out of range [0] with length 0)
3096 goroutine 169 [running]:
3097 k8s.io/apimachinery/pkg/util/runtime.logPanic({0x196f5a0, 0xc0013b4be8})
3098         /go/src/github.com/openshift/cluster-version-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x85
3099 k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc001a7dd90})
3100         /go/src/github.com/openshift/cluster-version-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x75
3101 panic({0x196f5a0, 0xc0013b4be8})
3102         /usr/lib/golang/src/runtime/panic.go:1038 +0x215
3103 …
```

Bug 2029785: pkg/cincinnati: Fix panic for conditional edges overlapping with unconditional edges

---

lib/resourcemerge/apps.go
lib/resourcemerge/apps_test.go

Picking #698 back to 4.9, but without `pointer.Int32`, which [isn't part of 4.9's vendored `pointer` package][1].
[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-version-operator/700/pull-ci-openshift-cluster-version-operator-release-4.9-golangci-lint/1466469531768590336#1:build-log.txt%3A16

Bug 2028602: lib/resourcemerge/apps: Default Deployment replicas to one

---

pkg/cvo/availableupdates.go

Since openshift/installer#4112, clusters born in 4.7 or later default to not having an explicit spec.upstream, so they rely on the CVO's internal default.  However, in that case, `u.Upstream` will be an empty string, while by this point in `syncAvailableUpdates`, `upstream` will have been set to the default value.  This commit splits up the "do we really need to check?" logic into a number of distinct cases, and gives them more specific logging, to make it easier to understand and confirm the desired behavior:
a. If we have no cached data, we need to pull a graph.
b. If it's been over `minimumUpdateCheckInterval` since our last check,  we need to pull a graph.  Even if nothing has changed on our side, our data is sufficiently stale to need a refresh.
c. If the `channel` has changed, we …

Bug 2033745: pkg/cvo/availableupdates: Acount for default upstream in recent-change throttling

---

bootstrap/bootstrap-pod.yaml
install/0000_00_cluster-version-operator_03_deployment.yaml
lib/resourceapply/apiext.go
lib/resourceapply/apps.go
lib/resourceapply/batch.go
lib/resourceapply/core.go
lib/resourceapply/cv.go
lib/resourceapply/imagestream.go
lib/resourceapply/rbac.go
lib/resourceapply/security.go
lib/resourcebuilder/batch.go
lib/resourcedelete/helper.go
pkg/autoupdate/autoupdate.go
pkg/cincinnati/cincinnati.go
pkg/clusterconditions/cache/cache.go
pkg/clusterconditions/clusterconditions.go
pkg/clusterconditions/promql/promql.go
pkg/cvo/availableupdates.go
pkg/cvo/cvo.go
pkg/cvo/cvo_test.go
pkg/cvo/internal/generic.go
pkg/cvo/metrics.go
pkg/cvo/status.go
pkg/cvo/sync_worker.go
pkg/cvo/updatepayload.go
pkg/cvo/upgradeable.go
pkg/payload/payload.go
pkg/payload/precondition/clusterversion/upgradeable.go
pkg/payload/task_graph.go

We've been using `--v=5` since 88c222c954 (#448).  But it leads to large quantities of [noise from client-side throttling][1], and that throttling is `V(3)`:
```console
$ grep -n . vendor/k8s.io/client-go/rest/request.go | grep -B7 -A6 '^597:'
589:    switch {
590:    case len(retryInfo) > 0:
591:            message = fmt.Sprintf("Waited for %v, %s - request: %s:%s", latency, retryInfo, r.verb, r.URL().String())
592:    default:
593:            message = fmt.Sprintf("Waited for %v due to client-side throttling, not priority and fairness, request: %s:%s", latency, r.verb, r.URL().String())
594:    }
596:    if latency > longThrottleLatency {
597:            klog.V(3).Info(message)
598:    }
599:    if latency > extraLongThrottleLatency {
600:            // If the rate limiter latency is …
```

Bug 2034493: *: Use --v=2 logging to drop client-side throttling noise

---

lib/resourcemerge/apps.go
lib/resourcemerge/apps_test.go

62a9f077ad (#650) added strategy reconciliation, but as described [in rhbz#2000938][1], the `DeepEqual` is generating false positive `modified` detection when comparing manifests with implicit strategies like:
```console
$ oc adm release extract --to manifests registry.ci.openshift.org/ocp/release:4.10.0-0.nightly-2021-12-23-153012
$ grep -c strategy: manifests/0000_50_service-ca-operator_05_deploy.yaml
0
```
With the in-cluster resources that have the server-injected defaults:
```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.9-e2e-aws/1478247345723281408/artifacts/e2e-aws/gather-extra/artifacts/deployments.json | jq '.items[] | select(.metadata.name == "service-ca-operator").spec.strategy'
{ …
```

Bug 2000938: lib/resourcemerge/apps: Avoid hotlooping on implicit strategy

---

bootstrap/bootstrap-pod.yaml
install/0000_00_cluster-version-operator_03_deployment.yaml
lib/resourceapply/apiext.go
lib/resourceapply/apps.go
lib/resourceapply/batch.go
lib/resourceapply/core.go
lib/resourceapply/cv.go
lib/resourceapply/imagestream.go
lib/resourceapply/rbac.go
lib/resourceapply/security.go
lib/resourcebuilder/batch.go
lib/resourcedelete/helper.go
pkg/autoupdate/autoupdate.go
pkg/cincinnati/cincinnati.go
pkg/cvo/availableupdates.go
pkg/cvo/cvo.go
pkg/cvo/cvo_test.go
pkg/cvo/internal/generic.go
pkg/cvo/metrics.go
pkg/cvo/status.go
pkg/cvo/sync_worker.go
pkg/cvo/updatepayload.go
pkg/cvo/upgradeable.go
pkg/payload/payload.go
pkg/payload/precondition/clusterversion/upgradeable.go
pkg/payload/task_graph.go

We've been using --v=5 since 88c222c954
(install/0000_00_cluster-version-operator_03_deployment: Bump to
--v=5, 2020-08-30, #448).  But it leads to large quantities of noise
from client-side throttling [1], and that throttling is V(3):
$ grep -n . vendor/k8s.io/client-go/rest/request.go | grep -B7 -A6 '^597:'
589:    switch {
590:    case len(retryInfo) > 0:
591:            message = fmt.Sprintf("Waited for %v, %s - request: %s:%s", latency, retryInfo, r.verb, r.URL().String())
592:    default:
593:            message = fmt.Sprintf("Waited for %v due to client-side throttling, not priority and fairness, request: %s:%s", latency, r.verb, r.URL().String())
594:    }
596:    if latency > longThrottleLatency {
597:            klog.V(3).Info(message)
598:    }
599:    if latency > …

Bug 2038275: *: Use --v=2 logging to drop client-side throttling noise

---

bootstrap/bootstrap-pod.yaml
install/0000_00_cluster-version-operator_03_deployment.yaml
lib/resourcebuilder/batch.go
pkg/autoupdate/autoupdate.go
pkg/cincinnati/cincinnati.go
pkg/cvo/availableupdates.go
pkg/cvo/cvo.go
pkg/cvo/cvo_test.go
pkg/cvo/metrics.go
pkg/cvo/status.go
pkg/cvo/sync_worker.go
pkg/cvo/updatepayload.go
pkg/cvo/upgradeable.go
pkg/payload/payload.go
pkg/payload/precondition/clusterversion/upgradeable.go
pkg/payload/task_graph.go

We've been using --v=5 since 88c222c954
(install/0000_00_cluster-version-operator_03_deployment: Bump to
--v=5, 2020-08-30, #448).  But it leads to large quantities of noise
from client-side throttling [1], and that throttling is V(3):
$ grep -n . vendor/k8s.io/client-go/rest/request.go | grep -B7 -A6 '^597:'
589:    switch {
590:    case len(retryInfo) > 0:
591:            message = fmt.Sprintf("Waited for %v, %s - request: %s:%s", latency, retryInfo, r.verb, r.URL().String())
592:    default:
593:            message = fmt.Sprintf("Waited for %v due to client-side throttling, not priority and fairness, request: %s:%s", latency, r.verb, r.URL().String())
594:    }
596:    if latency > longThrottleLatency {
597:            klog.V(3).Info(message)
598:    }
599:    if latency > …

Bug 2038936: *: Use --v=2 logging to drop client-side throttling noise

---

pkg/cvo/sync_worker.go

Context:
1. bee2a5e634 (#713) was our initial attempt to respect overrides changes during install but reject target-release changes.  It [suffered from hot-looping on overrides-change detection][1], with:
1. Change to overrides detected.
2. Change not actually pushed into the sync workers.
3. Sync workers canceled.
4. Return to step i.
and install didn't actually complete when overrides were set (e.g. because [the installer was inserting overrides during bootstrapping to keep the CVO from clobbering user-provided manifests][2]).
2. 11bca782a8 (#727), got CI flowing again while we worked up a fix.
3. 5c7ed6da32 (#728) restored something a lot like bee2a5e634.  It fixed the overrides-change/worker-cancel hotlooping by always passing updated overrides values through to thet sync workers. …

Bug 2009845: pkg/cvo/sync_worker: Do not cancel sync workers on install-time target-version change

---

go.mod
go.sum
pkg/cvo/metrics.go
pkg/start/start.go
vendor/gopkg.in/fsnotify.v1/.editorconfig
vendor/gopkg.in/fsnotify.v1/.gitignore
vendor/gopkg.in/fsnotify.v1/.travis.yml
vendor/gopkg.in/fsnotify.v1/AUTHORS
vendor/gopkg.in/fsnotify.v1/CHANGELOG.md
vendor/gopkg.in/fsnotify.v1/CONTRIBUTING.md
vendor/gopkg.in/fsnotify.v1/LICENSE
vendor/gopkg.in/fsnotify.v1/README.md
vendor/gopkg.in/fsnotify.v1/fen.go
vendor/gopkg.in/fsnotify.v1/fsnotify.go
vendor/gopkg.in/fsnotify.v1/inotify.go
vendor/gopkg.in/fsnotify.v1/inotify_poller.go
vendor/gopkg.in/fsnotify.v1/kqueue.go
vendor/gopkg.in/fsnotify.v1/open_mode_bsd.go
vendor/gopkg.in/fsnotify.v1/open_mode_darwin.go
vendor/gopkg.in/fsnotify.v1/windows.go
vendor/modules.txt

Add a file watcher to the metrics server using the fsnotify package, to watch for changes to the TLS certificate for the metrics endpoint. Prior to this change when changes occurred to the metrics certificate CVO would have to be restarted to pick up the new certificate. With this change the HTTP server is shutdown and then recreated with the new TLS configuration.
Much of the code is reuse from [openshift/cluster-node-tuning-operator#297](https://github.com/openshift/cluster-node-tuning-operator/pull/297).
I tested this by simply running `oc delete secret/signing-key -n openshift-service-ca` as suggested in the bug.

Bug 2027342: Add notification for certificate changes

---

pkg/cvo/sync_worker.go

To make it easier to understand why this is happening.

Bug 2009845: pkg/cvo/sync_worker: Log transition to updating

---

pkg/cvo/cvo.go
pkg/start/start.go

The last consumer was removed way back in 90e9881bd5 (#45).

pkg/cvo: Drop unused 'workers' argument from Operator.Run

---

pkg/cvo/sync_worker.go

Fixing a bug from 5c7ed6da32 (#728), where:
1. The bootstrap cluster-version operator does its happy thing.
2. With bootstrap winding down, the bootstrap CVO exits, in favor of a control-plane-hosted CVO.
3. Control-plane CVO acquires the leader lock, and [continues `Initializing`][e].
4. As a final bootstrap action, the installer [patches away its `spec.overrides` additions][1].
5. The control-plane CVO watcher gets notified after the `overrides` change, and [call `SyncWorker.Update`][f].
6. `SyncWorker.Update` notices that `w.work != nil`, so it ignores [its `state` argument][a], and [the newly-created work structure][b]'s `State` defaults to 0, because:
```console
$ grep iota pkg/payload/payload.go
UpdatingPayload State = iota
```
and [`iota` starts at zero][2].  This is the bit I …

Bug 2009845: pkg/cvo/sync_worker: Use current state, not suggested state, for guarding Initializing->Updating

---

pkg/featurechangestopper/techpreviewchangestopper.go

As described in the bug, some 4.10 jobs that set `TechPreviewNoUpgrade` very early during install are running into trouble like:
1. Early in bootstrap, something sets `TechPreviewNoUpgrade`.
2. Cluster-version operator comes up, and attempts to figure out the current `featureSet`.  But because the Kubernetes API is also still coming up, that fails on an error [like][2]:
```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.10-e2e-aws-techpreview/1489537240471179264/artifacts/e2e-aws-techpreview/gather-extra/artifacts/pods/openshift-cluster-version_cluster-version-operator-76cd65b7bb-4p945_cluster-version-operator.log | grep 'Error getting featuregate value\|tech'
W0204 10:10:40.126809       1 …
```

Bug 2050946: pkg/featurechangestopper: Seed queue to guard against incorrect startingTechPreviewState

---

pkg/payload/payload.go
pkg/payload/payload_test.go

We have a number of different annotations all working together now, so logging exclusions with our reasoning will help folks who are debugging "why is my manifest not being reconciled?".  And while this will create a number of logs for some profiles, we we already log each reconciled manifest with every sync cycle, so the volume increase isn't huge compared to our existing log rate.  This is primarily a dev-time issue, which argues against log spew for production clusters, but since 72599d323d (#694), there's been the dynamic tech-preview business, so there is now more utility in production logging around this than there was before.

pkg/payload: Log manifest exclusion

---

pkg/cvo/cvo.go
pkg/cvo/cvo_scenarios_test.go
pkg/cvo/sync_test.go
pkg/cvo/sync_worker.go

Fix remaining comments from https://github.com/openshift/cluster-version-operator/pull/683.
Remove unused parameter lister `configlistersv1.ClusterVersionLister` from `SyncWorker.Update`.

Bug 1822752: pkg/cvo: Fix ups from separating load from apply #683

---

pkg/featurechangestopper/techpreviewchangestopper.go
pkg/start/start.go

Bringing #736 and #739 back to 4.10.

Bug 2053359: Feature gate initialization

---

hack/cluster-version-util/task_graph.go
lib/capability/capability.go
lib/capability/capability_test.go
pkg/cvo/cvo.go
pkg/cvo/cvo_scenarios_test.go
pkg/cvo/status.go
pkg/cvo/sync_test.go
pkg/cvo/sync_worker.go
pkg/payload/payload.go
pkg/payload/payload_test.go
pkg/payload/task_graph_test.go

Implements initial, postinstall, support of static capabilities
per Jira [OTA-567](https://issues.redhat.com/browse/OTA-567).

Consume post install static spec capabilities

---

pkg/payload/payload.go

We moved from `--v=5` to `--v=2` with c4a10047f3 (#721).  But this `V(5)` logging slipped through via the parallel 5d343a503d (#712).  Catch it up, to restore exclusion logging.

pkg/payload: Log load-time manifest exclusion at V(2)

---

pkg/cvo/cvo_scenarios_test.go
pkg/cvo/sync_worker.go

`SyncWorker.apply` creates a `consistentReporter` passing in a new `SyncWorkerStatus` struct. It did not set all struct fields and therefore sets any not explicitly set back to default stepping on both recently added `CapabilitiesStatus` and `loadPayloadStatus` fields. This PR assigns the current value of those fields to the newly created `SyncWorkerStatus` struct.

pkg/cvo/sync_worker.go: ensure all of SyncWorkerStatus copied

---

lib/capability/capability.go

This makes life more predictable for consumers, including our own unit tests.

lib/capability: Sort status.capabilities arrays

---

pkg/cvo/metrics.go

Fleet capability choices should make their way up to Red Hat via Insights uploads.  But [some clusters have Telemetry enabled but Insights disabled][1].  For these clusters, we'll want this data in Telemetry, and getting it into metrics (this commit) is the first step.  After this lands, we'll need to update the monitoring operator like [this][2] to get these shipped up off of cluster.
[1]: https://github.com/openshift/enhancements/pull/922#discussion_r742287363
[2]: https://github.com/openshift/cluster-monitoring-operator/pull/1477

pkg/cvo/metrics: Add a cluster_version_capability metric

---

pkg/cvo/updatepayload.go

[Avoid][1]:
mv: inter-device move failed: '/manifests' to '/etc/cvo/updatepayloads/HbO7IDc7tyIg9utw3sd_tg/manifests/manifests'; unable to remove target: Directory not empty
by pruning all scratch directories before downloading a new payload.  Also shift the job pruning up here too, so it's all collected together.  This avoids sticking subsequent download jobs after a corrupted download attempt (e.g. if something terminates a download job part way through its `mv` call, subsequent download ).  Reproducing this issue locally, with `/tmp` on a different filesystem:
```console
$ mkdir -p a /tmp/a/a
$ /bin/mv a /tmp
/bin/mv: inter-device move failed: 'a' to '/tmp/a'; unable to remove target: Directory not empty
$ /bin/mv --version
mv (GNU coreutils) 8.31
...
```
The directory pruning will also …

Bug 2070805: pkg/cvo/updatepayload: Prune previous payload downloads

---

lib/capability/capability.go
pkg/cvo/sync_worker.go

Pivot `ClusterCapabilities.Equal` to return an error explaining the difference.  This allows me to use that tailored error in the `equalSyncWork` message, so I don't have to guess how `ClusterCapabilities.Equal` is implemented or log the whole capabilities structure.

pkg/cvo/sync_worker: Log only changed enabled capabilities

---

pkg/cvo/sync_worker.go

since implicitly enabled capability changes do not trigger !capabilitiesEqual so we return before setting the status.

Bug 2070887: pkg/cvo/sync_worker.go: set implicitly enabled caps earlier

---

pkg/cvo/sync_worker.go

which can occur since the splitting of payload load and apply to be called in separate goroutines https://github.com/openshift/cluster-version-operator/pull/683. Each thread will now call it's own `update status` function that only sets status values it manages.

Bug 2070854: syncWorkerStatus: Avoid saving stale status values

---

pkg/cvo/updatepayload.go

I'd attempted to add this cleanup on the CVO side in 507b474632 (#760), but @evakhoni pointed out that that doesn't work because the CVO's volume mount is `readOnly: true`:
2022-04-11T20:42:32.056428784Z W0411 20:42:32.056387       1 updatepayload.go:149] failed to prune update payload directory: unlinkat /etc/cvo/updatepayloads/brRTeZnZSIkZ2J2YMdQozg: read-only file system
This commit shifts removal into the job.
And because we want that removal to also cover "a previous job run half-populated the target release directory", I've removed the pre-fetch `ValidateDirectory` check.  In cases where we already had valid content locally, that's one extra download, which seems like a lower price than assuming a previous partial download was actually complete.  If we see many extra downloads, we …

Bug 2070805: pkg/cvo/updatepayload: Shift previous-download removal into the job

---

pkg/cvo/updatepayload.go

Some background on recent changes:
* 507b474632 (#760) attempted to add CVO-side directory removal, but that failed because the CVO mounts the shared volume `readOnly: true`.
* a5af89d34e (#765) shifted removal into the job itself.  As far as I can tell, this worked.
* c45a981302 (#765) addressed concerns with unquoted shell arguments by pivoting to `initContainers` and dropping the shell.  This broke the `*` pathname expansion that `rm` depends on to find directories to remove.
This commit returns to using the shell to invoke the `rm` call, so we get [pathname expansion][1] back.  But I avoid the possibility of unquoted argument injection by using `workingDir` to bring in `baseDir`.
[1]: https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_06

Bug 2070805: pkg/cvo/updatepayload: Restore shell for rm globbing

---

pkg/cvo/cvo_scenarios_test.go
pkg/cvo/sync_worker.go

since this will cause `equalSyncWork` to continually return `true` and no reattempt to load the payload will occur until the desired update is updated by the user again, e.g. image change or change to `force`. This was accomplished by moving `work` update, including the desired version, after the desired version payload has been successfully loaded.
See commit message for more details on precondition failures in general and the `RecentEtcdBackup` precondition specifically.

Bug 2072389: Do not save desired update on load failures

---

pkg/cvo/cvo_scenarios_test.go
pkg/cvo/sync_worker.go

if changed before returning due to a desired update payload load failure.

Bug 2080429: pkg/cvo/sync_worker.go: Save overrides and capabilities

---

install/0000_00_cluster-version-operator_01_admingate_configmap.yaml

This reverts commit f159829988ab7db53460ae725d4ebfbfb7641e1c.
We are reverting this because we want to merge with around 4.12 feature
freeze. Right now it is too early to add this.

Revert "admin-gates: Add ack-4.11-kube-1.25-api-removals-in-4.12 gate"

---

pkg/cvo/updatepayload.go

[Avoid](https://bugzilla.redhat.com/show_bug.cgi?id=2070805#c0):
mv: inter-device move failed: '/manifests' to '/etc/cvo/updatepayloads/HbO7IDc7tyIg9utw3sd_tg/manifests/manifests'; unable to remove target: Directory not empty
by pruning all scratch directories before downloading a new payload.
Picks #760, #765, and #767 back to 4.10.

Bug 2080058: pkg/cvo/updatepayload: Prune previous payload downloads

---

lib/capability/capability.go
pkg/cvo/cvo_scenarios_test.go
pkg/cvo/sync_worker.go
pkg/cvo/testdata/payloadcapabilitytest/test10/current/file_1.yaml
pkg/cvo/testdata/payloadcapabilitytest/test10/update/file_1.yaml
pkg/payload/payload.go
pkg/payload/payload_test.go
pkg/payload/task.go

so newly started CVO pod, including one which results from an upgrade, will be able to determine and set implicitly enabled capabilities.
Also made the following changes:
- Set `w.status` when `w.work == nil` so as not to clobber `CapabilitiesStatus`. `CapabilitiesStatus` would never had been set at that point in the code before this change.
- Duplicate manifests are handled by `GetImplicitlyEnabledCapabilities` by tainting in all applicable capabilities across the duplicated manifests.

Bug 2079789: capability: Init prior known from CV status

---

lib/resourcebuilder/apps.go
lib/resourcebuilder/batch.go

I'd missed these Gets in 0833bba34d (#771).  What I'd thought was happening:
1. Pass `typedObject` into `check*Health`.
2. No status on `typedObject`, so `check*Health` passed, even if the in-cluster resource was sad.
What was actually happening:
1. Pass `typedObject` into `check*Health`.
2. `check*Health` calls `Get` to see what's going on in the cluster.
3. Health check appropriately checks the health of the in-cluster resource.
However, now that 0833bba34d is passing in the just-retrieved in-cluster resource, the `check*Health` `Get` call is an API call that we don't need to make.  Dropping it here saves us and the API server a small amount of CPU cycles and network bandwidth.

Bug 2081895: lib/resourcebuilder: Drop Get from check*Health functions

---

go.mod
go.sum
pkg/cvo/sync_worker.go
pkg/cvo/updatepayload.go
pkg/payload/task.go
vendor/github.com/openshift/library-go/pkg/verify/store/configmap/configmap.go
vendor/github.com/openshift/library-go/pkg/verify/store/parallel/parallel.go
vendor/github.com/openshift/library-go/pkg/verify/store/serial/serial.go
vendor/github.com/openshift/library-go/pkg/verify/store/sigstore/sigstore.go
vendor/github.com/openshift/library-go/pkg/verify/store/store.go
vendor/github.com/openshift/library-go/pkg/verify/verify.go
vendor/modules.txt

For unforced updates, when signature, etc. verification fails, `RetrievePayload` returns an error, and we have emitted events for `RetrievePayload` errors since 475e71f334 (#411).  However, when the user forces the update, we log but do not error out on verification failures.  With this commit, we will also emit a warning event with an error message, which will make it easier to understand how signature verification failed, even [when we don't have access to the logs of the outgoing cluster-version operator][1].
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=2071998#c2

Bug 2071998: pkg/cvo/updatepayload: Event when forcing through a sig-verification failure

---

pkg/cvo/updatepayload.go

[Avoiding][1]:
```console
$ tar -xOz must-gather/namespaces/openshift-cluster-version/pods/version-4.10.16-dk76g-6qdx2/cleanup/cleanup/logs/current.log <02527285_must-gather-20220531_022021Z.tar.gz
2022-05-31T02:13:19.710822157Z rm: invalid option -- 'c'
2022-05-31T02:13:19.710822157Z Try 'rm ./-cgXkuYo_RfOyhs3_AZGxQ' to remove the file '-cgXkuYo_RfOyhs3_AZGxQ'.
2022-05-31T02:13:19.710822157Z Try 'rm --help' for more information.
```
The version-specific filenames are MD5s of the image pullspec which are then encoded with `RawURLEncoding`.  [`RawURLEncoding` uses the encoding from RFC 4648][2].  RFC 4648's URL encoding [includes `-` for decimal 62][3].
We could use `rm -fR -- *`, but I don't see `--` specified [in POSIX][4].  `./*` is a POSIX-compliant way to avoid `rm` misinterpreting …

Bug 2091770: pkg/cvo/updatepayload: Guard against 'rm -fR -whatever' with ./*

---

pkg/cvo/sync_worker.go

Bug 2090150: pkg/cvo/sync_worker.go: Save overrides

---

pkg/cvo/status.go
pkg/cvo/status_test.go

which was the intent of https://github.com/openshift/cluster-version-operator/commit/6971c2bce79327fd51045fe6726c5d9c4524aaed. But that change failed to keep the last completed if last completed is at position maxHistory-1. It also did not work for a "prune as you go" `(len(History) == maxHistory+1)` strategy which is how the pruner is called by mergeOperatorHistory.

Bug 2097067: pkg/cvo: retain initial completed update history entry

---

pkg/cvo/cvo.go
pkg/cvo/cvo_scenarios_test.go
pkg/cvo/sync_test.go
pkg/cvo/sync_worker.go

Back-port https://github.com/openshift/cluster-version-operator/pull/753/commits/35b0f4f0b2b8c2b2c04789dbeee2d5175fbc93a2 and https://github.com/openshift/cluster-version-operator/pull/782/commits/a16c4ce07f7cf2c89ad36bc36929cf918e3e7cff to 4.9. There were many subsequent fix-up and issue resolution commits related to this original change in 4.11 but as explained below, these other commits are not required for this back-port. 
In addition to splitting the load and application of a given payload into two separate goroutines, the original PR https://github.com/openshift/cluster-version-operator/pull/683 also created a new condition, `DesiredReleaseAccepted`, indicating whether the requested (desired) release payload was successfully loaded. This portion of the original PR has not been …

Bug 2091806: pkg/cvo: Separate payload load from payload apply

---

lib/resourcemerge/core.go
lib/resourcemerge/core_test.go
lib/resourcemerge/meta_test.go

to handle securityContext changes differently. Since https://github.com/openshift/cluster-version-operator/commit/d9f6718, if a securityContext is not explicitly specified in the manifest the resource's securityContext will remain unchanged and it will continue to use the securityContext setting of the currently running resource (if there is one). We're not sure of the exact reason the logic was originally developed in this manner but this change joins a series of similar previous tightenings, including https://github.com/openshift/cluster-version-operator/commit/02bb9ba829174d799e418aeedfbd88bf572a35a0 (lib/resourcemerge/core: Clear env and envFrom if unset in
manifest, 2021-04-20, https://github.com/openshift/cluster-version-operator/pull/549) and …

Bug 2108858: lib/resourcemerge: change SecurityContext reconcile

---

pkg/clusterconditions/promql/promql.go

In some clusters, [these PromQL queries can hang for hours, possibly forever][1].  I think we have [a 30s default `KeepAlive` timeout][2], but apparently there's enough socket traffic to keep from tripping that.  This adds a 5m cap to the PromQL calls, although I'm not particularly attached to that particular number.  We can always raise it if we start seeing timeouts in Insights for queries where taking that long seems reasonable.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=2109374#c12
[2]: https://pkg.go.dev/github.com/prometheus/client_golang/api#pkg-variables

Bug 2109374: pkg/clusterconditions/promql: Cap PromQL queries at 5 minutes

---

pkg/cvo/updatepayload.go

This blocks us from being associated with SecurityContextConstraints that set `readOnlyRootFilesystem: true`, because from [the upstream docs][1]:
> The set of SCCs that admission uses to authorize a pod are determined by the user identity and groups that the user belongs to.  Additionally, if the pod specifies a service account, the set of allowable SCCs includes any constraints accessible to the service account.
>
> Admission uses the following approach to create the final security context for the pod:
>
> 1. Retrieve all SCCs available for use.
> 2. Generate field values for security context settings that were not specified on the request.
> 3. Validate the final settings against the available constraints.
If we leave `readOnlyRootFilesystem` implicit, we may get associated with a SCC …

Bug 2110590: pkg/cvo/updatepayload: Set 'readOnlyRootFilesystem: false'

---

pkg/cvo/availableupdates.go
pkg/cvo/cvo.go
pkg/cvo/cvo_scenarios_test.go
pkg/cvo/cvo_test.go
pkg/cvo/sync_worker.go
pkg/payload/payload.go
pkg/payload/payload_test.go
pkg/start/start_integration_test.go

and use when querying OSUS. Per https://issues.redhat.com/browse/OTA-655, heterogeneous cluster payloads will contain metadata key "architecture" set to "multi". Homogeneous cluster payloads are unchanged and will not contain the metadata key "architecture" in which case CVO will set the architecture using runtime.GOARCH.

Pull arch from payload

---

pkg/cvo/availableupdates.go
pkg/cvo/cvo.go
pkg/cvo/cvo_scenarios_test.go
pkg/cvo/cvo_test.go
pkg/cvo/sync_worker.go
pkg/payload/payload.go
pkg/payload/payload_test.go
pkg/start/start_integration_test.go

Reverts openshift/cluster-version-operator#796 ; tracked by [TRT-441](https://issues.redhat.com/browse/TRT-441)
Per [TRT policy](https://github.com/openshift/enhancements/blob/725a118640d7b9fa8c6f720f2adb841de654fac5/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this (what I believe to be a) breaking change to get ci and/or nightly payloads flowing again.
```
[sig-instrumentation][Late] Alerts shouldn't report any unexpected alerts in firing or pending state [Suite:openshift/conformance/parallel]:
alert CannotRetrieveUpdates fired for 78 seconds with labels: {endpoint="metrics", instance="10.0.131.99:9099", job="cluster-version-operator", namespace="openshift-cluster-version", pod="cluster-version-operator-7b559749b8-fgff9", …
```

Revert "Pull arch from payload"

---

pkg/cvo/status.go

in condition message to avoid test failures caused by bg
sync timing that affects the order of the implicitly
enabled capabilities.

pkg/cvo/status.go: sort implicitly enabled caps

---

pkg/cvo/cvo.go
pkg/cvo/sync_test.go
pkg/cvo/sync_worker.go

@deads2k and @stbenjam [identified an uneccessary delay][1]:
* 9:42:00, CVO gives up on Kube API server ClusterOperator
* 9:42:47, Kube API server operator achieves 4.12
* 9:46:22, after a cool-off sleep, the CVO starts in on a new manifest graph-walk attempt
* 9:46:34, CVO notices that the Kube API server ClusterOperator is happy
The 3+ minute delay from 9:42:47 to 9:46:22 is not helpful, and we've probably had delays like this since my old e02d1489a5 (#560), which landed in 4.6.
This commit introduces a "ClusterOperator bumped `versions[name=operator]`" trigger to break out of the cool-off sleep.
There's plenty of room to be more precise here.  For example, you could currently have a `versions[name=operator]` bump during the sync loop that the CVO did notice, and that queued …

Bug 2117033: pkg/cvo/sync_worker: Trigger new sync round on ClusterOperator versions[name=operator] changes

---

pkg/cvo/availableupdates.go
pkg/cvo/cvo.go
pkg/cvo/cvo_scenarios_test.go
pkg/cvo/cvo_test.go
pkg/cvo/sync_worker.go
pkg/payload/payload.go
pkg/payload/payload_test.go
pkg/start/start_integration_test.go

by first restoring https://github.com/openshift/cluster-version-operator/commit/0b8e83f9f405b0b62e781edbb0d1c87c5f2cc45b.
Ths issue was that the 'SyncWorkerStatus.Architecture' was being clobbered
at
https://github.com/openshift/cluster-version-operator/blob/9d57cfc612dec8e6b5d67d34e5f00474f3c09032/pkg/cvo/sync_worker.go#L860.

Restore 'Pull arch from payload' and fix

---

install/0000_90_cluster-version-operator_02_servicemonitor.yaml

Add missing namespace labels `openshift-cluster-version` to alerting rules to comply with 
the [style guidance](https://github.com/openshift/enhancements/blob/master/enhancements/monitoring/alerting-consistency.md#style-guide). Alerts should include a namespace label indicating the alert's source.

Bug 2010365: OpenShift Alerting Rules Style-Guide Compliance

---

lib/capability/capability.go

We'd already been sorting the two status properties before attaching them to ClusterVersion, but we also use some of the underlying data internally, e.g. in `TestCVO_InitImplicitlyEnabledCaps`.  By sorting after we build each slice, we don't need to worry about slice-consumers being surprised by order instability.

lib/capability: Sort all slices after building them

---

pkg/cvo/status.go

reported in [OCPBUGS-569](https://issues.redhat.com/browse/OCPBUGS-569), cvo history method `prune` return is not assigned to status.history, resulting in history not being pruned, and `prune` method running in loops as seen in cvo log:  
```
cluster-version-operator-669594b4cd-h89ch.log:I0824 13:24:37.889213       1 status_history.go:69] Pruning an older update of less importance version 4.12.0-0.nightly-2022-08-23-223922 at index 99 with rank -99.990000.
cluster-version-operator-669594b4cd-h89ch.log:I0824 13:24:52.886216       1 status_history.go:69] Pruning an older update of less importance version 4.12.0-0.nightly-2022-08-23-223922 at index 99 with rank -99.990000.
cluster-version-operator-669594b4cd-h89ch.log:I0824 13:25:07.887131       1 status_history.go:69] Pruning an older …
```

OCPBUGS-569: CVO History Pruner return not assigned to config.Status.History

---

pkg/cvo/cvo.go
pkg/cvo/upgradeable.go

This pull request will synchronize the Upgradeable status more frequently when the precondition checks on the payload start failing and will improve the logging regarding synchronization of the upgradeable status. The more frequent synchronization will happen for a given period after the precondition checks start to fail.
A precondition check originally could be failing for at least `optr.minimumUpdateCheckInterval` time because of `Upgradeable==false`. The `Upgradeable==false` could have been potentially already resolved (cluster operator reporting `Upgradeable==false` just momentarily) during the duration resulting in necessary waiting for up to `optr.minimumUpdateCheckInterval` for the next synchronization. Synchronize the upgradeable status more frequently in case of failing …

Bug 2006611: Upgrade takes too much time when upgrading via --to-image

---

lib/resourcemerge/core.go
lib/resourcemerge/core_test.go

This recently started breaking [4.10-to-4.11-to-4.12 updates][1] with [the first failing run][2] like:
```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.12-upgrade-from-stable-4.11-from-stable-4.10-e2e-aws-sdn-upgrade/1562409104817786880/artifacts/e2e-aws-sdn-upgrade/gather-extra/artifacts/clusterversion.json | jq -r '.items[].status.conditions[] | .lastTransitionTime + " " + .type + "=" + .status + " " + .reason + ": " + .message'
2022-08-24T12:12:13Z RetrievedUpdates=False NoChannel: The update channel has not been configured.
2022-08-24T12:12:13Z ReleaseAccepted=True PayloadLoaded: Payload loaded version="4.12.0-0.ci-2022-08-24-061508" image="registry.build03.ci.openshift.org/ci-op-2v4w1wbk/release@ …
```

OCPBUGS-575: lib/resourcemerge/core: Reconcile seccompProfile in ensurePodSecurityContext

---

install/0000_00_cluster-version-operator_01_admingate_configmap.yaml

Reverting the last revert as we want to add this just before 4.12 feature freeze. This reverts commit f27e7b57c1a2bee0a4670887c233899c32126491.

OCPBUGS-1251: Add admin-gate ack-4.11-kube-1.25-api-removals-in-4.12

---

pkg/cvo/cvo_scenarios_test.go
pkg/cvo/sync_worker.go
pkg/cvo/testdata/payloadtest-3/release-manifests/0000_10_a_file.yaml
pkg/cvo/testdata/payloadtest-3/release-manifests/image-references
pkg/cvo/testdata/payloadtest-3/release-manifests/release-metadata

from `SyncWorker.updateLoadStatus` and `SyncWorker.Update`. This then keeps SyncWorker locked during the entire `Update` call not allowing occurrences as described by https://bugzilla.redhat.com/show_bug.cgi?id=2118289#c1. With this change `SyncWorker` must already be locked before `SyncWorker.updateLoadStatus` is called. But currently only `SyncWorker.Update` calls `SyncWorker.updateLoadStatus`.

OCPBUGS-1402: pkg/cvo/sync_worker.go: remove Lock/Unlock

---

pkg/cvo/sync_worker.go

that are returned as `UpdateEffectReport` during payload initialization by allowing payload initialization to complete successfully and setting the `ClusterStatusFailing` condition.

Bug 1951835: Handle report only sync errors

---

pkg/cvo/sync_worker.go

Originally, all component operators were responsible for creating their own ClusterOperator, and we'd just watch to make sure we were happy enough with what they did.  However, on install, or when updating to a version that added a new component, we could have timelines like:
1. CVO creates a namespace for an operator.
2. CVO creates ... for the operator.
3. CVO creates the operator Deployment.
4. Operator deployment never comes up, for whatever reason.
5. Admin must-gathers.
6. Must gather uses ClusterOperators for discovering important stuff, and because the ClusterOperator doesn't exist yet, we get no data about why the deployment didn't come up.
So in 2a469e37c1 (#318), we added ClusterOperator pre-creation to get:
1. CVO pre-creates ClusterOperator for an operator.
2. CVO creates the …

OCPBUGS-1636: pkg/cvo/sync_worker: Pre-create ClusterOperator in reconciling-mode too

---

bootstrap/bootstrap-pod.yaml
install/0000_00_cluster-version-operator_03_deployment.yaml
install/0000_90_cluster-version-operator_02_servicemonitor.yaml
pkg/cincinnati/cincinnati.go
pkg/cvo/sync_worker.go

Reverts openshift/cluster-version-operator#844
Avoid:
```
bootkube.sh[8231]: Failed to create "0000_00_cluster-version-operator_03_deployment.yaml" deployments.v1.apps/cluster-version-operator -n openshift-cluster-version: Deployment.apps "cluster-version-operator" is invalid: spec.template.spec.containers[0].env[2].valueFrom: Invalid value: "": must specify one of: `fieldRef`, `resourceFieldRef`, `configMapKeyRef` or `secretKeyRef`
```
Sorry for overriding CI without looking closely enough :(

Revert "Fix ups from gofmt 1.19 and yamllint"

---

Dockerfile

Fixes:
```console
$ ./hack/build-image.sh
...
[1/2] STEP 4/4: RUN hack/build-go.sh;     mkdir -p /tmp/build;     cp _output/linux/$(go env GOARCH)/cluster-version-operator /tmp/build/cluster-version-operator
...
vendor/sigs.k8s.io/json/internal/golang/encoding/json/encode.go:1249:12: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
vendor/sigs.k8s.io/json/internal/golang/encoding/json/encode.go:1255:18: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
```

Dockerfile: Bump to Go 1.18

---

pkg/cvo/cvo.go
pkg/cvo/cvo_scenarios_test.go
pkg/cvo/cvo_test.go
pkg/cvo/status.go
pkg/cvo/sync_test.go
pkg/cvo/sync_worker.go
pkg/payload/precondition/clusterversion/recommendedupdate.go
pkg/payload/precondition/clusterversion/recommendedupdate_test.go

by merging in https://github.com/wking/cluster-version-operator/commit/5613130c7817b6d37773ea1c1a3028b8546185c1#diff-854cd9a3f8419eead65da9983aa2a7efb35a8e76a8eeb20082304987a05c0c01R76 and adding pieces to get the accepted risks message into history by first saving in `SyncWorkerStatus.loadPayloadStatus`.

Bug 2033499: Populate acceptedRisks in ClusterVersion History

---

pkg/payload/precondition/clusterversion/recommendedupdate.go
pkg/payload/precondition/precondition.go
pkg/payload/precondition/precondition_test.go

With this change we will not fail precondition checks when a version is not in available updates. So users should be able to upgrade to any version with approriate client side overrides. For example using --allow-explicit-upgrade and --to-imge flags in "oc adm upgrade"

OCPBUGS-2727: Do not fail precondition check for UnknownUpdate

---

lib/resourcemerge/apps_test.go
lib/resourcemerge/batch_test.go
lib/resourcemerge/core_test.go
lib/resourcemerge/meta_test.go
lib/resourcemerge/rbac_test.go

These warnings are annoying for anyone new (like me) who opens the codebase in GoLand, and prevent new code from being efficiently checked while writing.
- `pointer.BoolPtr` -> `pointer.Bool`
- `pointer.Int*Ptr` -> `pointer.Int*`
- `diff.ObjectReflectDiff` -> `cmp.Diff`

resourcemerge: cleanup deprecated function calls

---

lib/resourcemerge/core.go
lib/resourcemerge/core_test.go
pkg/start/start.go

The problem was identified to be a broken substitution of internal load balancer into `KUBERNETES_SERVICE_HOST` by Trevor and David (see my [JIRA comment](https://issues.redhat.com/browse/OCPBUGS-1458?focusedCommentId=21090756&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-21090756) and related [Slack thread](https://coreos.slack.com/archives/C011CSSPBLK/p1664925995946479?thread_ts=1661182025.992649&cid=C011CSSPBLK)).
CVO injects the LB hostname in the [`ModifyDeployment`](https://github.com/openshift/cluster-version-operator/blob/dc1ad0aef5f3e1b88074448d21445a5bddb6b05b/lib/resourcebuilder/apps.go#L19) fine, but then the deployment gets applied in [`ApplyDeployment`](https://github.com/openshift/cluster-version-operator/blob/dc1ad0aef5f3e1b88074448d21445a5bd …

OCPBUGS-1458: Allow CVO to update `KUBERNETES_SERVICE_HOST` with LB address

---

Dockerfile

I think the bare `Dockerfile` only supports developer usecases (https://github.com/openshift/cluster-version-operator/pull/871), we build the product with `Dockerfile.rhel`. We should use the modern base images even for this scenario.
I have considered using upstream registry.access.redhat.com pullspec (https://catalog.redhat.com/software/containers/ubi8/5c647760bed8bd28d0e38f9f?container-tabs=gti) which should also allow unauthenticated access, but we use registry.ci.openshift.org in the first `FROM` anyway, and UBI images are periodically mirrored to registry.ci.openshift.org so we get the same stuff.

Build CVO from UBI8 instead of obsolete `origin-v4.0:base`

---

README.md

CVO-specific user-targeting content will always partially overlap with other
documentation, like OCP docs about upgrades, the [`dev-guide`](https://github.com/openshift/enhancements/tree/master/dev-guide/cluster-version-operator) in the openshift/enhancement
repository and perhaps other locations. Ideally we want avoid duplicating other
content here as much as possible: only cover the basics or really CVO-specific
content in this repository, and link elsewhere when needed.
The goals of the README are the following:
1. Inform a technical, knowledgeable user about how CVO operates
2. Inform a technical, knowledgeable user about how to interact with CVO in a cluster
3. Redirect an incoming developer to another suitable location for information
about development, testing and contributing
4. …

OTA-560: Modernize README.md to be user-centered

---

install/0000_90_cluster-version-operator_02_servicemonitor.yaml
pkg/cvo/metrics.go
pkg/cvo/metrics_test.go

To give users sub-component granularity about why they're getting a critical alert.
I'm still avoiding the cardinality hit of including the full message in the metric, because we don't want to load Prometheus down with *that* many time-series.  For message-level granularity, users still have to follow the `oc ...` or web-console links from the alert `description`.

OTA-844: pkg/cvo/metrics: Add 'reason' to cluster_operator_up

---

pkg/payload/precondition/precondition.go
pkg/payload/precondition/precondition_test.go

Avoid errors like:
```console
$ oc get -o json clusterversion version | jq -r '.status.history[0].acceptedRisks'
Forced through blocking failures: Precondition "ClusterVersionRecommendedUpdate" failed because of "UnknownUpdate": RetrievedUpdates=True (), so the update from 4.13.0-0.okd-2022-12-11-064650 to 4.13.0-0.okd-2022-12-13-052859 is probably neither recommended nor supported.
```
Instead, tweak the logic from 481bcde393 (#856), and only append the `Forced through blocking failures:` prefix when the forcing was required.

OCPBUGS-4986: pkg/payload/precondition: Do not claim warnings would have blocked

---

pkg/payload/payload.go
pkg/payload/payload_test.go
pkg/payload/render.go
pkg/payload/task.go
pkg/payload/task_graph_test.go
pkg/payload/task_test.go

- remove redundant `DeepEqual` checks (followup to a nit in https://github.com/openshift/cluster-version-operator/pull/860)
- update deprecated `ioutil.*` calls
- replace `ObjectReflectDiff` with `cmp.Diff`

pkg/payload: code cleanups

---

pkg/clusterconditions/cache/cache_test.go
pkg/clusterconditions/mock/mock.go
pkg/clusterconditions/mock/mock_test.go

Looking at [`Cache.Match()`](https://github.com/openshift/cluster-version-operator/blob/master/pkg/clusterconditions/cache/cache.go#L63-L148) implementation, the `c.Condition.Match()` on [L133](https://github.com/openshift/cluster-version-operator/blob/master/pkg/clusterconditions/cache/cache.go#L133) can be called with `targetCondition=nil` and that seems to be intentional. In tests, `c.Condition` is a mock, which did not expect that pointer to be `nil` and dereferenced it, resulting in an occassional panic in tests like https://github.com/openshift/cluster-version-operator/pull/871#issuecomment-1348927131. The fix stores the full pointer (its deepcopy to avoid sharing that memory) in the mock instead.
I needed to restructure the tests a little to allow adding a nil parameter testcase

tests: fix rare nil dereference in `TestCache`

---

pkg/cvo/updatepayload.go

When we separated payload load from payload apply (https://github.com/openshift/cluster-version-operator/pull/683) the context used for the retrieval changed as well. It went from one that was constrained by syncTimeout (2 -4 minutes) [1] to being the unconstrained shutdownContext [2]. However if "force" is specified we explicitly set a 2 minute timeout in RetrievePayload. This commit creates a new context with a reasonable timeout for RetrievePayload regardless of "force".
[1] https://github.com/openshift/cluster-version-operator/blob/57ffa7c610fb92ef4ccd9e9c49e75915e86e9296/pkg/cvo/sync_worker.go#L605
[2] https://github.com/openshift/cluster-version-operator/blob/57ffa7c610fb92ef4ccd9e9c49e75915e86e9296/pkg/cvo/cvo.go#L413

Bug 2090680: pkg/cvo/updatepayload.go: timeout payload retrieval

---

pkg/cincinnati/cincinnati.go
pkg/cincinnati/cincinnati_test.go
pkg/cvo/availableupdates.go
pkg/cvo/egress.go

So that it's easier to guess at the fraction of requests that are CVOs vs. other clients.  I'd like to set this for our signature requests too (`vendor/github.com/openshift/library-go/pkg/verify/store/sigstore`), but that would take some library-go requests first.

pkg/cincinnati: Set User-Agent for Cincinnati requests

---

pkg/cvo/updatepayload.go

Reverts openshift/cluster-version-operator#846
Apparently introduced a regression that blocks some upgrades, opening to allow `/payload` testing of `periodic-ci-openshift-release-master-nightly-4.13-e2e-metal-ipi-upgrade-ovn-ipv6`. If it fixes the job we should consider merging the revert and work on the fix with clean main branch.

Revert "pkg/cvo/updatepayload.go: timeout payload retrieval"

---

pkg/cvo/cvo.go
pkg/cvo/upgradeable.go
pkg/cvo/upgradeable_test.go

Previously, the throttling reused the `minimumUpdateCheckInterval` value which is derived from the full CVO minimum sync period. This value is set between 2m and 4m at CVO startup. This period is unecessarily long and bad for UX, things happen with a delay and our own testcase expects upgradeability to be propagated in 3 minutes at worst.
Hardcode the throttling to 2m to prevent flapping on flurries but allow changes to propagate deterministically faster. We will still get a bit of non-determinisim from sync periods and requeueing, so this change should not cause any periodic API-hammering.
I'd like to backport this change to 4.11 where it causes CI flakes in `[bz-Cluster Version Operator] Verify presence of admin ack gate blocks upgrade until acknowledged` test.

OCPBUGS-5505: Set upgradeability check throttling period to 2m

---

pkg/start/start.go

Previously, `resyncPeriod` returned a `func() time.Duration` that did the actual computation, but there is no place where the function is stored and used later as a callback. It was always immediately called after creation.
Remove one layer of unnecessary indirection and make `resyncPeriod` returns the computed sync period directly.

start.go: simplify code for computing sync period

---

lib/validation/validation.go
pkg/cvo/cvo_test.go

Narrowly catching up with c80bd024a8 (#684, [4.10][1]), which removed that option from the implementation.  Having the validation code living so far from the implementation code makes us more vulnerable to this kind of divergence, but I'll leave larger refactorings to follow-up work.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1878925

lib/validation: Drop "a previous version" from desiredUpdate validation

---

lib/resourceapply/apiext.go
lib/resourcemerge/apiext.go
lib/resourcemerge/apiext_test.go
lib/resourcemerge/helper.go

This pull request will fix CVO's behavior of removing the `caBundle` field of CRDs when reconciling manifests.
This pull request references the bug OCPBUGS-702 [1].
---
*   lib/resourcemerge: Fix removing `caBundle` field of CRDs when `...inject-cabundle=true`
Currently, the users can omit the `caBundle` field in the CRDs and set the `service.beta.openshift.io/inject-cabundle=true` annotation so that the given `caBundle` field is managed by the `service-ca` controller (this functionality is not limited only to CRDs) [2].
However, the CVO is not aware of this feature. CVO, when reconciling such CRD, sees an empty `caBundle` field in the given release manifest, and CVO then removes any value in the existing applied CRD so it matches the release manifest semantically.
This commit makes the …

OCPBUGS-702: Fix removing `caBundle` field of CRDs when `...inject-cabundle=true`

---

lib/resourcedelete/helper.go
pkg/autoupdate/autoupdate.go
pkg/cvo/availableupdates.go
pkg/cvo/cvo.go
pkg/payload/precondition/clusterversion/upgradeable.go

Replaces the default serialization format `2023-01-18 18:31:06.806926942 +0100 CET m=+18.871775150` with `2023-01-18T16:31:37Z` in log messages.
I do not believe the nanoseconds, monotonic clock reading and timezone have value in log messages. RFC3339 makes logs more concise and better readable.

logging: consistently use RFC3339 in log messages

---

pkg/cvo/upgradeable.go

Previously, the throttling reused the `minimumUpdateCheckInterval` value
which is derived from the full CVO minimum sync period. This value is
set between 2m and 4m at CVO startup. This period is unecessarily long
and bad for UX, things happen with a delay and our own testcase expects
upgradeability to be propagated in 3 minutes at worst.
Hardcode the throttling to 2m (lower bound of previous behavior) to
prevent flapping on flurries but allow changes to propagate
deterministically faster. We will still get a bit of non-determinisim
from sync periods and requeueing, so this change should not cause any
periodic API-hammering.
This is a partial backport of https://github.com/openshift/cluster-version-operator/pull/882. The `release-4.11` branch does not contain the …

[release-4.11] OCPBUGS-5882: Set upgradeability check throttling period to 2m

---

hack/generate-lib-resources.py
lib/resourceapply/admissionregistration.go
lib/resourcebuilder/resourcebuilder.go
lib/resourcedelete/admissionregistration.go
lib/resourcemerge/admissionregistration.go
lib/resourcemerge/admissionregistration_test.go
lib/resourceread/resourceread.go

This pull request will fix hotlooping on `ValidatingWebhookConfiguration`.
The hotlooping was caused by missing CVO-side defaulting of the `ValidatingWebhookConfiguration` resources and by missing CVO awareness of the `service-ca` operator who is responsible for injecting the CA bundle into resources annotated by `service.beta.openshift.io/inject-cabundle=true` [1].
This pull request adds the defaulting and ensures that the CVO ignores the respective `CABundle` fields inside the webhooks when the annotation is set.
This pull request references bug 2089138 [2].
[1] https://docs.openshift.com/container-platform/4.12/security/certificates/service-serving-certificate.html
[2] https://bugzilla.redhat.com/show_bug.cgi?id=2089138

Bug 2089138: CVO hotloops on ValidatingWebhookConfiguration

---

pkg/cvo/sync_worker.go

Cleaning up a log line I'd fumbled in 9222fa9a66 (#818).  Changes:
* Remove redundant `so do not notify about`, because `no need to inform about` covers that with more clarity (we're not informing, and even if we did, it would be useless, because there's already a pending notification in place).
* Use `Infof` to get the `%s` formatted in, avoiding:
...no need to inform about: %sCluster operator...
`

pkg/cvo/sync_worker: Fix "The sync worker already has a pending notification" formatting

---

pkg/cvo/updatepayload.go
pkg/cvo/updatepayload_test.go

The `RetrievePayload` performs two operations: verification and download. Both can take a non-trivial amount of time to terminate, up to "hanging" where CVO needs to abort the operation. The verification result can be ignored when upgrade is forced. The CVO calls `RetrievePayload` with a context that does not set a deadline, so `RetrievePayload` previously set its own internal deadline, common for both operations. This led to a suboptimal behavior on forced upgrades, where "hanging" verification could eat the whole timeout budget, got cancelled but its result was ignored (because of force). The code tried to proceed with download but that immediately aborts because of the expired context.
Improve timeouts in `RetrievePayload` for both input context states: with and without deadline. If …

Bug 2090680: RetrievePayload: Improve timeouts and cover behavior with tests

---

lib/resourceapply/imagestream.go
lib/resourcemerge/imagestream.go
lib/resourcemerge/imagestream_test.go

This pull request will fix hotlooping on `ImageStream` and fixes the logging happening during updating `ImageStream` resources.
The hotlooping was caused by missing CVO-side defaulting of the `ImageStream` resources. In `4.12`, a new import value, `importMode`, has been added to the `importPolicy` parameter of image streams [1]. Previously, the CVO wasn't aware of its default value `Legacy` [1].
This pull request also improves the logging when handling the `ImageStream` resources. Previously, the logged diff wasn't helpful in  discovering the issue that caused the update of the resource (this change is similar to the change introduced for improving logging for deployments in commit https://github.com/openshift/cluster-version-operator/commit/c58385eea897b5af790e4dd36103e978e7e4c597). And …

OCPBUGS-6097: CVO hotloops on ImageStream and logs the information incorrectly

---

install/0000_90_cluster-version-operator_02_servicemonitor.yaml

We grew a `ReleaseAccepted` condition in 7221c93dfc (#683), which [landed in 4.11][1] and was [backported to 4.10.8][2].  However, in order to notice a `ReleaseAccepted!=True` condition, users would need to be [checking `oc adm upgrade`][3] or [watching the web-console interface][4].  With this change, we add an alert, so admins can have push-notification to supplement those polling approaches.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1822752#c49
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=2064991#c7
[3]: https://bugzilla.redhat.com/show_bug.cgi?id=2065507
[4]: https://issues.redhat.com//browse/OCPBUGS-3069

install/0000_90_cluster-version-operator_02_servicemonitor: Add ClusterReleaseNotAccepted

---

pkg/cvo/availableupdates.go

When changing channels it's possible that multiple new conditional update risks will need to be evaluated.  For instance, a cluster running 4.10.34 in a 4.10 channel might only have to evaluate `OpenStackNodeCreationFails`.  But when the channel is changed to a 4.11 channel multiple new risks require evaluation and the evaluation of new risks was throttled at one every 10 minutes.  This means if there are three new risks it may take up to 20 minutes after the channel has changed for the full set of conditional updates to be computed.
With this commit, I'm sorting the conditional updates in version-descending order, which is the order we've used in the ClusterVersion status since c9dd4792f3ef (#663).  This prioritizes the longest-hop risks.  For example, 4.10.34 currently has the following …

OCPBUGS-5469: pkg/cvo/availableupdates: Prioritize conditional risks for largest target version

---

pkg/cvo/cvo.go
pkg/payload/precondition/clusterversion/rollback.go
pkg/payload/precondition/clusterversion/rollback_test.go

We have occasional cases where admins attempt a rollback, despite [long-standing docs][1]:
> Only upgrading to a newer version is supported. Reverting or rolling back your cluster to a previous version is not supported. If your update fails, contact Red Hat support.
Deeper history for that content [here][2], [here][3], and [here][4].  With this commit, we'll refuse to accept rollbacks unless the administrator sets `Force` to waive our guards.
[1]: https://docs.openshift.com/container-platform/4.12/updating/understanding-openshift-updates.html
[2]: https://github.com/openshift/openshift-docs/blame/60ae4bf339756189b7e72491b79d53764cbe85fa/modules/update-service-overview.adoc#L33
[3]: https://github.com/openshift/openshift-docs/pull/31432/commits/10515fe97929f5a9c344f8e519f823f941ed7e5c
[4]: …

OTA-941: pkg/payload/precondition/clusterversion/rollback: New precondition

---

cmd/main.go
install/0000_00_cluster-version-operator_03_deployment.yaml
pkg/cincinnati/cincinnati.go
pkg/cincinnati/cincinnati_test.go
pkg/clusterconditions/always/always.go
pkg/clusterconditions/clusterconditions.go
pkg/clusterconditions/clusterconditions_test.go
pkg/clusterconditions/promql/promql.go
pkg/clusterconditions/standard/standard.go
pkg/cvo/availableupdates.go
pkg/cvo/cvo.go

The kubelet consistently resolves the name.  This change allows the CVO to use the kubelet's DNS configuration.

Update dnsPolicy to allow consistent resolution of the internal LB

---

pkg/cvo/status.go

Status is synchronized every 15 seconds, and each call is currently logged with a lot of metadata, including full `status`. The metadata include words `error` and `Failure` which usually have zero values, but the words get noticed by filters and people eyeballing the logs:
```
I0405 09:24:26.084143       1 status.go:170] Synchronizing status errs=field.ErrorList(nil) status=&cvo.SyncWorkerStatus{Generation:55, Failure:error(nil), Done:830, Total:830, Completed:107, Reconciling:true, Initial:false, VersionHash:"yroEV7BhWJo=", Architecture:"amd64", LastProgress:time.Date(2023, time.April, 5, 9, 21, 50, 486422587, time.Local), Actual:v1.Release{Version:"4.12.10", Image:"quay.io/openshift-release-dev/ocp-release@sha256:db976910d909373b1136261a5479ed18ec08c93971285ff760ce75c6217d3943", …
```

syncStatus: Reduce verbosity when syncing nothing of interest

---

hack/generate-lib-resources.py
lib/resourceapply/batch.go
lib/resourcebuilder/resourcebuilder.go
lib/resourcedelete/batch.go
lib/resourcemerge/batch.go
lib/resourcemerge/batch_test.go

Currently the CVO hotloops on `CronJob` resources.
The issue was caused by the missing defaulting of these resources.
To fix this issue I have added the handling for `CronJob` resources so they are not reconciled as `generic` resources. This has then allowed me to introduce the defaulting.
To fix this issue I have also updated the applying for `Job` resources because its logic can be then reused as part of the fix for the hotlooping on `Cronjob` resources.  While updating the applying for `Job` I have added missing defaulting,  and I have added reconciling of fields that were added later in the development, and the CVO was not reconciling them.
This pull request references https://issues.redhat.com/browse/OCPBUGS-9070

OCPBUGS-9070: Fix hotlooping on Cronjob resources

---

cmd/main.go
install/0000_00_cluster-version-operator_03_deployment.yaml
pkg/cincinnati/cincinnati.go
pkg/cincinnati/cincinnati_test.go
pkg/clusterconditions/always/always.go
pkg/clusterconditions/clusterconditions.go
pkg/clusterconditions/clusterconditions_test.go
pkg/clusterconditions/promql/promql.go
pkg/clusterconditions/standard/standard.go
pkg/cvo/availableupdates.go
pkg/cvo/cvo.go

This is a cherry-pick of https://github.com/openshift/cluster-version-operator/pull/923
The 8af3ba94774cba60e91cd5d231eee9bd8f37d40c commit did not apply cleanly and I had to manually adjust for missing https://github.com/openshift/cluster-version-operator/pull/839 and https://github.com/openshift/cluster-version-operator/pull/860, but the changes were not that invasive, so I do not consider the resulting change to be too risky compared to https://github.com/openshift/cluster-version-operator/pull/923

OCPBUGS-12182: Update dnsPolicy to allow consistent resolution of the internal LB

---

hack/test-prerequisites.go
pkg/cincinnati/cincinnati.go
pkg/cvo/metrics.go
pkg/start/start_integration_test.go

Saw this failing in https://github.com/openshift/cluster-version-operator/pull/929 , not exactly sure what mechanism makes these appear  on their own :monocle_face: 
Also bumping the linter in https://github.com/openshift/release/pull/40480 because why not.

Code cleanups for golangci-lint failures

---

pkg/cvo/metrics.go

Since bd8d7cf7f4 (#204), the `from_version` value has been the penultimate `Completed` history entry.  So a cluster with a history like:
1. Version D, Partial
2. Version C, Completed
3. Version B, Partial
4. Version A, Completed
will have `version="C"` and `from_version="A"`.

pkg/cvo/metrics: Doc from_version semantics for cluster_version{type="completed"}

---

Dockerfile

This Dockerfile is not used in CI [1] nor in product builds [2], so it may as
well be external contributor friendly and do not contain private CI
registry pullspecs.
We should use 1.20 but that image does not exist yet [3]. I do not see
any reason why to keep using UBI8 in this Dockerfile, so I bumped it to
UBI9.
[1] https://github.com/openshift/release/blob/7d59d083a7aa5f2aec28e807681a4b4e9ccdd088/ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-master.yaml#L17-L25
[2] https://github.com/openshift-eng/ocp-build-data/blob/openshift-4.14/images/cluster-version-operator.yml#L3
[3] https://github.com/openshift/release/pull/40567

Dockerfile: bump to 1.19 and use public UBI pullspec

---

pkg/clusterconditions/cache/cache.go
pkg/clusterconditions/cache/cache_test.go
pkg/cvo/availableupdates.go

There are opportunities to improve this area overall but we probably do not want to do that in the scope of OCPBUGS-13308

OCPBUGS-13308: Simplify user-facing messages on risk evaluation throttling

---

lib/resourcemerge/apps.go

With this change, we now reconcile all of these:
```console
$ git --no-pager grep -A42 'type DeploymentSpec struct' vendor/k8s.io/api/apps/v1 | grep json
vendor/k8s.io/api/apps/v1/types.go-     Replicas *int32 `json:"replicas,omitempty" protobuf:"varint,1,opt,name=replicas"`
vendor/k8s.io/api/apps/v1/types.go-     Selector *metav1.LabelSelector `json:"selector" protobuf:"bytes,2,opt,name=selector"`
vendor/k8s.io/api/apps/v1/types.go-     Template v1.PodTemplateSpec `json:"template" protobuf:"bytes,3,opt,name=template"`
vendor/k8s.io/api/apps/v1/types.go-     Strategy DeploymentStrategy `json:"strategy,omitempty" patchStrategy:"retainKeys" protobuf:"bytes,4,opt,name=strategy"`
vendor/k8s.io/api/apps/v1/types.go-     MinReadySeconds int32 `json:"minReadySeconds,omitempty" …
```

OCPBUGS-18567: lib/resourcemerge/apps: Cover paused and other spec properties in EnsureDeployment

---

pkg/clusterconditions/mock/mock.go
pkg/cvo/availableupdates.go
pkg/cvo/availableupdates_test.go

The code in `evaluateConditionalUpdates` correctly uses `SetStatusCondition` to set conditions, which only updates the
`LastTransitionTime` field when `Status` differs between the original and updated state. Previously though, the original state always contained empty conditions, because conditional updates are always obtained from OSUS and the fresh structure was never updated with existing conditions from the in-cluster status.

availableupdates: do not reset lastTransitionTime on unchanged status

---

cmd/start.go
pkg/cincinnati/cincinnati_test.go
pkg/clusterconditions/clusterconditions.go
pkg/clusterconditions/clusterconditions_test.go
pkg/clusterconditions/promql/promql.go
pkg/clusterconditions/standard/standard.go
pkg/cvo/availableupdates.go
pkg/cvo/cvo.go
pkg/start/start.go

This pull request will add new flags and some minor logic to enable the CVO to evaluate conditional updates in HyperShift.
This pull request references the https://issues.redhat.com/browse/OTA-854

OTA-854: Add configurable CVO knobs for risk-evaluation PromQL target

---

pkg/clusterconditions/mock/mock.go
pkg/clusterconditions/promql/promql.go
pkg/cvo/availableupdates.go
pkg/cvo/availableupdates_test.go

Picking #939 back to 4.14, with some minor manual edits because I'm not bringing back #926 (a feature adding support for new environments).  I am bringing back #964, because that was fixing existing behavior (so not a feature) and having it made the rebase slightly easier.

OCPBUGS-19737: pkg/clusterconditions/promql: Warm cache with 1s delay

---

pkg/clusterconditions/cache/cache.go

When:
* It has been longer than `MinBetweenMatches` since our last wrapped evaluation,
* There is no alternative key stale enough (`MinForCondition`) to steal the evaluation, and
* The currently requested key is not cached yet, e.g. because it was recently declared as a new risk to a cluster-version operator which had recently run all the other relevent risks from the current Cincinnati response.
avoid crashing with:
```console
$ grep -B1 -A15 'too fresh' previous.log
I0927 12:07:55.594222       1 cincinnati.go:114] Using a root CA pool with 0 root CA subjects to request updates from https://raw.githubusercontent.com/shellyyang1989/upgrade-cincy/master/cincy-conditional-edge-invalid-promql.json?arch=amd64&channel=stable-4.15&id=dc628f75-7778-457a-bb69-6a31a243c3a9&version=4.15.0-0.test-202 …
```

OCPBUGS-19868: pkg/clusterconditions/cache: Avoid panic on all-fresh-cache evaluation

---

pkg/cvo/sync_worker.go

The capability is new in 4.14, via openshift/api@d557f9784b (openshift/api#1462) and ba3aeb9ab9 (#950).  But as pointed out in [OCPBUGS-20321](https://issues.redhat.com/browse/OCPBUGS-20321), 4.14 releases do not declare any manifests as linked to the new capability:
```console
$ oc adm release extract --to manifests quay.io/openshift-release-dev/ocp-release:4.14.0-rc.5-x86_64
Extracted release payload from digest sha256:042899f17f33259ed9f2cfc179930af283733455720f72ea3483fd1905f9b301 created at 2023-10-10T18:00:08Z
$ grep -ohr 'capability.openshift.io/name:.*' manifests | sort | uniq
capability.openshift.io/name: baremetal
capability.openshift.io/name: Console
capability.openshift.io/name: CSISnapshot
capability.openshift.io/name: ImageRegistry
capability.openshift.io/name: Insights …
```

OCPBUGS-20321: pkg/cvo/sync_worker: Always enable the DeploymentConfig capability

---

install/0000_90_cluster-version-operator_02_servicemonitor.yaml
pkg/cvo/availableupdates.go
pkg/cvo/availableupdates_test.go
pkg/cvo/metrics.go
pkg/cvo/metrics_test.go
pkg/cvo/status.go

Add a new `cluster_version_conditional_updates_recommended_conditions_seconds` which, for each conditional update known to CVO, reports how long (in seconds) is the `Recommended` condition on that update in the current state (this is the time since the conditions' `lastTransitionTime`). The metric is labelled with version, reason and status. Note that `lastTransitionTime` was not correctly maintained by CVO until fixed in #964.
Using this metric, we create an alert that fires when there is an update that is in an `Unknown` status for more than 50 minutes and this state is maintained for 10 minutes.
The metric was created slightly more generic than the alert would have needed. Technically the CVO could compute the "bad" state right away and just flap a 0/1 metric, but I believe the metrics …

OCPBUGS-9050: Alert on failing conditional update risk evaluation

---

install/0000_90_cluster-version-operator_02_servicemonitor.yaml

Fixing a `ClusterOperatorDown` typo from bbcc33dfa3 (#868) that I'd carried forward into `ClusterReleaseNotAccepted` in 734b9c5df9 (#906).

OCPBUGS-8079: install/0000_90_cluster-version-operator_02_servicemonitor: Drop $ from ${{

---

lib/resourcemerge/rbac.go

control-plane manages the cluster role rules if `aggregationRule` are set.

OCPBUGS-19391: do not reconcile rules if aggregationRule is set

---

pkg/cvo/sync_worker.go

initial reduction for https://issues.redhat.com/browse/OTA-923

OCPBUGS-23377: to reduce log noise, only log sync_worker messages on retry or payload change

---

pkg/clusterconditions/promql/promql.go

This pull request will create GET requests to the Prometheus API server.
The currently used Prometheus client library doesn't allow explicit specification of the type of requests (GET/POST) being made to the Prometheus API server. The tenancy port of the `thanos-querier.openshift-monitoring.svc` service being utilized in self-managed HyperShift requires different permissions depending on the type of requests. This PR will make sure that the CVO uses GET requests to the PromQL service.
The used Prometheus client library attempts POST requests, and on 501 and 405 response status codes fall-backs to GET requests. This PR will return the 501 status code even before sending a given HTTP POST request, resulting in a GET request being made as a fallback by the used library.
An alternative is to …

OTA-855: Create GET requests to the Prometheus API server

---

pkg/cvo/sync_worker.go

We've including verification-failure details for forced updates since 5ad3c1434f (#763), but had not been including them in logs or other output in the "we aren't forcing, so this blocks the update's acceptance" case.  This commit adds the detail to the Event, so it's available, but keeps only the high-level message in the `RetrievePayload` status output (which feeds the `ReleaseAccepted` condition in ClusterVersion), because while the low-level are useful for debugging, they're pretty chatty for condition consumers that are more interested in just knowing basically why the update request isn't being accepted.

OCPBUGS-25055: pkg/cvo/sync_worker: Verification-failure details for unforced updates too

---

pkg/cvo/cvo.go
pkg/payload/precondition/clusterversion/rollback.go
pkg/payload/precondition/clusterversion/rollback_test.go

From [OTA-553](https://issues.redhat.com/browse/OTA-553), Lala, Scott, and Subin all agreed that rollbacks to the cluster's previous release should not be blocked, as long as the previous and current version had the same `major.minor` version (i.e. "within a z-stream", using `x.y.z` naming for `major.minor.patch`). We agreed to ignore whether the previous history entry is `Completed` or `Partial`, expecting that most users who are interested in rolling back will make that decision at the first sign of trouble, and not after attempting a few roll-forward retargets.

OCPBUGS-24535: pkg/payload/precondition/clusterversion/rollback: Allow previous version within z-stream

---

pkg/cvo/availableupdates.go

965bfb2844 (#939) pivoted from "every `syncAvailableUpdates` round that does anything useful has a fresh Cincinnati pull" to "some `syncAvailableUpdates` rounds have a fresh Cincinnati pull, but others just re-eval some `Recommended=Unknown` conditional updates".  Then `syncAvailableUpdates` calls `setAvailableUpdates`.
However, until this commit, `setAvailableUpdates` had been bumping `LastAttempt` every time, even in the just-re-eval conditional updates" case.  That meant we never tripped the:
```go
} else if !optrAvailableUpdates.RecentlyChanged(optr.minimumUpdateCheckInterval) {
klog.V(2).Infof("Retrieving available updates again, because more than %s has elapsed since %s", optr.minimumUpdateCheckInterval, optrAvailableUpdates.LastAttempt.Format(time.RFC3339))
```
condition to trigger …

OCPBUGS-25708: pkg/cvo/availableupdates: Only bump LastAttempt on Cincinnati pulls

---

lib/resourcemerge/os.go
pkg/cvo/internal/operatorstatus.go

Previously, COs were only precreated so once they existed, they never got any updates from the manifest, like annotations. Our future work relies on CO annotations to recognize platform COs from OLM-created ones but ancient clusters like build02 were created when COs were not annotated at all.

OCPBUGS-26014: clusterOperatorBuilder: Reconcile metadata on COs

---

pkg/cvo/internal/operatorstatus.go
pkg/payload/task.go

Keeping the original upgrade start time may cause CVO spuriously warn about waiting on a CO for over 40 minutes, in a scenario like this:
1. CVO upgrades etcd / KAS very early in the upgrade, noting the time when it started to do that
2. These two COs upgrade successfully and upgrade proceeds
3. Eventually cluster starts rebooting masters and etcd/KAS go degraded
4. CVO compares current time against the noted time, discovers its more than 40 minutes and starts warning about it.

OCPBUGS-25862: CO health: only track current in-progress upgrade start

---

pkg/cvo/sync_test.go
pkg/cvo/sync_worker.go

Code refactors and cleanups that were previously part of https://github.com/openshift/cluster-version-operator/pull/1005, extracted to a separate PR because the actual OCPBUGS-7714 is possibly sensitive and we may want to review, discuss and investigate it (in the future) without the interference of the refactors.
Recommended to review per-commit.
- sync_worker.go: Refactor `calculateNext` and pull up lock
- sync_worker.go: add comments about lock assumptions
- sync_worker.go: lock access to w.status
- sync_worker.go: get rid of `StatusReporter` interface
- sync_worker.go: simplify `apply()` signature
- sync_worker.go: simplify `syncPayload` signature

OCPBUGS-7714: Refactor & improve SyncWorker lock code

---

lib/resourcemerge/os.go
pkg/cvo/internal/operatorstatus.go

Reverts openshift/cluster-version-operator#1021
Possibly related to [OCPBUGS-27822](https://issues.redhat.com/browse/OCPBUGS-27822)?  Let's see...
/hold

OCPBUGS-27822: Revert "[release-4.14] OCPBUGS-27175: clusterOperatorBuilder: Reconcile metadata on COs"

---

pkg/cvo/availableupdates.go
pkg/cvo/availableupdates_test.go

Until / unless we merge https://github.com/openshift/api/pull/1577, conditional risk names may not be valid condition reason strings, so we need to check them and use a generic (new `RiskAppliesToCluster`) reason instead.
I took the opportunity and wrote tests and refactored the code slightly (make it easily testable from a single place and get rid of extensive branching logic that was hard to read). I suggest reviewing individual commits.

OCPBUGS-18454: Avoid using risk names as condition reasons when invalid

---

pkg/cvo/cvo.go
pkg/cvo/cvo_test.go
pkg/cvo/status.go

updateClusterVersionStatus: add godoc and linewrap signature
---
status: work with `ClusterVersionStatus` instead of `ClusterVersion`
Status-computing methods can only read and modify `ClusterVersionStatus`
instead of `ClusterVersion`, resulting in simpler code and lower chance
of making a mistake.
---
status: uncouple `updateClusterVersionStatus` with `Operator`
`Operator` is a pretty beefy object with access to half of the universe, but `updateClusterVersionStatus` only uses its member very little. It reads its `release` member and calls its `getAvailableUpdates` method.
We can uncouple the long method by passing these two members as parameters. It is slightly awkward for the `getAvailableUpdates` method but I think the benefits outweight this.
---
status: extract status update logic to …

OTA-1159: [1/x] Refactor syncStatus for testability

---

install/0000_90_cluster-version-operator_02_servicemonitor.yaml

These two are low-hanging fruit because the appropriate runbooks already exist. They are a bit vague which is understandable because each CO is different but some links are better than no links, and having links may increase pressure on improving these runbooks.
This does not fully resolve OCPBUGS-14246 because we are still missing a runbook for `ClusterVersionOperatorDown`

NO-JIRA: Runbook URLs for ClusterOperatorDown and ClusterOperatorDegraded

---

cmd/start.go
pkg/cvo/availableupdates.go
pkg/cvo/availableupdates_test.go
pkg/cvo/cvo.go
pkg/cvo/cvo_test.go
pkg/cvo/metrics.go
pkg/start/start.go

[XCMSTRAT-513](https://issues.redhat.com/browse/XCMSTRAT-513) includes [OTA-1185](https://issues.redhat.com/browse/OTA-1185) pitching local update services in managed regions. However, HyperShift [currently][3] forces ClusterVersion `spec.upstream` empty.  This commit is part of making the upstream update service configurable on HyperShift, so those clusters can hear about and assess known issues with updates in environments where the default https://api.openshift.com/api/upgrades_info update service is not accessible, or in which an alternative update service was desired for testing or policy reasons. This includes [OTA-1185](https://issues.redhat.com/browse/OTA-1185), mentioned above, but would also include any other instance of disconnected/restricted-network use. The alternative for …

OTA-1210: *: Add --update-service command-line option

---

pkg/cvo/reconciliation_issues.go
pkg/cvo/reconciliation_issues_test.go
pkg/cvo/status.go
pkg/cvo/status_test.go

Walk the error's tree using [Go's][1]:
```go
Unwrap() error
Unwrap() []error
```
APIs.  Also include `Errors()`, because that's what our `k8s.io/apimachinery` implementation currently uses:
```console
$ git --no-pager grep '^func.* [A-Z].*) \[]error {' -- vendor
vendor/k8s.io/apimachinery/pkg/runtime/error.go:func (e *strictDecodingError) Errors() []error {
vendor/k8s.io/apimachinery/pkg/runtime/helper.go:func DecodeList(objects []Object, decoders ...Decoder) []error {
vendor/k8s.io/apimachinery/pkg/util/errors/errors.go:func (agg aggregate) Errors() []error {
vendor/k8s.io/client-go/tools/clientcmd/validation.go:func (e errConfigurationInvalid) Errors() []error {
```
Probably worth doing something to stabile-sort children.  Possibly doing something to get more `UpdateError` / `Manifest`. …

OTA-1159: pkg/cvo: Render status.Failure in ReconciliationIssues

---

install/0000_90_cluster-version-operator_02_servicemonitor.yaml
pkg/cvo/metrics.go
pkg/cvo/metrics_test.go
pkg/start/start.go

By adding `cluster_operator_up` handling for ClusterVersion, with `version` as the component name, the same way we handle `cluster_operator_conditions`.  This plugs us into `ClusterOperatorDown` (based on `cluster_operator_up`) and `ClusterOperatorDegraded` (based on both `cluster_operator_conditions` and `cluster_operator_up`).
I've adjusted the `ClusterOperatorDegraded` rule so that it fires on ClusterVersion `Failing=True` and does not fire on `Failing=False`.  Thinking through an update from before:
1. Outgoing CVO does not serve `cluster_operator_up{name="version"}`.
2. User requests an update to a release with this change.
3. New CVO comes in, starts serving `cluster_operator_up{name="version"}`.
4. Old `ClusterOperatorDegraded` no matching …

OCPBUGS-9133: pkg/cvo/metrics: Connect ClusterVersion to ClusterOperatorDown and ClusterOperatorDegraded

---

pkg/payload/task.go

cb4e0375e6 (#88) dropped the last consumer.

NO-ISSUE: pkg/payload/task: Drop unused Requeued property

---

pkg/cvo/reconciliation_issues.go

Allow ClusterVersion `status` consumers to make their own decisions about how long to wait before complaining about a slow-to-update ClusterOperator.

OTA-1160: pkg/cvo/reconciliation_issues: Publish ClusterOperator transitionStart

---

install/0000_00_cluster-version-operator_01_admingate_configmap.yaml

Add admin-gate ack-4.15-kube-1.29-api-removals-in-4.16
Require the admin ack for updating to next version of OpenShift

OCPBUGS-33984: Add admin-gate for OCP 4.16

---

.ci-operator.yaml
Dockerfile.rhel
go.mod

Reverts openshift/cluster-version-operator#1047
Might be leading to failures like:
```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.17-e2e-aws-ovn-fips/1800906552731766784/artifacts/e2e-aws-ovn-fips/ipi-install-install/artifacts/log-bundle-20240612161314.tar | tar -tvz | grep 'cluster-version.*log'
-rw-r--r-- core/core     54653 2024-06-12 09:13 log-bundle-20240612161314/bootstrap/containers/cluster-version-operator-bd9f61984afa844dcd284f68006ffc9548377c045eff840096c74bcdcbe5cca3.log
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-openshift-release-master-nightly-4.17-e2e-aws-ovn-fips/1800906552731766784/artifacts/e2e-aws-ovn-fips/ip …
```

Revert "OCPBUGS-34287: Updating cluster-version-operator-container image to be consistent with ART for 4.17"

---

install/0000_00_cluster-version-operator_03_deployment.yaml

[OCPBUGS-36817](https://issues.redhat.com/browse/OCPBUGS-36817)
Manual cherry-pick of [#1038](https://github.com/openshift/cluster-version-operator/pull/1038)

[release-4.15] OCPBUGS-36817: Set required-scc for openshift workloads

---

pkg/cvo/sync_worker.go
pkg/cvo/sync_worker_test.go

After the CVO has started and its worker goroutines are starting to work, a panic may occur due to a data race.
Originally (at 961873d6), the `SyncWorker.Start()` method was exclusively waiting for a signal on the `SyncWorker.notify` channel from the `SyncWorker.Update()` method before attempting the first application of a payload.
After the `Start()` method got the signal, its required values were already initialized by the `SyncWorker.Update()` method, such as the `SyncWorker.work` field.
However, the 9222fa9a introduced another section of the CVO that can signal the `SyncWorker.notify` channel.
The `SyncWorker.NotifyAboutManagedResourceActivity()` method now signals the channel upon an activity on a managed resource. This signal may occur before the `SyncWorker.Update()` has finished. …

OCPBUGS-32678: Fix a panic caused by a data race

---

lib/capability/capability_test.go

KnownClusterVersionCapabilities is the referential list of known capabilities. ClusterVersionCapabilitySetCurrent/DefaultCapabilitySet can change in time. As in https://github.com/openshift/api/pull/1954.

no-jira: TestSetCapabilities: use KnownClusterVersionCapabilities for known keys instead of picking DefaultCapabilitySet

---

pkg/cvo/cvo_scenarios_test.go

KnownClusterVersionCapabilities is the referential list of known capabilities. ClusterVersionCapabilitySetCurrent/DefaultCapabilitySet can change in time. As in https://github.com/openshift/api/pull/1954.
To unblock https://github.com/openshift/cluster-version-operator/pull/1066.

no-jira: TestCVO: set known caps from configv1.KnownClusterVersionCapabilities

---

pkg/payload/payload.go
pkg/payload/render.go
vendor/github.com/openshift/api/config/.codegen.yaml
vendor/github.com/openshift/api/config/install.go
vendor/modules.txt

Address [OCPBUGS-37770][1], where a ClusterImagePolicy manifest from the `cluster-update-keys` repository (openshift/cluster-update-keys#58) was not part of the bootstrap-rendered MachineConfigs, but was part of the production MachineConfigs.  That kind of skew causes trouble for the machine-config operator, as in [this run][2]:
```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_cluster-api-provider-aws/519/pull-ci-openshift-cluster-api-provider-aws-master-e2e-aws-ovn-techpreview/1818614625273384960/artifacts/e2e-aws-ovn-techpreview/gather-extra/artifacts/machineconfigpools.json | jq -r '.items[0].status.conditions[] | select(.type == "NodeDegraded").message'
Node ip-10-0-107-110.us-east-2.compute.internal is …
```

OCPBUGS-37770: pkg/payload/render: Include release image (Cluster)ImagePolicy

---

cmd/render.go
pkg/payload/render.go

455abd6acc (#1076) taught the `render` command to extract (Cluster)ImagePolicy manifests so the bootstrap machine-config controller could consume them.  That got the cluster-update-keys ClusterImagePolicy manifest working on `TechPreviewNoUpgrade` installs, because that feature-set needs the manifest to get into the boostrap MCC to avoid "missing MachineConfig `rendered-...`" hash mismatches.
But the ClusterImagePolicy manifest and CustomResourceDefinition are currently feature-gated, so the boostrap ClusterImagePolicy render broke default feature-set installs, [like][1]:
```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_cluster-update-keys/60/pull-ci-openshift-cluster-update-keys-master-e2e-aws/1821360664451485696/art …
```

OCPBUGS-37770: cmd/render: Add --feature-gate-manifest-path option

---

pkg/cvo/cvo_scenarios_test.go
pkg/cvo/status.go
pkg/cvo/status_test.go

Various errors get propagated to users, such as the summarized task
graph error. For example, in the form of the message in the Failing
condition. However, update errors set with the update effect of
`UpdateEffectNone` can confuse users, as these primarily informing
messages get displayed together with valid update errors that heavily
impact the update. This can result in a message such as:
```
{
"lastTransitionTime": "2023-06-20T13:40:12Z",
"message": "Multiple errors are preventing progress:\n* Cluster
operator authentication is updating versions\n* Could not update
customresourcedefinition \"alertingrules.monitoring.openshift.io\"
(512 of 993): the object is invalid, possibly due to local cluster
configuration",
"reason": "MultipleErrors",
"status": "True",
"type": "Failing"
}
```
The …

OCPBUGS-15200: Filter out shallowly `UpdateEffectNone` errors from a `MultipleErrors` message in the Failing condition

---

pkg/cvo/cvo.go
pkg/cvo/cvo_scenarios_test.go
pkg/cvo/sync_test.go
pkg/cvo/sync_worker.go

If the CVO pod gets restarted after a user sends a cluster
upgrade request with `--to-image`, the desired should not ALWAYS be
taken from `.Spec.DesiredUpdate`, e.g., when the targeting payload is blocked
on some precondition check failure.
The user request will be written to `cv.spec.desiredUpdate` where only
the `image` field is set, i.e., the `Version` field is empty.
If the CVO gets restarted, then
1. The desied [1] from `cv.spec.desiredUpdate` will be used to set
`w.status.Actual` [2] and then applied to `cv.status.desired`.
2. When the next `optr.sync()` happens, the precondition check may become
non-blocking [3] as the `Version` field is empty now.
3. CVO will then start an upgrade that should have been blocked.
[1]. https://github.com/openshift/cluster-version-operator/blob/1995380 …

OCPBUGS-35228: Fix desired before sync_worker's work is initialized

---

go.mod
go.sum
vendor/github.com/openshift/api/config/v1/types_cluster_version.go
vendor/github.com/openshift/api/config/v1/types_feature.go
vendor/github.com/openshift/api/config/v1/types_network.go
vendor/github.com/openshift/api/config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-CustomNoUpgrade.crd.yaml
vendor/github.com/openshift/api/config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-Default.crd.yaml
vendor/github.com/openshift/api/config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-DevPreviewNoUpgrade.crd.yaml
vendor/github.com/openshift/api/config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversions-TechPreviewNoUpgrade.crd.yaml
vendor/github.com/openshift/api/config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_featuregates.crd.yaml
vendor/github.com/openshift/api/config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_infrastructures-Default.crd.yaml
vendor/github.com/openshift/api/config/v1/zz_generated.crd-manifests/0000_10_config-operator_01_networks.crd.yaml
vendor/github.com/openshift/api/config/v1/zz_generated.featuregated-crd-manifests.yaml
vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
vendor/github.com/openshift/api/config/v1alpha1/types_cluster_image_policy.go
vendor/github.com/openshift/api/config/v1alpha1/types_image_policy.go
vendor/github.com/openshift/api/config/v1alpha1/zz_generated.featuregated-crd-manifests.yaml
vendor/github.com/openshift/api/features/features.go
vendor/github.com/openshift/api/security/v1/consts.go
vendor/modules.txt

Catching up with openshift/api#2023, and a backport-ish of 6abe8bb8be (#1086).  Generated with:
```console
$ GOPROXY=direct go get github.com/openshift/api@release-4.17
$ go mod tidy
$ go mod vendor
$ git add -A go.* vendor
```
all using:
```console
$ go version
go version go1.22.2 linux/amd64
```
where `GOPROXY=direct` avoids [a caching delay][2]:
> *I committed a new change (or released a new version) to a repository, why isn't it showing up when I run `go get -u` or `go list -m --versions`?*
>
> In order to improve our services' caching and serving latencies, new versions may not show up right away. If you want new code to be immediately available in the mirror, then first make sure there is a semantically versioned tag for this revision in the underlying source repository. Then …

OCPBUGS-41642: vendor: Update openshift/api to pick up the v4.17 capability sets

---

pkg/cvo/status_history.go
pkg/cvo/status_history_test.go
pkg/cvo/upgradeable.go
pkg/payload/precondition/clusterversion/upgradeable.go
pkg/payload/precondition/clusterversion/upgradeable_test.go

https://issues.redhat.com/browse/OCPBUGS-42880

OCPBUGS-42880: Upgradeable=False should not block a 4.(y+1).z to 4.(y+1).z' retarget

---

pkg/cvo/cvo.go
pkg/cvo/cvo_scenarios_test.go
pkg/cvo/sync_test.go
pkg/cvo/sync_worker.go

This PR cherry-picks the commit from https://github.com/openshift/cluster-version-operator/pull/1075 as it introduced `sortedKnownCaps` which is used by the other commits that are backported from https://github.com/openshift/cluster-version-operator/pull/1089.

[release-4.16] OCPBUGS-43964: Fix desired before sync_worker's work is initialized

---

pkg/payload/task_graph.go
pkg/payload/task_graph_test.go

[task graph test: do not wait after cancelation](https://github.com/openshift/cluster-version-operator/commit/1c71a50c41cc35a553908eae448a731dbe02bc4b)
Given correct synchronization I do not see any value in the `Sleep`, it just makes the test much slower:
```console
$ go test --count 10 --run TestRunGraph/cancelation_without_task_errors  ./pkg/payload/
ok  	github.com/openshift/cluster-version-operator/pkg/payload	10.041s
$ git checkout ocpbugs-22442-test-run-graph-mid-task-cancellation-flake
...
$ go test --count 10 --run TestRunGraph/cancellation_without_task_errors  ./pkg/payload/
ok  	github.com/openshift/cluster-version-operator/pkg/payload	0.043s
```
---
[task graph: simplify code](https://github.com/openshift/cluster-version-operator/commit/df39a81014aa4360b16496ac671a7db2dcdf2f6d) …

NO-JIRA: task graph: test speedup and code cleaup

---

pkg/payload/task_graph.go
pkg/payload/task_graph_test.go

Occasionally, the test flaked with the following:
```
--- FAIL: TestRunGraph (1.04s)
--- FAIL: TestRunGraph/mid-task_cancellation_with_work_in_queue_does_not_deadlock (0.01s)
task_graph_test.go:943: unexpected error: [context canceled context canceled]
```
The failure happened because the test saw two `context canceled` errors, but expected only one such error to happen:
```
errors: []string{"context canceled"}
```
The test is processing a graph with two independenent nodes, processed without paralellism:
```
nodes: []*TaskNode{
{Tasks: tasks("a1", "a2", "a3")},
{Tasks: tasks("b")},
},
maxParallelism: 1,
```
The test is configured to signal the cancellation in the middle of processing task `a2`, and expects:
- a2 task to return successfuly
- a3 task to start, but return the `context …

OCPBUGS-22442: Fix `TestRunGraph/mid-task_cancellation_with_work_in_queue_does_not_deadlock` flake

---

pkg/cvo/availableupdates.go
pkg/cvo/cvo_test.go

[`RemoteFailed`, `ResponseFailed`, and `ResponseInvalid` reasons are all server-side issues][a].  This commit makes clusters more resilient to OpenShift Update Service (OSUS) issues by preserving the cache of previously-retrieved advice for up to 24 hours, while we wait for OSUS to recover (or proxies or other network configuration between the cluster and its OSUS to be fixed).  OSUS advice does not change often, and the only risk of acting on stale advice is that you might not hear about recently-declared [Conditional Update risks][1].  The `RetrievedUpdates` condition should be displayed in the update-selection user interfaces, and [the `CannotRetrieveUpdates` alert][b] will be firing, so cluster administrators will be aware of the risk of stale data, and can decide whether to wait for …

OCPBUGS-44018: pkg/cvo/availableupdates: Preserve update advice on update-service failures

---

pkg/cvo/cvo.go
pkg/cvo/cvo_scenarios_test.go
pkg/cvo/sync_test.go
pkg/cvo/sync_worker.go

This PR is generated by 
```
$ git cherry-pick a411e9da061c6ba1b71bb2b1ce5972a8e0c03307 6906bbfb9d075450e93680cdf8ccfc51d4e62c24 e3a05d439a609e1eb5fc3c63c70a7825ee48f41f a1ee1ca6c050b752c622264c6903823210671334 ae4e180b19aa4f67f2a53785813ff040ee1690da
```
and then fix [the backported unit test](https://github.com/openshift/cluster-version-operator/pull/1097/files#diff-6cca1696ca6d83b25f5baf586b99602d32827c05c4276dd03ebfcb6825ff2558R2865) `TestCVO_UpgradePayloadStillInitializing` by the following editting:
```console
git --no-pager diff 
diff --git a/pkg/cvo/cvo_scenarios_test.go b/pkg/cvo/cvo_scenarios_test.go
index c195e26c..9f060195 100644
--- a/pkg/cvo/cvo_scenarios_test.go
+++ b/pkg/cvo/cvo_scenarios_test.go
@@ -33,9 +33,18 @@ import (
)
var architecture string
+var sortedCaps = …
```

OCPBUGS-44328: Fix desired before sync_worker's work is initialized

---

pkg/featuregates/featuregates.go

Fixing my sloppy copy/paste typo from 28b3b40869 (#1110).

MULTIARCH-4559: pkg/featuregates: Fix statusReleaseArchitecture enablement

---

pkg/cvo/updatepayload.go

[pkg/cvo/updatepayload.go: Set openshift.io/required-scc: privileged for version pods](https://github.com/openshift/cluster-version-operator/pull/1106/commits/9761a5b5ca847acece8f7537f78ef8a089faec6e)
Utilize the `openshift.io/required-scc` annotation [1] to pin the required SCC to
`version` pods. This will ensure that any existing custom SCCs in the cluster will
not have an effect on the `version` pods.
The `privileged` default SCC [2] was chosen as the pod accesses and modifies
host `/etc/` files. To do that, a pod must run as root and must also pass SELinux
permission checks. This is currently achieved by the pod running as a privileged
root. For such permission, the `privileged` default SCC is required.
Using the `hostmount-anyuid` default SCC is not sufficient for the existing code …

OCPBUGS-31462: Set `openshift.io/required-scc: privileged` annotation in `version` pods

---

pkg/cvo/cvo.go
pkg/payload/precondition/clusterversion/gianthop.go
pkg/payload/precondition/clusterversion/gianthop_test.go

From our [docs][1]:
> Due to fundamental Kubernetes design, all OpenShift Container Platform updates between minor versions must be serialized. You must update from OpenShift Container Platform `<4.y>` to `<4.y+1>`, and then to `<4.y+2>`. You cannot update from OpenShift Container Platform `<4.y>` to `<4.y+2>` directly. However, administrators who want to update between two even-numbered minor versions can do so incurring only a single reboot of non-control plane hosts.
This commit adds a new precondition that enforces that policy, so cluster admins who run `--to-image ...` don't hop straight from `4.y.z` to `4.(y+2).z'` or similar without realizing that they were outpacing testing and policy.
[1]: https://docs.openshift.com/container-platform/4.17/updating/updating_a_cluster/control-plane …

OCPBUGS-44860: pkg/payload/precondition/clusterversion: New GiantHop update precondition

---

install/0000_00_update-status-controller_00_namespace-DevPreviewNoUpgrade.yaml
install/0000_00_update-status-controller_01_serviceaccount-DevPreviewNoUpgrade.yaml
install/0000_00_update-status-controller_02_rbac-DevPreviewNoUpgrade.yaml
install/0000_00_update-status-controller_03_deployment-DevPreviewNoUpgrade.yaml

---
- Namespace
- ServiceAccount
- Role that allows read, watch & update ConfigMaps (+binding)
- ClusterRole that allows read & watch ConfigVersions (+rolebinding)
- Deployment
Squashed review commits:
USC: Do not tolerate taints
The original Deployment was copied from CVO which contained a bunch of
strong tolerations. It does not seem USC needs to be this robust against
node conditions and can be easily evicted if necessary.
https://github.com/openshift/enhancements/blob/master/CONVENTIONS.md#taints-and-tolerations
USC: Use `openshift-user-critical` priority class
The original USC deployment was copied from CVO which is obviously very
important component and should be protected from OOM kills and preemption
but USC does not seem to need it. …

OTA-1269: USC: Add `DevPreviewNoUpgrade`-gated manifests

---

CONTRIBUTING.md

From OCPBUGS-45922:
> Review your repository content for any assumptions related to branch naming. In rare scenarios, this may require opening pull requests against the target git repository to adopt the new "main" branch convention. For any such PR:
>    Ensure the PR is on /hold.
>    Ensure the PR is lgtm and approved.
>    Link the PR to this ticket by adding the ticket ID to the PR's title.

OCPBUGS-45922: CONTRIBUTING.md: Rename `master` to `main`

---

pkg/cvo/updatepayload.go

A manual cherry-pick of the https://github.com/openshift/cluster-version-operator/pull/1106 PR for the `release-4.18` branch.

OCPBUGS-46410: Set `openshift.io/required-scc`: privileged annotation in `version` pods

---

hack/test-usc-integration.sh

Required by https://github.com/openshift/release/pull/60990/files
/cc @petr-muller 
/auto-cc

OTA-1427: Add hack/test-usc-integration.sh to start testing USC in CI

---

cmd/start.go
lib/resourcemerge/batch_test.go

These issues are not currently detected by the `ci/prow/lint` job as the job uses the version `v1.54.2` of the `golangci-lint` tool [[1](https://github.com/openshift/release/blob/2576d99d6c11a20958b44ec140e1f382982e0433/ci-operator/config/openshift/cluster-version-operator/openshift-cluster-version-operator-main.yaml#L2-L5)].
It is needed to update the tool to support go `1.23`, which will be introduced in https://github.com/openshift/cluster-version-operator/pull/1147 PR. However, updating the tool right now in https://github.com/openshift/release/pull/61253 would cause the `ci/prow/lint` [presubmit to fail on PRs](https://github.com/openshift/release/pull/61253#issuecomment-2634805522).
Fix the lint issues in this PR. After that, we will update the `golangci-lint` tool. No disruptions …

OTA-209: Resolve lint issues

---

pkg/updatestatus/controlplaneinformer.go
pkg/updatestatus/controlplaneinformer_test.go
pkg/updatestatus/nodeinformer.go
pkg/updatestatus/nodeinformer_test.go
pkg/updatestatus/updatestatuscontroller.go
pkg/updatestatus/updatestatuscontroller_test.go

- Make the informer -> usc message contain an identification of the informer who sent it
- Decouple insight UIDs from usc assumptions (informers no longer need to prefix UIDs with `usc-`)
- Emulate by-informer partitioning by encoding informer in ConfigMap key name
- Make USC cope with invalid messages by dropping them (liberal in what it accepts)
- Extract code to create valid messages from insights assuming insights are valid
- NodeInformer needs to be adapted for the changes too.
There are changes in the API that separate a `ControlPlaneInsight` and `WorkerPoolsInsight`, these had to be partially accommodated in the chance, but not fully. We can expect the API to change a bit (or a lot, based on the current round of review) so I do not feel like investing effort to polish this up 100%.

OTA-1418: USC: Make messages more robust and decoupled

---

pkg/updatestatus/updatestatuscontroller.go
pkg/updatestatus/updatestatuscontroller_test.go

Assume the informers, in each message, include a list of all active insight IDs that infomer knows about. The Status API can then drop the unknown insights formerly reported by that informer (=insights present in the API but not known to be active by the responsible informer)
This is only a part of [OTA-1418](https://issues.redhat.com//browse/OTA-1418). The remaining changes will be as follows:
- Do not drop the unknown insights right away but make them expire after some some time of not being renewed (handle the case where informer starts up and starts sending messages about insights as it discovers them)
- Actually make the informers remember their insights and populate the `knownInsights` field of the message
- Add additional `deletedInsights` field to the message, to allow informers …

OTA-1418: USC: Drop unknown messages from the API

---

pkg/updatestatus/updatestatuscontroller.go
pkg/updatestatus/updatestatuscontroller_test.go

When we first see an insight in the API that is no longer known by the informer that originally reported it, mark it for expiration instead of dropping it right away. If it becomes known again, unmark the expiration. If it does not become known until expired, drop it from the API.

OTA-1418: USC: Drop unknown insights after grace period 

---

pkg/cvo/availableupdates_test.go
pkg/cvo/cvo_test.go

Those tests fail on e.g., the arm64 machine.
```console
$ go test -v -count 1 ./pkg/cvo/... | rg 'SKIP:|Skipped'
availableupdates_test.go:167: Skipped the test on arm64
--- SKIP: TestSyncAvailableUpdates (0.00s)
cvo_test.go:2786: Skipped the test case "no operator or ClusterVersion upstream uses the default update service" on arm64
cvo_test.go:2786: Skipped the test case "report an error condition when channel isn't set" on arm64
cvo_test.go:2786: Skipped the test case "report an error condition when no current version is set" on arm64
cvo_test.go:2786: Skipped the test case "report an error condition when the http server reports an error" on arm64
cvo_test.go:2786: Skipped the test case "set available updates and clear error state when success and empty" on arm64
cvo_test.go:2786: …
```

NO-JIRA: Fix a few AMD64-oriented tests on Non-AMD64 machines

---

pkg/cvo/status_history.go
pkg/cvo/upgradeable.go
pkg/payload/precondition/clusterversion/upgradeable.go
pkg/payload/precondition/clusterversion/upgradeable_test.go

https://issues.redhat.com/browse/OTA-861
This one will be rebased after https://github.com/openshift/cluster-version-operator/pull/1094 is merged.

OTA-861: Generate an accepted risk for Y-then-Z upgrade

---

go.mod
go.sum
vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
vendor/github.com/openshift/api/config/v1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusteroperators.crd.yaml
vendor/github.com/openshift/api/features/features.go
vendor/modules.txt

Generally, conditions are a listType map, which allows multiple actors via SSA to set individual conditions. We are building a suite of controllers which we plan to set low lever conditions, and have a aggregate controller look at these lower level conditions to set our top level conditions. Our intention was to use SSA, but without these markers, we can only write the whole list of conditions on each update, and this will cause conflicts.
Existing clients should not be affected as they already write the entire list.
This is based on #1147 for now as I needed the updated deps
/hold need to merge https://github.com/openshift/api/pull/2194 before we can continue
Opening this so that we can double check E2Es with this change

NO-JIRA: Update ClusterOperator Status Conditions to `listType=map`

---

lib/capability/capability.go
lib/capability/capability_test.go
pkg/cvo/cvo.go
pkg/cvo/sync_worker.go

Before we decide to use sets (K8S has util lib for sets) instead of maps for the fields from https://github.com/openshift/cluster-version-operator/blob/eb7599ced2534e0b15707947d94fe6bb5766e2cd/lib/capability/capability.go#L17-L21 
we may still do refactoring like these to improve the readability:
- Removed an unused constant `CapabilityAnnotation` and removed `DefaultCapabilitySet` and use its reference directly.
- Removed `setKnownCapabilities()` and `GetKnownCapabilities()`. Use `configv1.KnownClusterVersionCapabilities` instead. The logic is changed/improved a bit: A capability not enabled in all capSets is considered known now, but not before.
- The args`existingEnabled` and `alwaysEnabled` were handled in the same way in the function `SetCapabilities`. We removed the `alwaysEnabled` …

NO-JIRA: Refactor for readability

---

lib/capability/capability.go
lib/capability/capability_test.go
pkg/cvo/status.go
pkg/cvo/sync_worker.go
pkg/payload/payload.go
pkg/payload/payload_test.go

Follow up https://github.com/openshift/cluster-version-operator/pull/1131#pullrequestreview-2540096609
Will rebase after https://github.com/openshift/cluster-version-operator/pull/1131 gets in.

NO-JIRA: Rename fields in ClusterCapabilities for readability

---

Dockerfile
Dockerfile.rhel
install/0000_00_cluster-version-operator_02_configuration-DevPreviewNoUpgrade.yaml
pkg/dependencymagnet/doc.go
vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversionoperators-CustomNoUpgrade.crd.yaml
vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.crd-manifests/0000_00_cluster-version-operator_01_clusterversionoperators-DevPreviewNoUpgrade.crd.yaml
vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.crd-manifests/0000_10_config-operator_01_imagecontentsourcepolicies.crd.yaml
vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.crd-manifests/0000_10_etcd_01_etcdbackups-CustomNoUpgrade.crd.yaml
vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.crd-manifests/0000_10_etcd_01_etcdbackups-DevPreviewNoUpgrade.crd.yaml
vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.crd-manifests/0000_10_etcd_01_etcdbackups-TechPreviewNoUpgrade.crd.yaml
vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.crd-manifests/0000_10_operator-lifecycle-manager_01_olms.crd.yaml
vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.crd-manifests/doc.go
vendor/modules.txt

https://github.com/openshift/cluster-version-operator/pull/1137 will be broken down into smaller PRs.
This the initial PR.
For more information regarding the resources, see https://github.com/openshift/enhancements/blob/master/enhancements/update/cvo-log-level-api.md.
This pull request references https://issues.redhat.com//browse/OTA-209.

OTA-209: Add `ClusterVersionOperator` manifests

---

pkg/updatestatus/controlplaneinformer_test.go
pkg/updatestatus/nodeinformer.go
pkg/updatestatus/nodeinformer_test.go

This is to address the following comments from the review [1]:
[1]. https://github.com/openshift/cluster-version-operator/pull/1136#issuecomment-2621934987

OTA-1427: Recompute node insights when MC/MCP changes

---

pkg/cvo/updatepayload.go
pkg/payload/image.go

These usually either succeed or give `os.IsNotExist`, but in [some cases can return errors like][1]:
Unable to download and prepare the update: stat /etc/cvo/updatepayloads/7WNaprXJNWTsPAepCHJ00Q/release-manifests/release-metadata: permission denied.
To make it easier to debug those situations, this commit adds context to errors near `ValidateDirectory` calls, so it's more clear that the issue is the CVO's attempts to read `/etc/cvo/...` failing, and not an error with the `version-...` Pod, registry access, etc.
Also while I'm in this space, I've replaced the old `errors.Wrap` in `ImageForShortName` with `fmt.Errorf(...%w, ...)`, now that the Go standard libraries support error-wrapping like that.  One fewer 3rd-party dependency call-site.
[1]: …

OCPBUGS-52258: pkg/cvo/updatepayload: Context around ValidateDirectory calls

---

pkg/updatestatus/nodeinformer.go
pkg/updatestatus/nodeinformer_test.go

This PR addressed the remained comments from https://github.com/openshift/cluster-version-operator/pull/1144
In the 1st commit it improves the error handling on `reconcileAllNodes()` (See [1] for details).
Prior to this commit, the event on MC/MCP will be re-queued if `reconcileAllNodes()`
hits an error. However, `syncMachineConfig()` (or `syncMachineConfigPool` respectively)
is stateful, i.e., the result replies on the content of the caches that might be
changed from the original event.
With the commit, a special event stays between an MC/MCP event and `reconcileAllNodes()`.
An error from the latter will re-queue the special event which basically means triggering
another run of `reconcileAllNodes()`.
The 2nd commit is to improve the code either for better readability or for better APIs …

OTA-1427: Reconcile all nodes via a special event

---

pkg/payload/render_test.go
pkg/payload/testdata/TestRenderManifest_expected_cvo_deployment.yaml

The diff makes sense, of course.
```console
$ cat ./install/0000_00_cluster-version-operator_03_deployment.yaml | grep '{{'
image: {{.ReleaseImage}}
- "--release-image={{.ReleaseImage}}"
value: {{ .ClusterProfile }}
$ diff -Naupr install/0000_00_cluster-version-operator_03_deployment.yaml pkg/payload/testdata/TestRenderManifest_expected_cvo_deployment.yaml    
--- install/0000_00_cluster-version-operator_03_deployment.yaml 2024-11-06 13:30:42
+++ pkg/payload/testdata/TestRenderManifest_expected_cvo_deployment.yaml        2025-03-27 09:59:50
@@ -25,11 +25,11 @@ spec:
automountServiceAccountToken: false
containers:
- name: cluster-version-operator
-        image: {{.ReleaseImage}}
+        image: quay.io/cvo/release:latest
imagePullPolicy: IfNotPresent
args:
- "start"
-          - …
```

NO-JIRA: Add unit test for renderManifest

---

install/0000_00_cluster-version-operator_00_namespace.yaml
install/0000_00_cluster-version-operator_03_deployment.yaml
install/0000_00_cluster-version-operator_04_service.yaml
install/0000_00_update-status-controller_00_namespace-DevPreviewNoUpgrade.yaml
install/0000_00_update-status-controller_03_deployment-DevPreviewNoUpgrade.yaml
install/0000_90_cluster-version-operator_02_servicemonitor.yaml
pkg/payload/testdata/TestRenderManifest_expected_cvo_deployment.yaml

See [the rehearsal](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/63274/rehearse-63274-pull-ci-openshift-cluster-version-operator-main-yamllint/1905387572654247936) for the details.
The remained two will be fixed by https://github.com/openshift/cluster-version-operator/pull/1171/files#diff-d545314649981da131e9fa5eec88fd1fc37172eb51389689aa227464191bb133R72
```
$ yamllint -v && yamllint --strict -d '{extends: default, rules: {indentation: {indent-sequences: consistent}, document-start: disable, line-length: disable}}' ./install
yamllint 1.35.1
./install/0000_00_cluster-version-operator_03_deployment.yaml
73:20     error    too many spaces inside braces  (braces)
73:36     error    too many spaces inside braces  (braces)
```

NO-JIRA: Fix some issues identified by yamllint

---

install/0000_00_cluster-version-operator_03_deployment.yaml
pkg/payload/testdata/TestRenderManifest_expected_cvo_deployment.yaml

CVO manifests present in the payload contain plain templating `{{yada}}` placeholders where final manifests expect to contain strings, and because `{ }` has meaning in YAML, these manifests are invalid without template engine processing. 
CVO manifests are applied by CVO itself, which processes them through the templating engine, which makes them valid YAML. In an attempt to address OCPBUGS-30080, I want to process the CVO manifests through `oc adm release new` machinery, which requires them to be valid YAML.

NO-JIRA: manifests: make template manifests valid YAML

---

pkg/cvo/status.go
pkg/cvo/status_test.go
pkg/payload/task.go

When it takes too long (90m+ for machine-config and 30m+ for
others) to upgrade a cluster operator, clusterversion shows
a message with the indication that the upgrade might hit
some issue.
This will cover the case in the related OCPBUGS-23538: for some
reason, the pod under the deployment that manages the CO hit
CrashLoopBackOff. Deployment controller does not give useful
conditions in this situation [1]. Otherwise, checkDeploymentHealth [2]
would detect it.
Instead of CVO's figuring out the underlying pod's
CrashLoopBackOff which might be better to be implemented by
deployment controller, it is expected that our cluster admin
starts to dig into the cluster when such a message pops up.
In addition to the condition's message. We propagate Fail=Unknown
to make it available for other …

OCPBUGS-23514: Failing=Unknown upon long CO updating

---

cmd/cluster-version-operator/start.go
pkg/start/start.go
pkg/start/start_integration_test.go

Extract option validation to a new `ValidateAndComplete()` method, and run it separate from `Run()` through cobra `PreRunE` feature.
Refactor the `AlwaysEnabledCapabilities` processing to be consistent with how the other options are processed. The `NewControllerContext` is a method on `Options` struct, so it does not make sense to pass it some options through the struct, and some options through method parameters. I went further and separated the validation (performed with all other validation) from conversion, resulting in two smaller methods instead one larger one. The result is slightly less efficient but more readable.
The reason to do this refactor is that I need to clean up the `NewControllerContext` constructor. I will need to do some changes around, and removing the explicit pass …

OTA-1531: [1/x] cvo: refactor option processing

---

pkg/payload/payload.go

Builds on: https://github.com/openshift/cluster-version-operator/pull/1184
Extract loading tasks from `loadUpdatePayloadMetadata` one layer up to `LoadUpdate`, which makes more sense as a logical sequence of "loading the update". This also allows simplifying `loadUpdatePayloadMetadata` signature because the inputs for loading tasks are partially disjoint from the ones needed for loading the metadata.
The architecture is either read from release metadata when present (and in that case it must be a string and must be multi) or determined from runtime in all other cases. Refactor `loadReleaseFromMetadata` so that it only really reads the metadata, and move the "when metadata does not have architecture, read from runtime" logic to `loadPayloadMetadata` above (the `loadReleaseFromMetadata` …

OTA-1531: [2/x] cvo: refactor `LoadUpdate`

---

pkg/payload/payload.go
pkg/start/start.go

Builds on https://github.com/openshift/cluster-version-operator/pull/1185
CVO is typically executed in a Pod using the release payload image, which means its filesystem contains (among other content) the release metadata which the CVO can use to determine its OCP version, which is helpful to establish the feature gate enablement data to drive gated CVO behaviors.
It is useful to establish the feature gate enablement checker early in the CVO execution because it broadens the part of CVO code that can contain gated behavior (until the checker is established it is not possible to determine whether a gate is enabled or disabled)
Loading the full payload is still quite heavy operation and can only be done later in the execution (after the CVO acquires leader lease). The early metadata peek …

OTA-1531: [3/x] cvo: read version from release metadata on startup

---

pkg/start/start.go
pkg/start/start_integration_test.go

The code to set up informers is messy so this change attempts to make it more consistent:
- Alias all informer-related imports to `somethinginformers`
- Everything made by `NewSharedInformerFactory` methods is now called `somethingInformerFactory`
- Name factories in `Context` consistently: `SomethingFactory`
- Document the purpose of individual factories in `Context`
- Reorder code into clusters that deal with individual factory types
---
[OTA-1531](https://issues.redhat.com//browse/OTA-1531) will need the config.openshift.io group lister early in the CVO execution and outside of the `Context` structure, so this commit moves the necessary preparation code outside of `NewControllerContext` and passes these factories into it as parameters. Constructing factories at separate places is a …

OTA-1531: [4/x] cvo: extract config informer creation

---

.openshift-tests-extension/openshift_payload_cluster-version-operator.json
Makefile
hack/build-go.sh
hack/build-info.sh
hack/update-test-metadata.sh

Create an update target in the Makefile to execute the tests-extension update logic to update/validate test metadata. Add `git diff` logic to the verify target to make sure any uncommitted changes fail the execution of the target. This will be run on PRs to make sure the test metadata is commited and valid.
For more info on the update subcommand, see [ Update - Metadata Validation](https://www.github.com/openshift/enhancements/pull/1676/files#diff-3830bd2c970bd4daeeecea1e6624237b0694bdd8872c70b7042225bd6b636010R851-R867)

OTA-1403: Update and Verify Test Metadata Using Makefile

---

pkg/featuregates/featuregates.go
pkg/start/start.go

Extracting config.openshift.io informer factories allows to obtain the `FeatureGate` lister early. We need to start the the config informer factory for that but that is fine, later code can create new informers as long as it calls `Start()` again. Retrieved `FeatureGate` can then be used to read the featureSet enabled in the cluster and also the enabled and disabled CVO feature gates.
This is basically identical to what CVO currently does later in `Context.InitializeFromPayload`. For now _that_ code drives the actual CVO behavior, not the values discovered by the early code. The change to switch the CVO behavior from respecting the late code to the early code will follow; this commit just sets the stage for that and allows testing the early informer start.

OTA-1531: [5/x] cvo: read cluster `FeatureGate` early

---

pkg/cvo/status.go
pkg/cvo/status_test.go

It is a mistake introduced by https://github.com/openshift/cluster-version-operator/pull/1157/files#diff-db97dc5ae62ef3b4c4dabfdc43cbc3ae0ceae9b58748cadebde679e32b5bec2bL175
As a result, it changes the type name in ClusterVersion which was definitely not the intension of https://github.com/openshift/cluster-version-operator/pull/1157. So we change the constant back with this pull.
The mistake is [found](https://issues.redhat.com/browse/OTA-1533?focusedId=27163593&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-27163593) by @jiajliu while doing the pre-merge testing for https://github.com/openshift/cluster-version-operator/pull/1133.
It looks like I was not careful enough before confirming IDE (GoLand)'s smart editing. My apologies for that.
Additionally, a …

OCPBUGS-56114: Fix ImplicitlyEnabledCapabilities

---

Makefile

Fix the name of the script called, so that I can pass rehearsals in https://github.com/openshift/release/pull/65742 and then eventually remove the script in https://github.com/openshift/cluster-version-operator/pull/1202

NO-JIRA: tests: fix `make integration-test` target

---

pkg/cvo/cvo.go
pkg/featuregates/featurechangestopper.go
pkg/featuregates/featurechangestopper_test.go
pkg/featuregates/featuregates.go
pkg/start/start.go
pkg/start/start_integration_test.go

Previous changes prepared the code for this switch by adding code to detect enabled CVO gates and featureset early in the CVO execution, right before the controllers are initialized (well before CVO acquires its leader lease and actually starts the controllers). These early detected gate checker was not used anywhere yet.
This change makes CVO stop using its late detected gate checker (detected while loading its initial payload) and start using the early one instead. This eliminates the need for the panicking gate checker that was used to guard against checking gates before the actual checker could be established.
The change also allows to simplify some code layers. Late initialization on initial payload load is now only necessary for the actual CVO controller, not the …

OTA-1531: [6/6] cvo: use early gate checker to avoid delayed initialization

---

Makefile

It is stored in the $ARTIFACT_DIR folder in CI which is integrated in Prow's portal [1].
[1]. https://docs.prow.k8s.io/docs/spyglass/

NO-JIRA: Generate junitfile for unit tests

---

pkg/start/start.go

- The `FeatureGate` GET is now made over an informer client which is backed by a cache, so polling to smooth over non-isNotFound errors no longer makes sense. The GET runs after a cache sync succeeded earlier so no errors are expected (and if an error happens, it is unlikely to be resolved by a retry)
- Waiting for cache sync was not bounded; impose a 30s timeout on startup (this is similar to the deadline imposed by the poll before we started to use the informer client)

OTA-1531: Rework error handling in FeatureGate processing

---

.openshift-tests-extension/openshift_payload_cluster-version-operator.json
test/cvo/cvo.go

Per the integration guide for OTE, each test must have a clearly defined owner (by using a `[Jira:Component]` tag) or an entry in the ci-test-mapping repository. Naming the owner as `"Cluster Version Operator"` with spaces, as this is the format used to distinguish our component in the mapping repository [[1]].
Renaming tests should not be done without a proper setup, as this can lose a test's history. However, this test was never executed, and it acts as a signal of the OTE integration.
[1]: https://github.com/openshift-eng/ci-test-mapping/blob/b2ca5844ead12ede1cb72cae34321f3215beb6e3/pkg/components/clusterversionoperator/component.go#L14

OTA-1585: test: Rename an existing test to comply with the OTE integration guide

---

pkg/cincinnati/cincinnati.go
pkg/cincinnati/cincinnati_test.go
pkg/cvo/cvo.go
pkg/payload/payload.go

Instead of carring similar code in the payload and Cincinnati packages, centralize in one place to make maintenance easier.  And with the logic centralized, I've also put some time into hardening the channel parsing, to grumble about some possible issues.
For payload loading, errors get a logged warning, but are not fatal. Having the CVO come up with logged warnings still allows cluster admins to update into a fix.  But a crash-looping CVO would not notice ClusterVersion `spec.desiredUpdate` changes or be able to roll out a requested update into a fix.
For Cincinnati processing, errors are fatal.  Cluster admins can take the ClusterVersion `RetrievedUpdates=False` message and complain to their Update Service maintainers, who can fix the metadata.

OTA-1627: pkg/cincinnati: Centralize release metadata parsing
