openshift/cluster-version-operator

- pkg/cvo/update.go
A strong type system could have caught this.
> cvo: properly update OperatorStatus

- OWNERS
> *: add OWNERS file

- README.md
- hack/push-image.sh
> add README.md

- pkg/cvo/internal/dynamicclient/client.go
> dynamicclient: reset restmapper cache and try again on nomatch error

- OWNERS
> approvers: update OWNERS to promote wking and abhinavdahiya to approvers 

- docs/dev/clusteroperator.md
- docs/dev/operators.md
> docs: add docs for ClusterOperator for operators

- docs/dev/operators.md
Reserves 05 for the checkpointer run level.
> docs: add checkpointer operator run level

- docs/dev/clusteroperator.md
Provide guidance and examples about the messages and how they should be
structured.
> docs: Capture how to write messages for cluster operator conditions

- docs/dev/clusteroperator.md
Clarify condition meanings and harmonize with the API.
The different dimensions are clarified and the impact of each being in a "bad" state is described.
/assign @smarterclayton 
/cc @bparees
> docs: update status explanation

- pkg/cvo/internal/operatorstatus.go
This reverts commit 4067fb0143207bdfeacc5d1b6f992f370dd2f671.
/assign @deads2k
> Revert "clusteroperator: return RetryLaterError on not found"

- install/0000_00_cluster-version-operator_03_deployment.yaml
@smarterclayton @derekwaynecarr
> set cpu request for operator

- hack/test-prerequisites.go
Don't fail immediately, retry until timeout or we succeed, logging the
errors. The master sometimes takes a few seconds to stabilize.
> test: hack/test-prerequisites.go was seeing a few flakes, retry differently

- pkg/cvo/metrics_test.go
I wasn't sorting sufficiently to prevent flakes in #107. Tested with -count=1000.
> metrics: Fix flaky unit test from transition

- pkg/cvo/internal/operatorstatus.go
- pkg/cvo/internal/operatorstatus_test.go
> wait for COs versions to be correct

- pkg/cincinnati/cincinnati.go
- pkg/cincinnati/cincinnati_test.go
- pkg/start/start_integration_test.go
This adds three mandatory parameters to cincinnati requests, as per cincinnati-openshift specs.
Ref: https://github.com/openshift/cincinnati/blob/06c9ce64367b55f453295b2765a9aab61791dc76/docs/design/openshift.md#request
This PR is an enhancement of https://github.com/openshift/cluster-version-operator/pull/85 adding unit and integration tests that verify that the query parameters are included in the requests to cincinnati.
> pkg/cincinnati: add required parameters to requests

- pkg/cvo/sync_worker.go
> pkg/cvo: report actual metrics on Complete()

- install/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
Fixes printer column for rendering version of operator.
> install: fix column rendering for clusteroperator version

- docs/dev/clusteroperator.md
replaces https://github.com/openshift/cluster-version-operator/pull/130
> Update ClusterOperator docs for changes to versions and cluster-scoped

- pkg/start/start.go
While running integration tests in loops I was able to trigger a
double close panic. Leader election doesn't guarantee exclusion
in the handlers, and until we have step down from 1.13 client-go
we need to guard.
> leaderelect: Prevent double close channel panic when shutting down lease

- docs/dev/operators.md
Adds an explanation and warns people that it is unusual.
/assign @abhinavdahiya
> doc: explain the create-only annotation to developers

- pkg/cvo/cvo_scenarios_test.go
- pkg/cvo/sync_worker.go
- pkg/cvo/sync_worker_test.go
Previously the reported passed the Generation from its consumer directly to the update channel, therefore consumers like
syncOnce Downloading release image which were passing 0 Generation a do-not-care would end up updating clusterverison observed generation to 0
consistent reporter now preserves previous generation if consumer passed 0 ie do-not-care generation.
/cc @smarterclayton
> BUG 1703158 cvo: update the status reporter to preserve the previous Generation 

- pkg/start/start_integration_test.go
We flake occasionally when the status the sync worker reports is
partial - since the tests are already waiting to reach level, we
tolerate receiving a status history that is version="", image=X
since the sync worker may have that before it invokes retriev
payload.
> test: Tolerate when sync reports partial status "Working towards"

- lib/resourcebuilder/apps.go
Displays the Deployment Condition reason and message when
the Deployment is not progressing or there is a Replica failure.
Bug 1702582 - https://bugzilla.redhat.com/show_bug.cgi?id=1702582
Example:
```
E0515 20:17:10.936566       1 apps.go:82] Deployment kube-apiserver-operator is not ready. condition: (reason: ProgressDeadlineExceeded, message: ReplicaSet "kube-apiserver-operator-7dfb6ddb9d" has timed out progressing.)
I0515 20:17:10.936620       1 apps.go:86] Deployment kube-apiserver-operator is not ready. status: (replicas: 2, updated: 1, ready: 1, unavailable: 1)
```
> Bug 1702582: Log DeploymentConditions reason and message when Deployment is failing

- pkg/cvo/updatepayload.go
This change prunes the jobs in the openshift-cluster-version namespace
before creating a new one to download new update payloads. First, it
sorts them in chronological order and then calls delete for all except
the newest two.
> Bug 1665011: updatepayload: prune older jobs to maintain limit.

- lib/resourcemerge/apps.go
- lib/resourcemerge/apps_test.go
> Update Replica count too while ensuring deployment

- pkg/payload/image.go
- pkg/payload/payload.go
The `image` command currently loads the image-references file and then
renders all manifests. Clearly the manifest rendering can be avoided
when we just want to look up an image reference.
This command is currently run 17 times by bootkube, and my quick test
shows this refactor halving the roughly 10 seconds this takes.
The main refactoring here is to split the loadUpdatePayloadMetadata()
function into getPayloadTasks() and loadImageReferences() so that the
latter can be used standalone in this particular case.
> pkg/payload/image: avoid rendering manifests

- docs/user/reconciliation.md
- lib/resourcemerge/batch.go
- lib/resourcemerge/batch_test.go
Tracing code and unit testing to help understand
> Bug 1794823: lib/resourcemerge: Do not attempt to change Job's immutable spec.selector

- pkg/verify/verifyconfigmap/store.go
> Bug 1782982: pkg/verify/verifyconfigmap: Fix Store to use {algo}-{hash} prefix

- pkg/cvo/sync_worker.go
> pkg/cvo/sync_worker: Fix "successfull" -> "successful" typo

- pkg/cvo/updatepayload.go
Typo is from ed7fab15a1 (#29).
> pkg/cvo/updatepayload: Fix "deafult" -> "default" typo

- lib/resourcebuilder/apps.go
Test whether the error on the progressing path is causing us to reset
log output during upgrades and flag spurious errors.
Exploring why we see an "unknown error" and all pod progressing status
printed.
> Do not report errors to status loop on progressing

- OWNERS
> Add LalatenduMohanty to the owner list

- pkg/cvo/sync_worker.go
- pkg/payload/precondition/clusterversion/upgradeable.go
To make it easier to debug precondition failures like [rhbz#1827166][1].
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1827166
> Bug 1827166: pkg/cvo/sync_worker: Log precondition handling

- pkg/cvo/status.go
This slipped through in 7c52414095 (#47).
> pkg/cvo/status: Fix "syncDegradedStatus" -> "syncFailingStatus" comment

- pkg/cvo/upgradeable.go
> Fixing spelling of notUpradeableCondition

- docs/dev/metrics.md
- pkg/cvo/metrics.go
This should have been updated in e57f170c. Shame on me.
> docs: update cluster_installer description

- hack/build-go.sh
> Fix typo in goarch variable

- pkg/cvo/sync_worker.go
> Fixing go doc for equalUpdate()

- pkg/cvo/sync_worker.go
Ignore version and overrides changes during payload initialization and log warning.
> Bug 1905221: pkg/cvo/sync_worker.go: Ignore work changes during init

- lib/resourcebuilder/batch.go
> Bug 1918085: Fixing the log message in WaitForJobCompletion()

- pkg/cvo/updatepayload.go
Snuck into the logs with 687686e10d (#493).
> pkg/cvo/updatepayload: Fix "verifcation" -> "verification" typo

- pkg/cvo/sync_worker.go
Also adds logging of work change details.
> Bug 1921180: pkg/cvo/sync_worker.go: Ignore work changes during init

- install/0000_00_cluster-version-operator_00_namespace.yaml
- install/0000_00_cluster-version-operator_02_roles.yaml
- install/0000_00_cluster-version-operator_03_deployment.yaml
- install/0000_90_cluster-version-operator_00_prometheusrole.yaml
- install/0000_90_cluster-version-operator_01_prometheusrolebinding.yaml
- install/0000_90_cluster-version-operator_02_servicemonitor.yaml
- install/0001_00_cluster-version-operator_03_service.yaml
This is matches openshift/enhancements#510 and doesn't change existing behavior
> Bug 1925199: add current profile annotations to CVO manifests

- pkg/cvo/cvo.go
- pkg/cvo/status.go
This reverts commit dfc8494a4ed9b4e68d7511ae989cbf3225d65e65, reversing
changes made to bac69e03599f8c57f46585246618e462c31c2e93.
> Revert "Merge pull request #523 from jottofar/cv-logging"

- docs/user/status.md
Local analog for openshift/openshift-docs#22252.
> docs/user/status: Mention channel-clearing for VersionNotFound

- docs/user/reconciliation.md
The raw console dump doesn't give folks a lot of context on its own, so let folks know what we're demonstrating with each command.
> docs/user/reconciliation: Add some English to the release image inspection

- hack/generate-lib-resources.py
Catching the generator up with ce2874f129 (#443).
> hack/generate-lib-resources: Use library-go manifests

- README.md
- docs/dev/clusteroperator.md
- docs/user/update-workflow.md
> Docs: Adding the update workflow

- OWNERS
ref: https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md#emeritus
> Move some approvers to emeritus_approvers

- OWNERS
> OWNERS: Prune crawford

- docs/dev/feed-cvo-custom-graphs.md
> Adding docs to test CVO with custom update graph

- install/0000_90_cluster-version-operator_02_servicemonitor.yaml
> Bug 2005407: Changing the ClusterNotUpgradeable alert to info

- install/0000_00_cluster-version-operator_01_admingate_configmap.yaml
> Bug 2025955: Removing the extra indentation

- Makefile
> Bumping the GOLANGCI_LINT_VERSION to v1.43.0

- pkg/cvo/sync_worker.go
Reverts openshift/cluster-version-operator#713.  We'll restore something very similar soon, but in the meantime, a revert will avoid the [worker-cancel hotlooping we're seeing sometimes in CI][1].
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=2009845#c8
> Revert "Bug 2009845: Respect overrides changes during install"

- pkg/cvo/sync_worker.go
We'd taken a pass at this in bee2a5e634 (#713), but subsequently reverted in 11bca782a8 (#727), due to [some hot-looping on overrides-change detection][1].
With this new attempt, we're lifting the state check up out of `equalSyncWork`, where it has lived since the check landed in 213726df85 (#500).  This allows us to guard more specifically in the `Update` method, keeping `spec.desiredUpdate` changes out of the sync worker's work config until we complete installation, while passing `overrides` changes through.
On the sync-worker side, `calculateNext` keeps its traditional behavior of accepting any work that the `Update` method set up for it.  It does grow a new guard to keep it from transitioning from `InitializingPayload` to `UpdatingPayload`.  With the new guard, the only way to …
> Bug 2009845: Respect overrides changes during install (second round)

- lib/resourcebuilder/batch.go
Avoid waiting for a job that that job controller has given up on.  With this change, when we have issues like `DeadlineExceeded`, we will set `err != nil` for "things are not good" and (new in this commit) `done == true` for "waiting longer is useless".  Also split the `err != nil` cases to "log the error and wait longer" and (new in this commit) "bubble the error up to the caller" cases.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=2062568#c0
> Bug 2062568: lib/resourcebuilder/batch: Stop waiting on Job deadline exceeded

- pkg/cvo/sync_worker.go
so `syncPayload` does not return nil value and stomp on valid implicitly enabled capabilities value.
> Bug 2079789: pkg/cvo/sync_worker.go: Initialize implicitlyEnabledCaps

- install/0000_00_cluster-version-operator_01_admingate_configmap.yaml
> admin-gates: Add ack-4.11-kube-1.25-api-removals-in-4.12 gate

- pkg/cvo/cvo.go
- pkg/cvo/cvo_scenarios_test.go
- pkg/cvo/status.go
- pkg/cvo/sync_worker.go
when an upgrade in progress is cleared.
> Bug 2094174: pkg/cvo: reset payload load status

- OWNERS
@vrutkovs is focusing on assisted-installer stuff now.
> OWNERS: Prune vrutkovs

- pkg/cvo/cvo_scenarios_test.go
This unnecessary final check was originally added to utilize the newly added expectFinalUpdateStatus function to expose it for future use when test cases are modified or added. Multiple statuses are set making hitting the exact one difficult due to timing which can cause failures. TestCVO_InitImplicitlyEnabledCaps was modified to now use expectFinalUpdateStatus.
> pkg/cvo/cvo_scenarios_test.go: Remove status check from TestCVO_UpgradeFailedPayloadLoadWithCapsChanges

- OWNERS
I'd like to get assigned to PRs as a reviewer, and also approve/override when necessary. We spoke about reviews with David yesterday and he's interested in getting assigned too (he's doing informal reviews out of interest but never gets assigned), so I added him as a reviewer (for which I needed to introduce reviewers).
@Davoska FYI
> Add myself as approver and David Hurta as a reviewer

- go.mod
- go.sum
- vendor/github.com/openshift/library-go/pkg/manifest/manifest.go
- vendor/modules.txt
bring in https://github.com/openshift/library-go/pull/1408
> update library-go to pick up feature-set annotation change

- pkg/cvo/upgradeable.go
Previously, CVO could use a `ClusterVersion` lister before its informer's cache was synced, leading to the following noise in a CVO log, that could also propagate into an `Upgradeable=False` condition and cause user-observable noise:
```
Unable to get ClusterVersion, err=clusterversion.config.openshift.io "version" not found
```
This is coming from one of the upgradeable checks called inside `setUpgradeableCondition`. This method is called in two scenarios: 
- in `ConfigMap` informer create/update/delete handlers
- in `syncUpgradeable->upgradeableSync` path that handles work items  from the `upgradeableQueue` queue. This path throttles the sync and only sets the conditions if sufficient time passed since the last sync
The failure case is that while caches of all informers are synced, the …
> OCPBUGS-1443: Avoid using a lister before client caches sync

- pkg/cvo/upgradeable.go
Improve logging in upgradeability checker. Based on @wking 's suggestions, I went a little further and refactored the code slightly. I got rid of the two duration helpers: they were only used from these callsites and I believe that with careful naming and structure we can have readable code without them.
> upgradeable: improve logging and refactor

- OWNERS
As Jack is happily retired now.
> Adding David to approvers list and removing Jack 

- pkg/clusterconditions/cache/cache.go
- pkg/clusterconditions/mock/mock.go
- pkg/clusterconditions/promql/promql.go
- pkg/cvo/availableupdates.go
- pkg/cvo/availableupdates_test.go
- pkg/cvo/cvo_scenarios_test.go
Picking #974 and #980 back to 4.12.
> OCPBUGS-22408: pkg/clusterconditions/promql: Warm cache with 1s delay

- go.mod
- go.sum
- vendor/github.com/openshift/api/config/v1/feature_gates.go
- vendor/github.com/openshift/api/config/v1/types_feature.go
- vendor/modules.txt
Enable TranslateStreamCloseWebsocketRequests through TechPreviewNoUpgrade.
> OCPBUGS-27468: bump(openshift/api)=master to pick up new TechPreviewNoUpgrade features

- pkg/cvo/sync_worker.go
Retrieving payload is a potentially long-running operation (download can be slow or even timing out), and `RetrievePayload` is called while holding the `SyncWorker` lock. Holding the lock for extensive amount
of time prohibits the manifest applying look from proceeding, resulting in failures to reconcile state in the cluster.
`RetrievePayload` does not have access to anything protected by the lock, so I believe we can safely yield the lock for its duration and reacquire it afterwards.
~In addition to the bugfix, I refactored some lock-related code in `SyncWorker` code. I recommend reviewing per-commit, individual changes are fairly isolated but squashed together they could be confusing.~ moved to https://github.com/openshift/cluster-version-operator/pull/1020
---
This is why I think …
> OCPBUGS-7714: yield lock while retrieving payload

- pkg/customsignaturestore/customsignaturestore.go
- pkg/cvo/availableupdates.go
- pkg/cvo/cvo.go
- pkg/cvo/egress.go
> OCPBUGS-24700: Add support for Custom Certificate Authorities for custom signature stores

- pkg/customsignaturestore/customsignaturestore.go
- pkg/cvo/availableupdates.go
- pkg/cvo/cvo.go
- pkg/cvo/egress.go
Reverts openshift/cluster-version-operator#1030
> OCPBUGS-35236: Revert: Add support for Custom Certificate Authorities for custom signature stores"

- lib/capability/capability.go
- lib/resourcedelete/apiext.go
- lib/resourcedelete/apps.go
- lib/resourcedelete/core.go
- lib/resourcedelete/imagestream.go
- lib/resourcedelete/rbac.go
- lib/resourcedelete/security.go
- pkg/cvo/cvo.go
- pkg/cvo/status.go
typo: change previousily to previously
> NO-JIRA: typo change previousily to previously

- pkg/cvo/cvo_scenarios_test.go
Follow up https://github.com/openshift/cluster-version-operator/pull/1081#discussion_r1763025442 and https://github.com/openshift/cluster-version-operator/pull/1081#discussion_r1763031370
> NO-JIRA: Simplify unit test TestCVO_UpgradeVerifiedPayload

- OWNERS
I have updated my GitHub username. I am updating OWNERS files.
> NO-JIRA: OWNERS: Update the username of David Hurta

- pkg/payload/task_graph.go
- pkg/payload/task_graph_test.go
I want to eventually resolve [OCPBUGS-22442](https://issues.redhat.com/browse/OCPBUGS-22442) but this code is ancient and it took me a while to understand it. While I was grokking I made several opportunistic improvements which hopefully simplify the code and make it easier to understand.
> NO-JIRA: task graph: comments and cleanups

- pkg/payload/task_graph_test.go
The test was a layered amalgam with multiple types of inputs (task
graph, paralellism, `errorOn` which ended up being used for arbirary
callback use cases) and expected outputs (most used by just one or two
testcases).
- document test inputs
- improve invariants to be better readable for individual testcases
- describe desired properties as invariants
- restructure `errorOn` as `callbacks` to be called for individual
tasks rather than a single big function with `if` matching tasks
> NO-JIRA: task graph: improve TestRunGraph tests

- pkg/payload/precondition/clusterversion/gianthop.go
- pkg/payload/precondition/clusterversion/recommendedupdate.go
- pkg/payload/precondition/clusterversion/rollback.go
- pkg/payload/precondition/clusterversion/upgradeable.go
- pkg/payload/precondition/precondition.go
Follow up https://github.com/openshift/cluster-version-operator/pull/1112#discussion_r1852870478 and https://github.com/openshift/cluster-version-operator/pull/1112#discussion_r1852872232
> NO-ISSUE: Simplify the preconditions code

- pkg/updatestatus/controlplaneinformer.go
- pkg/updatestatus/controlplaneinformer_test.go
[OTA-1418](https://issues.redhat.com//browse/OTA-1418): Allow forcing health insights on CV
When a `ClusterVersion` is annotated with `usc.openshift.io/force-health-insight`, make USC emit a health insight, suitable for testing health insight lifecycle. Note that such health insight never goes away for now; this will be addressed by followup PRs.
Health insights UIDs are a hash of the insight message and the resources involved. This will become problematic if we ever want to do aggregation, but for now it suits the purpose.
Builds on #1138
/cc @hongkailiu 
/auto-cc
> OTA-1418: Allow forcing health insights on CV

- pkg/updatestatus/updatestatuscontroller.go
Going from USC-scrapes-all-insights periodically to unidirectional
message passing makes insight lifecycle a bit harder (if an informer is
not saying anyting about an insight Status API knows about, is it just
unchanged, or did the informer lose track of it?).
List of known insight UIDs is lightweight-enough payload to be included
in every message sent to USC and the USC can (eventually) drop the
insights that the informer stops reporting as known, and can drop
the insights the informer requests to be dropped.
Unsure whether this mechanism survives until the final version but it is
reasonably robust for the current state.
> OTA-1418: Decribe informer->usc communication

- lib/capability/capability.go
- lib/capability/capability_test.go
- pkg/cvo/sync_worker.go
- pkg/payload/payload.go
- pkg/payload/payload_test.go
Will rebase after https://github.com/openshift/cluster-version-operator/pull/1157
> NO-JIRA: Use k8s.sets for the fields of ClusterCapabilities

- Makefile
> NO-JIRA: Makefile: verify -> verify-yaml

- docs/dev/README.md
The credits regarding the "_workarounds/hacks_" go to Vadim and Petr :bow:
> NO-JIRA: Extend the development documentation regarding building and publishing a payload image
